### ISSUE TITLE
Memory optimisations for notifications have resulted in epochMillis not being set correctly for notifications

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1003]
### Describe the bug

1. We are now re-using the same AtNotificationBuilder object in the NotifyVerbHandler every time. However, we are not explicitly setting the notificationDateTime in the verb handler. As a result, the notificationDateTime that is used is not the current time, but is instead either the time the AtNotificationBuilder was first created (when the verb handler was created at server startup) or when it was 'reset' during the last previous execution of the verb handler.
2. The code as it stands is vulnerable to race conditions. Right now If we are going to reuse a single AtNotificationBuilder then we need to wrap the entire body of NotifyVerbHandler.processVerb in a `try {get mutex; ...; ...; } finally {release mutex}`
3. As it's possible that other bugs were introduced in these code changes, the changes should be re-reviewed in detail.

### Steps to reproduce

Send some notifications.

### Expected behavior

epochMillis should be correct

### Additional context

Bug observed by @ralfeus

**Comment by VJag** [comment]
@gkc ack

**Comment by sitaram-kalluri** [comment]
@gkc  and @VJag : 

Following are the proposed code changes to fix the issue: 

1. Move the entire processVerb method into a try and finally block where we acquire the mutex lock when entering and release the lock after completion.
2. Explicitly set the notification DateTime to the atNotificationBuilder in the NotifyVerbHandler.processVerb method and NotificationUtil.storeNotification method.
3. Call reset method in finally block on processVerb instead of having calls to reset method in various places in the processVerb method. (or) call reset method during the start of the processVerb so that the previous notification data is reset and DateTime is updated to the current date time before processing the notification. Along with #‎2, calling the reset method at the start of processVerb would be an additional check.

**Comment by VJag** [comment]
@kalluriramkumar 1 and 3 are good.

2. I think the ask is to set the notification date time to now when the Notification bean is created and not used the one from the NotificationBuilder.

@gkc may I know if the way 2 is stated is what you had in mind?

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar 1 and 3 are good.
> 
> 2. I think the ask is to set the notification date time to now when the Notification bean is created and not used the one from the NotificationBuilder.
> 
> @gkc may I know if the way 2 is stated is what you had in mind?

At the moment, the notificationDateTime is a private member in AtNotification. So, if we wanted to set date time directly on atNotification object, we have to make it public or expose a getter and setter.

**Comment by VJag** [comment]
Not really I think the default value will be now(). Is the idea to set it from the value taken in the verb from SDK? If not then now() will probably do. Otherwise, if the intent is to set it right when the notification is sent out to the recipient then it has to be exposed.

**Comment by gkc** [comment]
> > @kalluriramkumar 1 and 3 are good.
> > 
> > 2. I think the ask is to set the notification date time to now when the Notification bean is created and not used the one from the NotificationBuilder.
> > 
> > @gkc may I know if the way 2 is stated is what you had in mind?
> 
> At the moment, the notificationDateTime is a private member in AtNotification. So, if we wanted to set date time directly on atNotification object, we have to make it public or expose a getter and setter.

Or could call builder.reset() at the start of the verb processing - i.e. **before** using the builder rather than after.

**Comment by gkc** [comment]
> Not really I think the default value will be now(). Is the idea to set it from the value taken in the verb from SDK? If not then now() will probably do. Otherwise, if the intent is to set it right when the notification is sent out to the recipient then it has to be exposed.

Historical behaviour was `now()` so we should do that for now

**Comment by gkc** [comment]
Thanks @kalluriramkumar - I've approved the PR. Can you add a label to this issue for estimate on number of SPs effort this took, please?

**Comment by sitaram-kalluri** [comment]
> Thanks @kalluriramkumar - I've approved the PR. Can you add a label to this issue for estimate on number of SPs effort this took, please?

Thank you, @gkc. Spent 4SP on this issue.
