### ISSUE TITLE
Check the secondaries that come up as failing on scan and 0/0 in daily reports

### ISSUE THREAD

**Issue by kumarnarendra701** [atsign-foundation/at_server#1024]
### Describe the bug

On the daily report, a few secondaries are showing in a 0/0 state.

### Steps to reproduce

Check gChat report

### Expected behavior

No alerts in gChat for 0/0 state

**Comment by kumarnarendra701** [comment]
@cpswan - I have checked this atsign and found that I had deleted the storage directory to make it Problematic secondary so that Srie teja/Ashish can do error handling.

```
01-04.us-central1-a.c.development-305719.internal   Ready           Rejected 2 seconds ago    "invalid mount config for type "bind": bind source path does not exist: /gluster/@/secondaries/a5/c5/28/ff/a5c528ff09c7e07f3eeeaffd53fac2be/d6601b65-d44f-520a-9525-d7fc336aba6b/storage"   
```

**Comment by cpswan** [comment]
@kumarnarendra701 do we still need that problematic secondary?

**Comment by kumarnarendra701** [comment]
@cpswan - I have confirmed with Ashish and now we don’t need it so I have deleted it.

**Comment by kumarnarendra701** [comment]
@cpswan - Can we close this?
