### ISSUE TITLE
AWS credits at the end, pruning required

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#1039]
We had a significant credit on AWS the last two years but it is drawing to a close. As such we should remove everything that we do not need.
 If we have services that have to be on AWS that is fine but lets make sure we are investing $'s widely.

**Comment by kumarnarendra701** [comment]
@cconstab @cpswan - Can I get the AWS creds? So that I'll create a list of services that are used then based on your feedback, I'll remove unused services.

**Comment by cpswan** [comment]
@kumarnarendra701 given the number of AWS accounts we have it's probably going to be just as quick for me to do this myself as it will be to work my way through assigning you access.

**Comment by cpswan** [comment]
Firstly a look at the bill from last month:

$1367.61 total
$925.55 EC2
$241.41 RDS
$74.40 EKS
$72.71 WorkSpaces

leaving $53.54 for other stuff (S3, ELB, data egress, Backup). So let's focus fire on EC2 and RDS (and remind ourselves why EKS is even there).

Going account by account:

filebin2-prod - just S3, nothing to prune
aws-atsign-wasp - nothing running
atsign-cicd - $37.80/m for CICD instances that we know are frequently used
atsign-playpen - $31.65 for WorkSpaces, they're using AutoStop, so nothing much to be done there.
there are a bunch of burning and turning ec2 instances of various sizes that could probably be taken down - topic for eng stand.
The @ Company - a bunch of utility VMs (Discord, Minecraft), a Filebin2 service ($$$), and some strays.

**Comment by cpswan** [comment]
Filebin2 and various VMs terminated/deleted, which should take the bulk of the cost out going forward. The Nov bill will be ~$800 as we've already been burning for half the month, and there's a residue of stuff that we need to keep ticking along.
