### ISSUE TITLE
Fix deprecation warnings on infrastructure_root_manager GitHub Actions

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1053]
### Is your feature request related to a problem? Please describe.

Actions runs such as https://github.com/atsign-company/infrastructure_root_manager/actions/runs/3466873608 are showing deprecation warnings like:

![image](https://user-images.githubusercontent.com/478926/201919156-23c47f7d-c004-4daf-82a5-8f7e4790cef5.png)

### Describe the solution you'd like

Modify workflows to make use of supported methods e.g. using using google-github-actions/auth

**Comment by kumarnarendra701** [comment]
@cpswan This fix is available on this #1045 PR
https://github.com/atsign-company/infrastructure_root_manager/pull/27

**Comment by cpswan** [comment]
Thanks @kumarnarendra701 

Can you search across other repos to find where we might need to make similar changes.

**Comment by kumarnarendra701** [comment]
@cpswan - Updated on below repos.
https://github.com/atsign-company/infrastructure_root_manager
https://github.com/atsign-company/registrar_node
https://github.com/atsign-company/at_handle_registrar_web
https://github.com/atsign-company/infrastructure_api
https://github.com/atsign-company/at_find_api
