### ISSUE TITLE
Index server deploy and go live

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#108]
- [x]  Run secondary storage of index server on Redis (at_server)
- [x]  Test (developer) that it works with both Redis and ES (at_server)
- [x]   Expose @index and @Search verbs in SDK (at_sdk)
- [x]   Implement CommitLog in Redis
- [x]  Implement AccessLog in Redis
- [x]  Implement NotificationLog in Redis
- [x] Make Notification Subsystem to work with NotificationLog
- [x] Make Sync work with Commit Log
- [x] Make CommitLog compaction work with Redis CommitLog
- [x] Make TTR refresh job work with RedisKeyStore
- [x]   Unit tests
- [x]   Dev testing
- [x]   QA testing

**Comment by purnimavenkatasubbu** [comment]
While testing with @wavi came across an issue
https://github.com/atsign-company/at_settings/issues/342
