### ISSUE TITLE
Build a WASM (from Dart) prototype on EDJX

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1096]
### Is your feature request related to a problem? Please describe.

Not related to a problem

### Describe the solution you'd like

A basic WASM app (compiled from Dart) running on the EDJX platform as the first step to evaluating whether it might be suitable for atServers

**Comment by cpswan** [comment]
## Deploying WASM on EDJX

I've run through the [EDJURL Tutorial](https://docs.edjx.net/docs/latest/edjurl.html), hitting a minor snag with the CPP SDK leading to https://github.com/edjx/edjurl/issues/2, but with the previous release of the SDK things are working as they should.

## Building WASM from Dart

[dart2wasm](https://github.com/dart-lang/sdk/blob/main/pkg/dart2wasm/dart2wasm.md) is now part of the Dart SDK.

I've raised https://github.com/dart-lang/sdk/pull/50885 to better document how to get started.

[Experimenting with Dart and Wasm](https://medium.com/dartlang/experimenting-with-dart-and-wasm-ef7f1c065577) makes it clear that the Dart WASM implementation relies on [WASM GC](https://github.com/WebAssembly/gc/blob/master/README.md), which is presently at proposal stage with an experimental implementation in the V8 engine accessible through the [d8 command line](https://v8.dev/docs/d8).

I've reached out to @d-vison (CTO at EDJX) to enquire about their plans to support WASM GC.

Any further progress towards running a secondary on EDJX will be contingent on WASM GC becoming available.

**Comment by cpswan** [comment]
No reply from EDJX, so closing for now, as we won't be able to make progress without WASM GC (and we've already learned a bunch from the work so far).

**Comment by d-vison** [comment]
Hello @cpswan, this got lost in our email and we have just seen this issue. I would like to get more insight into your needs. I noticed that WASM GC is a garbage collector and we currently don't support this, but would like to understand more as we could consider adding support in the future.
