### ISSUE TITLE
kryz_9850 atSign failed to start on latest canary release - 3.0.26b

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1099]
### Describe the bug

On releasing the latest canary version - 3.0.26b, the `kryz_9850` atSign failed to restart.

Restart failed with the following error:

```
HiveKeystore|HiveKeystore get error: HiveError: Cannot read, unknown typeId: 158. Did you forget to register an adapter?
SecondaryServerBootStrapper|Uncaught error: Cannot read, unknown typeId: 158. Did you forget to register an adapter?
...
SecondaryServerBootStrapper|Somehow made it to the finally block - exiting with status 1
```

### Steps to reproduce

Released the canary version 3.0.36b and the issue occurred. The issue is specific to atSign `kryz_9850`

### Expected behavior

The atSign should start successfully.

**Comment by sitaram-kalluri** [comment]
The issue occurred when initializing the metadata cache due to an invalid key present in the Keystore.

Invalid Key: `public:ttl:-1:ttr:-1:datasignature:h35rdygk+fnvraeptv5uq7mtu/ct+a8mexoku0rsqslvbpqbccez29xbkqqm1pg03ptj373q3duwbqlcqeruf64rwaqylexadjmcmlyswswjc09h2g2kbvniss/tpqdln31xdzkyxhbfeh2gse2q1xgnxmwt0doe`

Fix:
Deleted the invalid key from the Keystore and able to start the atSign successfully.

**Comment by cpswan** [comment]
@kalluriramkumar can you please open another ticket for work to stop such malformed keys from making their way into the keystore.

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar can you please open another ticket for work to stop such malformed keys from making their way into the keystore.

@cpswan: We already have a validation to prevent malformed getting saved to Keystore which is done and published - https://github.com/atsign-foundation/at_server/issues/821.

**Comment by gkc** [comment]
@kalluriramkumar We need to understand clearly why this problem was only encountered on the restart for the most recent canary release, and not on previous restarts

**Comment by sitaram-kalluri** [comment]
> @kalluriramkumar We need to understand clearly why this problem was only encountered on the restart for the most recent canary release, and not on previous restarts

Sure Gary, will investigate the issue and update this ticket

**Comment by sitaram-kalluri** [comment]
@gkc  and @cpswan: Below is the analysis of why the `kryz_9850` atSign did not start successfully on the latest canary release (c3.0.26b).

Adding `await` before hiveKeyStore.init() method in AtSecondaryServerImpl (line no. 553) caused the issue to pop up.  When initializing the metadata cache If a malformed key is encountered, the exception is thrown. But since the method is async and await is not there server did start up successfully and accepted the inbound connection(s). In the latest canary release adding `await` caused the server to not start successfully and hence unable to accept the incoming connection.

Further, the reason behind added await before hiveKeyStore.init() method is, in order to remove the malformed keys, `getKeys` method is used, which internally uses a metadata cache to verify if the keys are expired. Without `await`, the metadata cache is not initialized completely and hence all keys are not returned. Hence added `await` to fetch all the keys in the KeyStore to remove the malformed key.

**Comment by cpswan** [comment]
Thanks @kalluriramkumar for the detailed explanation. I think that clears up the question we had. Closing.
