### ISSUE TITLE
get-gke-credentials failed with: failed to extract project ID

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1112]
### Describe the bug

Deploy_On_Dev_K8 action is failing:

> google-github-actions/get-gke-credentials failed with: failed to extract project ID, please set the "project_id" input, set $GCLOUD_PROJECT, or specify the cluster name as a full resource name.

### Steps to reproduce

See logs from https://github.com/atsign-foundation/at_server/actions/runs/3730138276

### Expected behavior

Workflow should complete successfully.

Workflow should only run when there have been changes made to root server or underlying dependencies.

### Screenshots

![image](https://user-images.githubusercontent.com/478926/208414575-22c8fef3-1599-4ec6-a91a-b3803d288f22.png)

**Comment by kumarnarendra701** [comment]
@cpswan - Please let me know if we can close this.
