### ISSUE TITLE
Version in the metadata not being updated

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#1126]
### Describe the bug

The "version" field in the metadata does not get updated after updating the key

### Steps to reproduce

1. First create a new key
2. Then  update the same key again
3. And then get() the value

### Expected behavior

The version field should be updated from 0 to 1 after the key is updated.

Also, the updatedAt, createdAt fields shows incorrect value

**Comment by sitaram-kalluri** [comment]
The changes are completed and awaiting review. No pending work

**Comment by sitaram-kalluri** [comment]
The changes are published in at_persistence_secondary_server: v3.0.46
