### ISSUE TITLE
End to end testing to include registrar

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1135]
### Is your feature request related to a problem? Please describe.

We presently use a set of pre provisioned secondaries for end to end tests (in this repo and at_client_sdk), but this doesn't test our ability to create (and destroy) new secondaries.

### Describe the solution you'd like

A workflow where:

* new secondaries are created and activated in the staging environment
* e2e tests are run against that secondary in a similar manner to existing e2e tests
* the secondaries are deleted on completion so we don't amass a pile of unused secondaries

**Comment by athandle** [comment]
@ksanty who is owner of this ticket?
@gkc @cpswan let me know what is required from me

Mentioned below are some documents that can help

https://docs.google.com/document/d/13I7peZ4O7sSNDw3gRXhGBtUpbn1bv3ipJUP3IN_A1LQ/edit
https://docs.google.com/document/d/1X9dbqeB5TE4XIlYzNdenGK1iNAseMs-HdllLF8XPBl8/edit#heading=h.fj6vx9bz6awc

**Comment by cpswan** [comment]
@athandle as discussed on the sprint planning call yesterday I created this ticket after a conversation with @gkc about what else we could do to ensure that our infrastructure is robust. @kumarnarendra701 is the primary assignee, but I expect he'll need some help from you.

The basis will be the existing e2e tests, and the new work will be spinning up fresh secondaries in an automated fashion, and deleting them afterwards. I expect the difficult part will be around credentials and ensuring the right keys get to the right places.

**Comment by ksanty** [comment]
Thanks @cpswan @athandle that's why I added you.

**Comment by kumarnarendra701** [comment]
Moving this to PR54

**Comment by kumarnarendra701** [comment]
@gkc @cpswan - Need your help to understand the requirement.

new secondaries are created and activated in the staging environment 

Question - I know about secondary creation but am unsure about activation. Can you please let me know the process of secondary activation?

e2e tests are run against that secondary in a similar manner to existing e2e tests

Question - Do we have any existing e2e against secondary?

**Comment by athandle** [comment]
c.c @sitaram-kalluri  @srieteja  if you can help

**Comment by gkc** [comment]
Hi @kumarnarendra701 

Imagine the following scenario in the End to end tests of the AtClient:
* Needs to register some new atSigns, have them running and get the CRAM keys of each one
* Then run various tests
* And finally delete those atSigns and their secondaries

@athandle I think this is all possible right now using a super-API-key just wanted to confirm

**Comment by athandle** [comment]
> * Then run various tests

@gkc I am not sure about this. Please help us with what tests we have to run.
I can help to create secondary and delete secondary.

**Comment by gkc** [comment]
The tests will be part of the AtClient end-to-end test suite. No additional tests for registrar (although we should separately take a look at what automated tests there are already for the registrar specifically)

**Comment by athandle** [comment]
thanks @gkc  I think we need to help @kumarnarendra701 how to run AtClient end-to-end test suite

**Comment by cpswan** [comment]
I thought we'd be using the at_server end to end tests, but in either case the tests are here in the repo (s) along with the scripts in GitHub Actions that run them.

The only difference is to provision an atSign for the tests, rather than using dedicated testing atSigns as we do at the moment.

**Comment by kumarnarendra701** [comment]
Please move it to the next sprint.

**Comment by athandle** [comment]
@kumarnarendra701 if you need help please ask from team don't keep ticket  with you

**Comment by kumarnarendra701** [comment]
Performed the below steps to achieve the e2e test(Create Atsign on runtime)
1. Hit Node API to create two Atsgin i.e e2etest1, e2etest2
2. Replace port no in config-e2e_test_runtime.yaml
3. Move config-e2e_test_runtime.yaml to config.yaml
4. Run the e2e test.
5. Delete Atsgin i.e e2etest1, e2etest2 after test.

Blocker -  Currently Node API create Atsign but didn't return port no but we need port no to be replaced in config.yaml to perform a test between both Atsign. So here I need @athandle help with API to return Atsign and port no.


Reference - 
https://github.com/atsign-foundation/at_server/blob/e2e_testing_1135/.github/workflows/at_server.yaml#L348
https://github.com/atsign-foundation/at_server/blob/e2e_testing_1135/tests/at_end2end_test/config/config-e2e_test_runtime.yaml


@gkc @cpswan - Can you please review my approach and let me know if I am in the right direction or if you think any alternative for this?

**Comment by cpswan** [comment]
@kumarnarendra701 can't you just ask the root server for the FQDN and port?

The overall approach is what I was expecting, though I'm not yet seeing stuff on activation (generating PKAM keys and getting them where they need to be for testing).

**Comment by gkc** [comment]
@kumarnarendra701 this is what I was looking for to start with, thank you. The MVP I had in mind was to add a job in the workflow which does the following
* Create and verify steps
  * creates the atSigns
  * looks up the atSigns' atServers' addresses via root.atsign.wtf:64
  * make openssl connection to the atServers' addresses and run "info:brief" command (to verify they are up)
* Onboarding steps
  * Run the [activate_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/bin/activate_cli.dart) program (takes atSign, cram key and root server parameters) for each atSign
    * if successful this will generate a .keys file for the atSign ~/.atsign/keys/@alice_key.atKeys
* E2E test steps
  * Create a config.yaml for the atSigns (as you are doing, but with the host and port populated with the addresses retrieved during the "Create and verify" steps above)
  * Generate an at_demo_data.dart file
    * this file contains the various keys for the e2e test atSigns, and currently this is held as a github secret because we have already onboarded the atSigns we have been using for e2e tests. 
    * But for these tests we need to write a little bit of code that will take the .atKeys files generated during onboarding step earlier, and output the at_demo_data.dart file
  * Run the e2e past pack against the atSigns
* Delete and verify steps
  * deletes the atSigns
  * tries to make openssl connection to the atServer addresses it looked up during "Create and verify" steps, and fails
  * tries to look up the addresses again via root.atsign.wtf:64 and gets null responses

**Comment by kumarnarendra701** [comment]
@athandle - To run the onboarding step, I need a cram key of atsign. Can you please help with this?

**Comment by gkc** [comment]
@srieteja knows how to do this I believe, with the onboarding cli tool

**Comment by srieteja** [comment]
@gkc I have already had a discussion with Narendra. He's hitting an internal API endpoint which is not directly returning the CRAM. We do need some input from @athandle reg this.

**Comment by kumarnarendra701** [comment]
@athandle - Any update on this?

**Comment by athandle** [comment]
@kumarnarendra701 here is API doc
https://docs.google.com/document/d/1X9dbqeB5TE4XIlYzNdenGK1iNAseMs-HdllLF8XPBl8/edit#heading=h.fj6vx9bz6awc

**Comment by athandle** [comment]
@kumarnarendra701 this requires OTP and if you are looking for without OTP then I need permission from @gkc @cpswan  to create a secure API for this purpose only.

**Comment by kumarnarendra701** [comment]
@cpswan @gkc - Can you please look into this?

**Comment by gkc** [comment]
@athandle why can't we use a super-api-key for all of this?

**Comment by athandle** [comment]
> @athandle why can't we use a super-api-key for all of this?

thanks @gkc  I think it's a nice idea. Let me help @kumarnarendra701

**Comment by kumarnarendra701** [comment]
@gkc @cpswan - - I completed mentioned below tasks
1. Create and verify steps
2. E2E test steps(Create a config.yaml for the atSigns)
3. Delete and verify steps


Mentioned below are some tasks in which I need some help from you or anyone who is aware of Dart, I never worked on Dart. 

* Onboarding steps
  * Run the [activate_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/bin/activate_cli.dart) program (takes atSign, cram key and root server parameters) for each atSign
* E2E test steps
  * Generate an at_demo_data.dart file
    * this file contains the various keys for the e2e test atSigns, and currently this is held as a github secret because we have already onboarded the atSigns we have been using for e2e tests. 
    * But for these tests we need to write a little bit of code that will take the .atKeys files generated during onboarding step earlier, and output the at_demo_data.dart file

**Comment by cpswan** [comment]
@kumarnarendra701 I've just spoken to @sitaram-kalluri about this, and he will help integrate the provisioning elements with the end-end tests.

Reduced to 5SP for work done in PR56

**Comment by sitaram-kalluri** [comment]
> @gkc @cpswan - - I completed mentioned below tasks
> 
> 1. Create and verify steps
> 2. E2E test steps(Create a config.yaml for the atSigns)
> 3. Delete and verify steps
> 
> Mentioned below are some tasks in which I need some help from you or anyone who is aware of Dart, I never worked on Dart.
> 
> * Onboarding steps
>   
>   * Run the [activate_cli](https://github.com/atsign-foundation/at_libraries/blob/trunk/packages/at_onboarding_cli/bin/activate_cli.dart) program (takes atSign, cram key and root server parameters) for each atSign
> * E2E test steps
>   
>   * Generate an at_demo_data.dart file
>     
>     * this file contains the various keys for the e2e test atSigns, and currently this is held as a github secret because we have already onboarded the atSigns we have been using for e2e tests.
>     * But for these tests we need to write a little bit of code that will take the .atKeys files generated during onboarding step earlier, and output the at_demo_data.dart file

@kumarnarendra701: As discussed, please find the below steps to activate an atSign using the at_onboarding_cli

* Clone [at_libraries](https://github.com/atsign-foundation/at_libraries) and navigate into "packages/at_onboarding_cli"
* Run the following command to activate atSign
  ```dart
   dart bin/activate_cli.dart -a @<atSign> -c <cram_key> -r root.atsign.org
  ```
The .atKeys file saved at : at_libraries/packages/at_onboarding_cli/keys/@<atSign>_key.atKeys.

In case, the environment is staging, set the -r to root.atsign.wtf.

Will keep you updated on generating the at_demo_data.dart file once completed.

**Comment by sitaram-kalluri** [comment]
@kumarnarendra701: The script to generate at_demo_data.dart file is available in the link: [generate_at_demo_data.dart]( https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_dump_atKeys/bin/generate_at_demo_data.dart). Please refer to the dart docs in the file for usage.

**Comment by kumarnarendra701** [comment]
@sitaram-kalluri - Seeing below errors with activate_cli 

https://github.com/atsign-foundation/at_server/actions/runs/4429571520/jobs/7770231303

```
Run dart at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart -a @$ATSIGN_1_NAME -c $CRAM_KEY1 -r  root.atsign.wtf
Error: Couldn't resolve the package 'at_onboarding_cli' in 'package:at_onboarding_cli/src/activate_cli/activate_cli.dart'.
at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart:1:8: Error: Not found: 'package:at_onboarding_cli/src/activate_cli/activate_cli.dart'
import 'package:at_onboarding_cli/src/activate_cli/activate_cli.dart'
       ^
at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart:5:[22](https://github.com/atsign-foundation/at_server/actions/runs/4429571520/jobs/7770231303#step:10:23): Error: Method not found: 'main'.
  await activate_cli.main(args);
                     ^^^^
Error: Process completed with exit code [25](https://github.com/atsign-foundation/at_server/actions/runs/4429571520/jobs/7770231303#step:10:26)4.
```

Can you also share the command for Generate an at_demo_data.dart because in the shared reference URL it's showing dart code?

**Comment by athandle** [comment]
@sitaram-kalluri any update on this?

**Comment by sitaram-kalluri** [comment]
> dart at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart -a @$ATSIGN_1_NAME -c $CRAM_KEY1 -r  root.atsign.wtf

@kumarnarendra701 : Looks like the error is because it is unable to fetch the dependencies. Did you run `dart pub get` command before running `dart at_libraries/packages/at_onboarding_cli/bin/activate_cli.dart` ?

**Comment by sitaram-kalluri** [comment]
> Can you also share the command for Generate an at_demo_data.dart because in the shared reference URL it's showing dart code?

The command to generate the at_demo_data.dart is `dart bin/generate_at_demo_data.dart -d <path_to_atKeys_directory>`.

In the given URL [generate_at_demo_data.data](https://github.com/atsign-foundation/at_tools/blob/trunk/packages/at_dump_atKeys/bin/generate_at_demo_data.dart), the dart docs (from line no. 9 to 33) has the usage which further explains the command and other optional flags that command accepts.

**Comment by kumarnarendra701** [comment]
@sitaram-kalluri - I have added all steps for the e2e test but it's failing on "dart test" with the below errors. Need your help to fix this error.

```
Run dart test --concurrency=[1](https://github.com/atsign-foundation/at_server/actions/runs/4540716199/jobs/8001982633#step:13:1)

❌ loading test/cached_key_test.dart (failed)
  Failed to load "test/cached_key_test.dart":
  test/pkam_utils.dart:11:28: Error: The method 'trim' isn't defined for the class 'Map<String, String>'.
   - 'Map' is from 'dart:core'.
  Try correcting the name to the name of an existing method, or defining a method named 'trim'.
    privateKey = privateKey!.trim();
                             ^^^^
  test/pkam_utils.dart:12:38: Error: The argument type 'Map<String, String>?' can't be assigned to the parameter type 'String'.
   - 'Map' is from 'dart:core'.
    var key = RSAPrivateKey.fromString(privateKey);
                                       ^
  test/pkam_utils.dart:21:16: Error: Undefined name 'cramKeyMap'.
    var secret = cramKeyMap[atsign];
                 ^^^^^^^^^^
  package:test_core/src/runner/vm/platform.dart 255:7   VMPlatform._compileToKernel
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 232:[15](https://github.com/atsign-foundation/at_server/actions/runs/4540716199/jobs/8001982633#step:13:16)  VMPlatform._spawnIsolate
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 76:[19](https://github.com/atsign-foundation/at_server/actions/runs/4540716199/jobs/8001982633#step:13:20)   VMPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart [23](https://github.com/atsign-foundation/at_server/actions/runs/4540716199/jobs/8001982633#step:13:24)2:[27](https://github.com/atsign-foundation/at_server/actions/runs/4540716199/jobs/8001982633#step:13:28)       Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 99:19    new LoadSuite.<fn>.<fn>
```
cc: @gkc @cpswan

**Comment by kumarnarendra701** [comment]
@gkc @cpswan  - Can you please look into this workflow and let me know your feedback? Once you give us go ahead then I'll add the prod endpoint of node API and raise PR.

Workflow - https://github.com/atsign-foundation/at_server/blob/sr_e2e_testing_1135/.github/workflows/e2e_test.yaml

**Comment by gkc** [comment]
Overall looks good to me @kumarnarendra701 thank you ... only thing I think you've missed is the checks I wanted at the end (see my [earlier comment](https://github.com/atsign-foundation/at_server/issues/1135#issuecomment-1441667737)) to verify that the deletions have been successful

With regards to "add the prod endpoint of node API" - can you clarify what that means please?

As an aside, just to be clear, we will be running these lifecycle tests against the staging environment, not against production. We will in the future have "probes" running against production which are doing a similar thing periodically to verify the sanity of our production environment.

**Comment by kumarnarendra701** [comment]
@gkc - Thank you for your review. I have added deletion check steps in the workflow.

Now, I am clear about the environment. Please let me know when we need to add these e2e steps.

https://github.com/atsign-foundation/at_server/blob/sr_e2e_testing_1135/.github/workflows/e2e_test.yaml#L206

**Comment by gkc** [comment]
> @gkc - Thank you for your review. I have added deletion check steps in the workflow.

Yep saw that, just left a comment on the PR


> Now, I am clear about the environment.

👍

> Please let me know when we need to add these e2e steps.

Sorry I don't understand what you mean by 'add' ... add to what? They've been added to the workflow in the PR, so it looks like the PR is nearly ready. Once we merge the PR will we be finished here? Or is there something else that needs to happen?

**Comment by kumarnarendra701** [comment]
@gkc - I mean it is currently configured for push events and there is a different workflow file i.e e2e_test.yaml. So my question was do we need to configure this on a different event like PR, different branch, and want to integrate this entire workflow in at_server.yaml workflow file.

**Comment by gkc** [comment]
Ah I see. (1) I think we should merge it into the at_server.yaml file. (2) With regards to events etc, the main options I can think of are:
- run against current staging services
  - i.e. **before** we do the push_staging_secondary_image or push_staging_observable_secondary_image jobs
  - not dependent on any other jobs so it can start in parallel with unit_tests, functional_tests and end2end_test_prep 
  - the tests would thus run for every PR and merge to trunk, and we could if we wish add them to the list of mandatory checks in the branch protection rules
- run *after* we push the new staging image
  - i.e. needs [ push_staging_secondary_image, push_staging_observable_secondary_image ]
  - the tests would thus run for every merge to trunk
  - but not for every PR push, and thus they would not be made part of the list of mandatory checks

What do you think? My preference is the first option

**Comment by kumarnarendra701** [comment]
@gkc - Agree with the first option.

  - i.e. **before** we do the push_staging_secondary_image or push_staging_observable_secondary_image jobs - **Added end2end_test_staging step with push_staging_secondary_image**
  - not dependent on any other jobs so it can start in parallel with unit_tests, functional_tests and end2end_test_prep  - **It will trigger required jobs.**
  - the tests would thus run for every PR and merge to trunk, and we could if we wish add them to the list of mandatory checks in the branch protection rules - **Currently, the push_staging_secondary_image step is configured for Push on the trunk branch.**
  
Please review the below PR and share your feedback.

https://github.com/atsign-foundation/at_server/pull/1306
