### ISSUE TITLE
Generating new atsigns runs on older secondary server version

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1136]
### Describe the bug

The new atSign's generated on the mobile apps runs on the older version of the secondary server.

Below are the log snippets of the two atSign "55inline" and "gothiceggplant87"

55inline:

```
11acd986-35e6-531b-90b8-2c627e6510fa_secondary.1.ww9e0wah29ly@swarm0002-18.us-central1-c.c.secondaries.internal    | INFO|2023-01-11 06:49:12.944389|AtSecondaryServer|Secondary server started on version : 3.0.15 on root server : root.atsign.org 
11acd986-35e6-531b-90b8-2c627e6510fa_secondary.1.ww9e0wah29ly@swarm0002-18.us-central1-c.c.secondaries.internal    | 
11acd986-35e6-531b-90b8-2c627e6510fa_secondary.1.ww9e0wah29ly@swarm0002-18.us-central1-c.c.secondaries.internal    | INFO|2023-01-11 06:49:12.944518|AtSecondaryServer|Secure Socket open for @55inline ! 
```
gothiceggplant87:

```
|Secondary server started on version : 3.0.15 on root server : root.atsign.org 
1327f51b-10c9-54d9-b2cb-a8ec99cec4fe_secondary.1.6g6ag8ifpb35@swarm0002-18.us-central1-c.c.secondaries.internal    | 
1327f51b-10c9-54d9-b2cb-a8ec99cec4fe_secondary.1.6g6ag8ifpb35@swarm0002-18.us-central1-c.c.secondaries.internal    | INFO|2023-01-10 09:24:20.919863|AtSecondaryServer|Secure Socket open for @gothiceggplant87 ! 
1327f51b-10c9-54d9-b2cb-a8ec99cec4fe_secondary.1.6g6ag8ifpb35@swarm0002-18.us-central1-c.c.secondaries.internal    | 
1327f51b-10c9-54d9-b2cb-a8ec99cec4fe_secondary.1.6g6ag8ifpb35@swarm0002-18.us-central1-c.c.secondaries.internal    | SEVERE|2023-01-10 09:24:42.986653|DefaultVerbExecutor|exception in processing command :from:@gothiceggplant87:clientConfig:{"version":"3.0.49"}: Exception: invalid @sign: Cannot contain !*'`();:&=+$,/?#[]{} characters 
```

Since the secondary version is pointing to an older version (v3.0.15), the new variant of "FROM" which contains the client config fails with an exception which prevents the creation of new connections. 

### Steps to reproduce

Generate a free atSign on the wavi app:

* Select an atSign and enter my email address
* Enter the OTP received via email and enter it
* Select the new atSign (not the existing atSign's)

### Expected behavior

The below exception should be resolved and the app should be able to connect to the secondary server.

```
SEVERE|2023-01-10 09:24:42.986653|DefaultVerbExecutor|exception in processing command :from:@gothiceggplant87:clientConfig:{"version":"3.0.49"}: Exception: invalid @sign: Cannot contain !*'`();:&=+$,/?#[]{} characters 
```

### Were you using an atApplication when the bug was found?

Wavi

**Comment by sitaram-kalluri** [comment]
This issue might be the potential cause for the following issue: https://github.com/atsign-foundation/apps/issues/759

**Comment by cpswan** [comment]
My initial trouble shooting on this identified that the registry `reg.swarm0001.atsign.zone` was running with an expired certificate:

```
Certificate chain
 0 s:CN = reg.swarm0001.atsign.zone
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Oct 12 07:35:33 2022 GMT; NotAfter: Jan 10 07:35:32 2023 GMT
```

A new cert had been generated on 12 Dec, but the registry hadn't been restarted since then.

Action #1137 and https://github.com/atsign-foundation/seccheck/issues/24 opened so that this shouldn't happen again, along with https://github.com/atsign-company/secondaries-scripts/issues/62 to make secondary spinup more robust.

**Comment by cpswan** [comment]
Moving this to PR54 as the linked actions aren't done yet, but treat as a tracker, so assigning 0 SP.

**Comment by gkc** [comment]
Linked actions are complete, closing this ticket as complete
