### ISSUE TITLE
Ensure that registry is restarted following a certificate renewal

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1137]
### Is your feature request related to a problem? Please describe.

#1136 was opened because new secondaries were coming up with a very old version, which was happening due to an expired cert on the registry

### Describe the solution you'd like

When a new cert is created for the registry the registry should be restarted.

### Describe alternatives you've considered

We could periodically restart the registry.

**Comment by cpswan** [comment]
@kumarnarendra701 can you please make this your top priority for this sprint

**Comment by kumarnarendra701** [comment]
@cpswan -  I got one reg renewal script but with the wrong command. So modified the script and tested it and it check for a restart file and re-deploy the reg service. So we need to setup this as corn only. Please let me know if you need any other enhancements.

```
#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/config
export  CACHEDIR LETSDIR REGDIR DOMAIN
if [[ -f /gluster/@/etc/letsencrypt/live/$DOMAIN/restart ]]
then
docker service rm reg_registry
docker stack deploy --compose-file "$REGDIR"docker-compose.yml  --with-registry-auth --resolve-image changed reg
rm /gluster/@/etc/letsencrypt/live/$DOMAIN/restart
fi
```

**Comment by cpswan** [comment]
@kumarnarendra701 rather than removing the service and recreating it can't we just scale to 0 then back to 1?

**Comment by kumarnarendra701** [comment]
@cpswan - Yes we can do that and modified script and configured cronjob in stage environment.

```
#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
source $SCRIPT_DIR/config
export  CACHEDIR LETSDIR REGDIR DOMAIN
if [[ -f /gluster/@/etc/letsencrypt/live/$DOMAIN/restart ]]
then
    # scale down to zero 
    docker service scale reg_registry=0
    # scale down to zero
    docker service scale reg_registry=1
    # remove restart file
    rm /gluster/@/etc/letsencrypt/live/$DOMAIN/restart
fi
```

Cronjob - 
00 23 * * * /gluster/reg.staging0001/scripts/renewal.sh >/dev/null 2>&1

**Comment by cpswan** [comment]
Thanks @kumarnarendra701 please do the same in prod. Can you also please PR the scripts into the secondaries_scripts repo.

**Comment by kumarnarendra701** [comment]
@cpswan - Please review below PR.
https://github.com/atsign-company/secondaries-scripts/pull/65
