### ISSUE TITLE
Upgrade Ubuntu on swarm managers

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1144]
### Is your feature request related to a problem? Please describe.

Managers are showing:

```
*** System restart required ***
```

And there are numerous package updates e.g. on swarm0004-01:

```
51 updates can be applied immediately.
To see these additional updates run: apt list --upgradable
```

### Describe the solution you'd like

Run:

```
apt update && apt upgrade -y
```

Check for any errors or warnings

```
reboot
```

Ensure that leader position and any manager constrained containers are reassigned in the swarm before moving to next manager. (It may be best to do one manager per swarm rather than all of the managers in a swarm).

- [x] staging0001
- [x] canary
- [x] swarm0004
- [x] swarm0003
- [x] swarm0002
- [x] swarm0001

**Comment by kumarnarendra701** [comment]
@cpswan - All swarm managers upgrade completed.

**Comment by cpswan** [comment]
Thanks @kumarnarendra701
