### ISSUE TITLE
UpdateVerbHandler may be setting expiresAt incorrectly on the auto-notification it generates

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1175]
### Describe the bug

See this code snippet from the `_notify` method of `UpdateVerbHandler`
```dart
    DateTime? expiresAt;
    if (atMetaData.ttl != null) {
      expiresAt = DateTime.now().add(Duration(seconds: atMetaData.ttl!));
    }
```

(1) notification expiry time is not currently expected to be coupled with the underlying data entry's ttl
(2) even if we were coupling the expiry time, `ttl` is in _milliseconds_ and we are treating it here as _seconds_

### Expected behavior

* `expiresAt` on the auto-notification should be as per at_protocol specification
* If the specification is unclear then we should clarify the specification and make the implementation match it.

**Comment by xavierchanth** [comment]
Ensure it is mentioned in dartdoc, and there is a test.

**Comment by srieteja** [comment]
The solution is part of the PullRequest that has been attached. Carrying over this issue into PR57 to complete the PR review and merge.
