### ISSUE TITLE
When a new certificate is available the secondary should just drop connections and get on with it..

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#1209]
### Is your feature request related to a problem? Please describe.

Currently we are way too polite and it causes issues.. 

```
So @visual61 is the receiving half of the @kryz_9850 stream of SNMP stats. It stopped allowing new connections as it wanted to up date its certificate.

 It got stuck as there is no break in the data.. So as a test I shutdown the SNMP notifications and receivers and then after a while for the TCP connections to drop the new cert popped into place.

But we should think about killing all connections and just do the cert renewal, as that would be less distruptive that disallowing connections until " connections drop" as in this case they would never drop.

I will raise a ticket.. The good news, I did not bounce the secondary and the new cert is in place that secondary has been up for 4 weeks and handled about 620k notifications and about 4M data points.

```

### Describe the solution you'd like

Just drop the connection and renew the certificate at some stage. Blocking incoming connections just caused a bigger outage than getting on with the cert renewal.

### Describe alternatives you've considered

This is Dart bug/feature that needs raising with the team.. We should be able to change the security context on the fly so new connections use the new security context. Perhaps there is a way but I have not found it ?

### Additional context

Perhaps force clients to disconnect occasionally instead ?

**Comment by gkc** [comment]
This is already fixed, it's in canary since a few days ago, not yet promoted to prod. See https://github.com/atsign-foundation/at_server/pull/1131 and https://github.com/atsign-foundation/at_server/issues/960

**Comment by gkc** [comment]
> This is Dart bug/feature that needs raising with the team.. We should be able to change the security context on the fly so new connections use the new security context. Perhaps there is a way but I have not found it ?

There is no way to change it currently. The context can be supplied at bind time only. Yes this would be a useful enhancement to the Dart core.
