### ISSUE TITLE
keys with capital letters doesn't show up in scan response

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#1216]
### Describe the bug

A key that contains a capital letter doesn't show up in the scan verb response.

### Steps to reproduce

1. First create a key that has a capital letter in it. 
example: @alice🛠@update:public:capS@alice🛠 check

2. Then do a scan

@alice🛠@update:public:capS@alice🛠 check
data:4
@alice🛠@scan
data:["@alice🛠:signing_privatekey@alice🛠","public:publickey@alice🛠","public:signing_publickey@alice🛠"]

### Expected behavior

Scan verb result should display the key 

### Screenshots

![Screenshot from 2023-02-21 18-21-58](https://user-images.githubusercontent.com/43639593/220353190-596ac892-9b9a-4f4a-9833-1a1ca346e2d8.png)

**Comment by gkc** [comment]
Thanks for discovering this @purnimavenkatasubbu !!!  I've done a little testing locally and have found a clue ... I observe that if the server is restarted then the key is returned from scan as expected

**Comment by gkc** [comment]
Problem is with maintenance of the _metaDataCache map in HiveKeystore. The map entries are created with the key as supplied, which may have uppercase in it.

**Comment by gkc** [comment]
I'm going to fix this now, as I'm already in the server code
