### ISSUE TITLE
SyncProgressive's buffer size and InboundMessageListener's buffer size out of step

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1227]
### Describe the bug

- SyncProgressive's buffer size and InboundMessageListener's buffer size out of step
- InboundMessageListener has a hard-coded value
- SyncProgressive's buffer size is set by config
- When InboundMessageListener's buffer size is larger (currently it is nearly twice as large) then it is possible for a client to send an update with a data size greater than sync's buffer limit, which subsequently cannot be sync'd back to a client

### Steps to reproduce

* Start a server with a buffer size of 10 (10 bytes)
* Do an update
* sync will never return anything

### Expected behavior

InboundMessageListener buffer capacity should be set to 10KB less than the sync buffer size

**Comment by gkc** [comment]
Alternative better solution: always return at least 1 record in the sync response regardless of buffer size

**Comment by srieteja** [comment]
Case 1:
Was able to reproduce the issue - Started a server with 500k bytes of InboundMessageListener buffer size and 250k bytes of Sync buffer size. Started 2 clients for this server, then updated a key with a value of size 450k bytes through client 1. Now this key was not synced to the LocalSecondary of client2 (although the key shows in the scans on remote_secondary).

Case 2:
Started a server with 500k bytes of InboundMessageListener buffer size and 489760 bytes of Sync buffer size
- (500k bytes - 10kb = 489760 bytes)

In this case the large key which could not be synced to client2's local secondary in case1 was synced.

**Comment by srieteja** [comment]
> Alternative better solution: always return at least 1 record in the sync response regardless of buffer size

Now that we have a preliminary solution, will try to implement this.

**Comment by gkc** [comment]
@murali-shris Remember we're not using labels for story points any more; I've entered 3 in the SP field. (See also the ["PR Tasks"](https://github.com/orgs/atsign-foundation/projects/8/views/140) view on the project board.

**Comment by murali-shris** [comment]
> @murali-shris Remember we're not using labels for story points any more; I've entered 3 in the SP field. (See also the ["PR Tasks"](https://github.com/orgs/atsign-foundation/projects/8/views/140) view on the project board.

noted Gary. thank you

**Comment by gkc** [comment]
@srieteja I'd like to get the fix released soon; the fix looked nearly ready to go on Friday - can you create a PR please so I can review it and hopefully then get it out to prod tomorrow?

**Comment by srieteja** [comment]
The PR is ready @gkc. https://github.com/atsign-foundation/at_server/pull/1246

**Comment by gkc** [comment]
Great! Thank you
