### ISSUE TITLE
at_functional_tests should be using pkam authentication instead of cram authentication

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#1229]
### Describe the bug

Currently,  at_functional_tests in server runs with cram authentication, It is supposed to be using pkam authentication.

### Steps to reproduce

1. Run the functional test in pkam_verb_test.dart

### Expected behavior

Tests should pass with pkam authentication

### Screenshots

https://github.com/atsign-foundation/at_server/actions/runs/4301369009

**Comment by sitaram-kalluri** [comment]
Following are the error logs that are observed when trying to load the PKAM keys in the at_functional_test in at_server:

```
error while setting keys for @ashish🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @eve🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @barbara🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @colin🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @emoji🦄🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @jagan🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @egcreditbureau🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @purnima🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
error while setting keys for @kevin🛠 exception: Exception: Failed connecting to root server url vip.ve.atsign.zone on port 64
```

**Comment by cpswan** [comment]
@sitaram-kalluri can you please also detail the debugging steps you mentioned earlier?

Also are we following the same steps that we take with the VE for at_client_sdk tests?

**Comment by sitaram-kalluri** [comment]
> @sitaram-kalluri can you please also detail the debugging steps you mentioned earlier?
> 
> Also are we following the same steps that we take with the VE for at_client_sdk tests?

1. Set a tmate in the at_server workflow.
2. SSH into the Github actions VM and SSH into the docker container.
3. Manually run the pkamLoad process via the supervisorctl command line.
4. I have observed the above error message in the pkam.log.

However, I am able to connect to the root server via the OpenSSL from the docker container in the GitHub actions VM.

With respect to loading PKAM keys, the steps are similar to what we have in at_client_SDK.

**Comment by purnimavenkatasubbu** [comment]
Changed in the following [PR](https://github.com/atsign-foundation/at_server/pull/1214) is merged to the trunk.
