### ISSUE TITLE
Some tests marked "temporarily skipped"

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1238]
### Describe the bug

[Two tests in commit_log_test.dart](https://github.com/atsign-foundation/at_server/blob/trunk/packages/at_persistence_secondary_server/test/commit_log_test.dart#L104-L122) are marked as "temporarily skipped". The tests currently fail if the 'skip' is removed.

### Expected behavior

The tests should be unskipped and changes made to AtCommitLog to make them pass.

**Comment by sitaram-kalluri** [comment]
The skip tag is removed and the test are modified to assert the current behaviour. The changes are merged to trunk.
