### ISSUE TITLE
Move stats tests from e2e tests to functional tests 

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1276]
### Is your feature request related to a problem? Please describe.

Various tests in `tests/at_end2end_test/test/stats_verb_test.dart` fail pretty frequently - most likely due to race conditions.

### Describe the solution you'd like

As there are no tests there which depend on there being more than one server, we should move these tests to tests/at_functional_test instead. This may remove the race condition, if it is related to the fact that the e2e test atServers are reused across test runs but even if it does not, it reduces the probability of a check run failing because of this since, in each checks run, we run the e2e tests three times, but the functional tests only once

**Comment by gkc** [comment]
Marking as P1 important because tests failing due to race conditions causes wasted time investigating the failure, re-running checks etc

**Comment by purnimavenkatasubbu** [comment]
Changes are in the [PR](https://github.com/atsign-foundation/at_server/pull/1297). But there is a [bug](https://github.com/atsign-foundation/at_server/issues/1298) due to which the tests will fail.

**Comment by purnimavenkatasubbu** [comment]
As per the comment in this [ticket](https://github.com/atsign-foundation/at_server/issues/1298#issuecomment-1501548636). Currently, the sent count gets incremented only if we notify a different atsign. Tests need to send a notification to a different and we cannot move these tests to functional_tests.

**Comment by purnimavenkatasubbu** [comment]
Moved only the tests that don't require a second atsign to functional tests. PR is ready for review.
[PR](https://github.com/atsign-foundation/at_server/pull/1297)

**Comment by purnimavenkatasubbu** [comment]
Closing the ticket as [PR](https://github.com/atsign-foundation/at_server/pull/1297) is merged to trunk
