### ISSUE TITLE
When updating metadata, it should be patched (merged), not overwritten

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1295]
### Describe the bug

In #1287 we have a situation where
- an sshnpd program using newest version of dart client SDK was creating keys with a value in the new ivNonce metadata
- an older version of the sshnpd program was also creating (updating) those keys and, since it was unaware of new metadata, it did not send it in the batch update request to the server
- the server did not merge data appropriately

### Steps to reproduce

See #1287 

### Expected behavior

The Update and UpdateMeta verb handlers should
- retrieve the current AtMetadata, if any
- set values on it if and only if they have been sent by the client in the update command (i.e. they are present in the verb params)
- and that modified AtMetadata object is what should be saved back to the keystore

There is code in the persistence layer which has some intent along these lines; however - it is not possible to do this entirely in the persistence layer, as the persistence layer cannot know the difference between a field which was explicitly set to null by a client and sent as such in the update command, versus a field which was not sent by the client and thus has an implicit value of null

**Comment by gkc** [comment]
I will work on this in PR59 if nobody else picks it up, but I would be very grateful if someone else could pick it up as soon as possible

**Comment by sitaram-kalluri** [comment]
The changes are released into Canary c3.0.30

**Comment by sitaram-kalluri** [comment]
The changes are released into production in p3.0.30. Closing the issue.
