### ISSUE TITLE
Sent count in stats:11 doesn't get updated for a self-notification

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#1298]
### Describe the bug

When a self-notification is sent, the sent count isn't updated in the stats:11, Whereas the received count gets updated.

### Steps to reproduce

1. Send a self notification
@ alice🛠@ notify:update:@ alice🛠:phone@ alice🛠:90920190129
data:a7f77997-a055-40c9-92d7-1203f4ade3be
@ alice🛠@ notify:status:a7f77997-a055-40c9-92d7-1203f4ade3be
data:delivered

### Expected behavior

The sent count should be updated in the stats:11 response

### Screenshots

Before sending self-notification

![Screenshot from 2023-04-04 17-45-30](https://user-images.githubusercontent.com/43639593/229788607-c1b32e6f-7c8b-4a14-81c5-da2266d6bf86.png)

After sending a self-notification, stats:11 response

![Screenshot from 2023-04-04 17-45-44](https://user-images.githubusercontent.com/43639593/229788805-a3641ee0-5659-4c77-b891-34702510ef4b.png)

**Comment by sitaram-kalluri** [comment]
@purnimavenkatasubbu: By design, this is working as expected. 

From the code snippet below, the self-notifications are marked as "received" and hence the received count is updated and not the sent count.

```
NotificationType _getNotificationType(String toAtSign, String currentAtSign) {
    if (toAtSign == currentAtSign) {
      return NotificationType.received;
    }
    return NotificationType.sent;
  }
```

**Comment by purnimavenkatasubbu** [comment]
Closing this ticket, as this is the expected behavior
