### ISSUE TITLE
Reduce atServer memory requirements

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1303]
### Is your feature request related to a problem? Please describe.

50MB seems insufficent for many atSigns ... recently we've had to bump memory for `@snowthe18raw` and `@intenseaquarius` as they were constantly being killed by docker swarm manager very shortly after startup

### Describe the solution you'd like

atServer should have a predictable cap on amount of memory used during startup and in steady state

Let's start by profiling atServer memory usage during startup and in steady state to see what we can reduce.

**Comment by gkc** [comment]
Another one today, `@ foolishgemini1`

**Comment by athandle** [comment]
today incident @snowthe18raw  today swarm-0002

**Comment by sitaram-kalluri** [comment]
Work done in PR: 60:
* Analysed the server logs and did not find any clue on the Out-Of-Memory error.
* Pulled the storage of the atSign's 'snowth18raw' and 'foolishgemini1' and ran locally with memory profiling. On server start-up, the memory consumed is nearly 21MB.
* Scanned through keys and commit entries and cache maps in the persistent layer are not causing the issue.

Yet to investigate why is server taking more than the memory required.

**Comment by sitaram-kalluri** [comment]
Work done in PR-63:
* Run the secondary server prod image and observe the memory usage with large commit log key-store. 
* Updated the results into the following google sheet: https://docs.google.com/spreadsheets/d/14kGBE0ldXlukjFh0vsELc7bxHgZx7wHXc8jzaWMMhk0/edit?usp=sharing
