### ISSUE TITLE
Enhance DeleteVerbHandler so it prevents deletion of important data

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1325]
### Describe the bug

It is currently possible for an authenticate client to delete data such as the server's signing keypair

### Steps to reproduce
See https://github.com/atsign-foundation/operations/issues/14

### Expected behavior

DeleteVerbHandler should prevent deletion of data which is important to correct functioning. In addition to the signing keypair mentioned above, we should consider whether other data should be deletable (e.g. `public:publickey@<atSign>`)

**Comment by srieteja** [comment]
Could not work on this yet. Carrying it forward to the next sprint

**Comment by gkc** [comment]
Is this being actively worked on?

**Comment by srieteja** [comment]
Not yet Gary, I been working on onboarding_cli bugs and at_login for the past couple of sprints and could not take this up. I will take this up this sprint.

**Comment by srieteja** [comment]
Implementation to fix this issue is in the linked pr. Carrying forward to PR68 for completing the review and PR merge.
