### ISSUE TITLE
Improve null safety checks and exception handling around the pol auth flow

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1327]
### Describe the bug

See incident report https://github.com/atsign-foundation/operations/issues/14

Incident took much longer than it should have to diagnose because of a lack of parameter value checks and more localized exception handling on both ends of the pol auth flow (OutboundClient, and PolVerbHandler) which in turn led to there being a severe lack of useful log messages to help diagnose the issue

### Expected behavior

Check variables for correctness of their values. (Non-null, in appropriate format, etc)
Do more localized exception handling so that, given an exception messages, it is easier to narrow down where the problem is occurring

**Comment by srieteja** [comment]
Carrying it forward to address pr comments and get the pr merged
