### ISSUE TITLE
APKAM - Enroll request verb implementation

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1355]
### Is your feature request related to a problem? Please describe.

Implement changes related to enroll verb request as per APKAM design
https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md

### Describe the solution you'd like

* introduce enroll verb syntax
* Enroll verb handler implementation in server

**Comment by murali-shris** [comment]
@gkc 
section - "Initial bootstrap - onboard FirstApp" in [the APKAM ](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) spec
If the first app/client is cram authenticated and sends a enroll request with apkamPublicKey..
we will create a keystore entry with key <approvalID>.new.enrollments.__manage@atSign.
if the app disconnects and attempts a PKAM, how do we get the APKAM public key for this pkam request 
Should we search the keystore for pattern ".new.enrollments." , match the deviceName/appName and get the APKAM public key from value json  or should we maintain a list of approvalIds on the server?

**Comment by gkc** [comment]
> @gkc section - "Initial bootstrap - onboard FirstApp" in [the APKAM ](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) spec
> If the first app/client is cram authenticated and sends a enroll request with apkamPublicKey.. we will create a keystore
> entry with key .new.enrollments.__manage@atSign. if the app disconnects and attempts a PKAM, how do we get the
> APKAM public key for this pkam request? Should we search the keystore for pattern ".new.enrollments." and then match
> the deviceName/appName and get the APKAM public key from value object or should we maintain a list of approvalIds
> on the server?

Given that the ID of the enrollment record will include a unique part e.g. `<id>.new.enrollments.__manage@atSign`. Two choices come to mine: (1) server returns, and client keeps track of, the generated ID of the new enrollment request. (2) search by deviceName / appName as you say

I think (1) is clearer and cleaner. What do you think?

**Comment by murali-shris** [comment]
> > @gkc section - "Initial bootstrap - onboard FirstApp" in [the APKAM ](https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md) spec
> > If the first app/client is cram authenticated and sends a enroll request with apkamPublicKey.. we will create a keystore
> > entry with key .new.enrollments.__manage@atSign. if the app disconnects and attempts a PKAM, how do we get the
> > APKAM public key for this pkam request? Should we search the keystore for pattern ".new.enrollments." and then match
> > the deviceName/appName and get the APKAM public key from value object or should we maintain a list of approvalIds
> > on the server?
> 
> Given that the ID of the enrollment record will include a unique part e.g. `<id>.new.enrollments.__manage@atSign`. Two choices come to mine: (1) server returns, and client keeps track of, the generated ID of the new enrollment request. (2) search by deviceName / appName as you say
> 
> I think (1) is clearer and cleaner. What do you think?

yes. in (1), in the pkam request, client will pass the approvalID?

**Comment by gkc** [comment]
Hmm.

Maybe we should think about all subsequent PKAM requests; in each case there will have to be some way for the server to find the PKAM public key. And so the client will have to retain and provide something uniquely identifying about their PKAM, each time - the enrollment ID would work for that, as the server will generate it and can guarantee uniqueness as well as performant lookup when a PKAM request is received. We need also to consider where that identifier is held by the client. The local atKeys file (for command-line / headless clients) or keychain (for apps) seems like the appropriate place to put it, since the identifier is directly tied to the PKAM keypair (because a PKAM request will need both the keypair and this identifier.)

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_server/tree/apkam_enroll
Changes pushed so far
* enroll verb handler implementation 
  - new enroll request of client that is cram authenticated
  - subsequent enroll request of new client 
  - send notification via monitor (implementation to be confirmed with Gary since client needs to be active to receive the notification)
* pkam verb handler changes
  - enroll id in syntax
  - changes to perform pkam auth with apkam public key
* Manual testing done

**Comment by murali-shris** [comment]
Manual testing steps
First client:
* cram auth done
* send enroll request
```
@alice@enroll:request:appName:wavi:deviceName:pixel:namespaces:wavi,rw:apkamPublicKey:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg1THrbmEpXMDXUtci4GBNaARF2ghWYz6tC5PcO8oyjqioDwlp7lVZcufhgZGD2Dd5j124vyx8t0qlTP/LObK8WvgvLOY5NqUCOgYBv0VufVzOr6xrsNKVEKC9GzMkMbUfFwBVYHeeIg3IKeGTyxB+qHQIAa2gLZCBKX8EsLTGliQmkv2J96umaFTsS/juwxw9nSVpsMIwCcg6hA3njVbjR1p5o9mZ3lVw57GOHzkdyGXXBgKzNvBRXBSDOkNCulxoixrydqWD8sLc8AERQoWCUwSWITTS0YE/jFL8fH2zWupjJ510JmoIf2L2MJsiFFUCtRIRTWSIHs1/cXZiIEvhQIDAQAB
data:{"approvalId":"8f037db4-ccd5-4da8-8256-2adb9ec3c7cf","status":"success"}
```
* disconnect client
* attempt pkam with enrollId
```
@from:@alice
data:_c038dc37-fa77-4ad0-b917-3759b35f2fe0@alice:995a8adb-04fb-4e35-b8a8-1ae34a96b2ba
@pkam:enrollApprovalId:8f037db4-ccd5-4da8-8256-2adb9ec3c7cf:cT0zHOfylN0V2YVxpFnXAaxJLHDgn1IXEVS2/0tnktgDKSlVa0gjYrNEFVTKMQXorESRIL7NWdoDunzcxdIja156XCTWJrIVWPw+ZZ2Ku9d1tA02OgvqZ/N1n0W4GD8oPV+SRu2dNL7jQ3WRq/uvn/nS+C9EE2wZf50kEALyez4QbZ6qAJ+ZZZgz/OTAH78iEUYHKBMaRz0CBHKrtVbqpAt2ig6Fuet4+dfSjBc/G1iJCXxM2876YEjnza1urcLl0JgoeZHuFycbKLy2Hnl6g40wOJUmInyRzCnffdiXKJ6UDZxJ3yFvw+UzK+MSOpiBtjPKiAYGw4BCKl41GrV8/w==
data:success
```
* start monitor
@ alice @ monitor

Second client
* Send enroll request
```
@enroll:request:appName:wavi:deviceName:pixel:namespaces:buzz,rw:apkamPublicKey:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg1THrbmEpXMDXUtci4GBNaARF2ghWYz6tC5PcO8oyjqioDwlp7lVZcufhgZGD2Dd5j124vyx8t0qlTP/LObK8WvgvLOY5NqUCOgYBv0VufVzOr6xrsNKVEKC9GzMkMbUfFwBVYHeeIg3IKeGTyxB+qHQIAa2gLZCBKX8EsLTGliQmkv2J96umaFTsS/juwxw9nSVpsMIwCcg6hA3njVbjR1p5o9mZ3lVw57GOHzkdyGXXBgKzNvBRXBSDOkNCulxoixrydqWD8sLc8AERQoWCUwSWITTS0YE/jFL8fH2zWupjJ510JmoIf2L2MJsiFFUCtRIRTWSIHs1/cXZiIEvhQIDAQAB
data:{"approvalId":"996ebb77-c6a4-40b2-a731-0aaeb2f52e81","status":"pending"}
```
First client:
* Notification received on monitor //TODO encrypt notification
```
notification: {"id":"89339f16-12a1-4060-92c1-587c152f9e22","from":"@alice","to":"@alice","key":"8f037db4-ccd5-4da8-8256-2adb9ec3c7cf.new.enrollments.__manage@alice","value":null,"operation":null,"epochMillis":1685448468569,"messageType":"MessageType.key","isEncrypted":false,"metadata":null}
```

**Comment by murali-shris** [comment]
@gkc 
 I have the below clarifications related to sending notification when a enroll request is sent by a new client
 * Temporarily I am sending notifications from enroll_verb_handler to monitor connection of online clients with __manage access.
 * how do we send notification to the apps/client with __manage namespace access if they are offline?

**Comment by gkc** [comment]
Notifications should be stored; then they can be delivered when the approvals app comes online. Expectation is that the user will know that they need to open their approvals app

**Comment by murali-shris** [comment]
Work done in PR 63
* Completed enroll verb handler implementation with notifications
* adhoc implementation of totp for demo purpose
* introduced self notification type for enroll feature since monitor only delivers received notifications
* namepace access control changes in scan verb handler
* demo'ed the functionality implemented so far
Pending:
* notifications to be received when client is offline and then comes online

**Comment by murali-shris** [comment]
@gkc @cconstab Question on TOTP implementation
https://docs.google.com/document/d/18Ryt8dcYemn7CkBz-MbNWATpuPFCKgg0V7tuDxQZICg/edit?disco=AAAAz9Ng7IE

**Comment by murali-shris** [comment]
Implementation done with functional tests. 
https://github.com/atsign-foundation/at_server/tree/apkam_enroll
TOTP pending changes will be addressed in a new task
