### ISSUE TITLE
APKAM - info verb to include APKAM namespace access details

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1356]
### Is your feature request related to a problem? Please describe.

info verb to include APKAM namespace access details
https://github.com/atsign-foundation/at_protocol/blob/trunk/decisions/2023-01-pkam-per-app-and-device.md

### Describe the solution you'd like

Modify info verb implementation to include APKAM namespace details

**Comment by purnimavenkatasubbu** [comment]
Changes are available in the branch [issue_1356](https://github.com/atsign-foundation/at_server/tree/issue_1356)

**Comment by murali-shris** [comment]
Code review and functional tests pending

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_server/pull/1439
PR  merged to trunk
