### ISSUE TITLE
Redis : Adding an atsign to blocklist throws internal server error while using redis keystore

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#138]
**Describe the bug**
Adding an atsign to the blocklist using the config verb throws the following error

error:AT0010-Internal server error : NoSuchMethodError: Class 'RedisPersistenceManager' has no instance getter 'box'.
Receiver: Instance of 'RedisPersistenceManager'
Tried calling: box

**To Reproduce**
1. First I Started the secondary server of both alice and bob 
2. Then From the bob's atsign added alice to the blocklist and viceversa using the config verb as follows
In bob's terminal
config:block:add:@ alice
In alice's terminal
config:block:add:@ bob

**Expected behavior**
Atsign which I added using the config:block verb should e added to my blocklist

Server Logs

![Screenshot from 2021-05-26 18-19-48](https://user-images.githubusercontent.com/43639593/119662446-09244d80-be4f-11eb-94e8-d7815fb440a6.png)
![Screenshot from 2021-05-26 18-20-00](https://user-images.githubusercontent.com/43639593/119662452-0aee1100-be4f-11eb-8f53-d06527dd49dd.png)

**Comment by bob** [comment]
Hi Alice!

**Comment by purnimavenkatasubbu** [comment]
Tested the scenario after the bug fix. Issue is resolved.

![Screenshot from 2021-05-31 18-47-16](https://user-images.githubusercontent.com/43639593/120199371-ca243c80-c240-11eb-9258-2d391991b99f.png)
