### ISSUE TITLE
APKAM - OTP design discussion and changes in implementation

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1423]
### Is your feature request related to a problem? Please describe.
![totp](https://github.com/atsign-foundation/at_server/assets/18326522/62c5ca24-e931-41eb-8b79-7e82eee79cee)

Image source : Diagram source : https://www.protectimus.com/blog/totp-algorithm-explained/

Step 1: TOTP is setup between an already enrolled app(e.g wavi) and secondary server.
Q: shared secret for totp. Should this be stored as self key which gets synced to server?

Step 2: Apkam enrollment steps (sequence diagram below)

Q: when a person has access to apps like wavi/buzz etc., looking up TOTP and entering in another app is straightforward.

In IoT scenario how do we accomplish this? E.g what if enrolled client and to be enrolled client both are remote devices.

![totp drawio (1)](https://github.com/atsign-foundation/at_server/assets/18326522/b7b3ad05-7c9c-4bfb-a1ac-8e0c17e886fd)

### Describe the solution you'd like

Options suggested by @gkc 
I'm not sure we need a totp necessarily. I'd thought of the sequence something like this …
- Approver app (Wavi in this example) is asked for a PIN. It issues a verb command to the server like `otp:generate:ttl:60` to generate a PIN which will be valid for 60 seconds
- The server
creates a random 4-character alphanumeric pin
stores it as a private key along with its expiry time
And for housekeeping, schedules a future to run at the expiry time to delete the PIN again
Also for housekeeping, server upon startup should also scan through any existing PINs and delete any which have expired
returns the PIN to the Approver app
- Approver app displays the PIN in some way to the user
- User enters PIN into Enrolling app (Buzz in this example)
- Buzz sends enroll request, which includes the PIN, to the server
- Server scans PINs in the keystore and checks that there is a valid (unexpired) match. If so then it accepts the enrollment request.
- Enrollment request (including the PIN used) is notified to the Approver app.
- The Approver app checks that the PIN is the one it displayed. If it is, then
    if it is interactive it displays the approve / reject dialog to the user
     if it is not interactive then it can automatically approve because the PIN matches

- If we decide we need a TOTP then as usual we will need two copies - in this case one for the client (a self key which can be synced) and one for the server (encrypted with the server’s public signing key)

**Comment by murali-shris** [comment]
Q:
Currently we have a 6 digit otp generated on the server with an expiry of 90 seconds. Already enrolled apps can display/request an OTP using totp:get command to secondary server. Is this implementation fine?
From Colin:
Switching to alphanumeric is better and limiting the number of tries

Making that number of characters configurable is also probably a good idea while we have the code open

From Ashish:
Remove o and 0

To avoid confusion

**Comment by murali-shris** [comment]
implementation not started in PR66. carrying over.

**Comment by murali-shris** [comment]
> implementation not started in PR66. carrying over.

Will be implemented in PR68

**Comment by sitaram-kalluri** [comment]
Spent 3 SP in PR-68. The changes are available in [change_otp_impl](https://github.com/atsign-foundation/at_server/compare/apkam_spec_changes...change_otp_impl?expand=1)

**Comment by sitaram-kalluri** [comment]
Spent 5 SP in PR-69:

Identified failures in scan_verb_test.dart. Fixed the issue and also refactored the scan_verb_handler.dart in the following PR: https://github.com/atsign-foundation/at_server/pull/1529.

Renamed the TOTP to OTP in at_commons, at_server_spec and at_secondary_server and published at_commons-3.0.54 and at_server_spec - 3.0.14. The changes in at_secondary_server are merged to trunk.

**Comment by sitaram-kalluri** [comment]
The changes are released into canary in v3.0.35a. Closing this issue.
