### ISSUE TITLE
functional tests for reference keys

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1438]
### Is your feature request related to a problem? Please describe.

* reference keys e.g
phone@ alice 123
phonref@ alice atsign://phone@ alice

do not have functionals tests

### Describe the solution you'd like

* write a functional test in update/lookup verb handler to verify storing and retrieval of public keys and shared reference keys

**Comment by purnimavenkatasubbu** [comment]
Raised the following [PR](https://github.com/atsign-foundation/at_server/pull/1449)

**Comment by purnimavenkatasubbu** [comment]
Closing the ticket as [PR](https://github.com/atsign-foundation/at_server/pull/1449) got merged to trunk
