### ISSUE TITLE
APKAM - access changes for monitor verb

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1444]
### Is your feature request related to a problem? Please describe.

When user is authenticated via APKAM, allow only the keys with authorized namespaces to flow through the verbs.

- Monitor verb: Allow only the notification where keys with authorized namespaces to stream through the monitor connection.
- Notify verb: Allow only the notification where keys with authorized namespaces to be processed through the notify verb.

### Describe the solution you'd like

- Refer to the implementation https://github.com/atsign-foundation/at_server/pull/1443
- In monitor verb handler, add a check to verify if the namespaces of a key are authorized with enrollmentId used to authenticate.
- Similar to monitor verb, add a check in notify verb check for authorization of namespace.

**Comment by murali-shris** [comment]
Not started in PR66.carrying over

**Comment by sitaram-kalluri** [comment]
In PR-67, spent 5 SP, implemented the changes.
The changes are available in [enroll_access_changes](https://github.com/atsign-foundation/at_server/tree/enroll_access_changes).

**Comment by sitaram-kalluri** [comment]
No progress made in PR-68. Waiting on the PR: https://github.com/atsign-foundation/at_server/pull/1496 to merge.
Pending work is pull the latest changes of APKAM and resolve merge conflicts

**Comment by sitaram-kalluri** [comment]
@gkc : Regarding the APKAM changes in "notify" verb, when recipient lacks access to a specific namespace, should a notification be sent or return error message? Additionally, if the recipient has subscribed to a namespace but lacks the authorization to write, should the cached key be stored or ignored?

**Comment by gkc** [comment]
I'd like you to think this through and come to a conclusion, and then we can discuss your conclusion

**Comment by sitaram-kalluri** [comment]
Following is the PR related the APKAM changes in monitor verb: https://github.com/atsign-foundation/at_server/pull/1525

Attaching the sequence diagram of APKAM functionality with respect to monitor verb:

```mermaid
sequenceDiagram
    participant w as Wavi-Approving App
    participant s as Server
    participant b as Buzz-Enrolling App

    note right of w: First App Enrollment
    w->>s: CRAM Authenticated
    s->>w: Auth Successful
    note right of w: __manage, * and wavi are added to enroll namespace list
    w->>s: Start monitor:selfNotifications
    s->>w: Stream all notifications via the monitor
    
    note left of b: Second app requesting enrollment
    b->>s: Request for enrollment - {buzz:rw}
    note left of b: Enrollment in pending state. Monitor will not receive notifications untill approved
    s->>w: Notify the enrollment request for approve/deny
    w->>s: Enrollment approved 
    s->>b: Inform enrollment status - approved
    b->>s: Start monitor:selfNotifications
    s->>b: Stream only buzz namespace notifications on monitor

    w->>s: Enrollment denied/revoked
    b->>s: start Monitor
    s->>b: Auth failed. Cannot execute monitor verb.
```

**Comment by sitaram-kalluri** [comment]
> I'd like you to think this through and come to a conclusion, and then we can discuss your conclusion

My thoughts are, it is necessary to validate whether the intended recipient has the proper authorization to receive the notification.

The rationale for this assertion is outlined as follows:

1. Currently, the recipient lacks the ability to control the receiving of notifications. Consequently, the sender retains the ability to send notifications, potentially causing the recipient to become overly engaged with processing these notifications. This leads to recipient's server being starved from other jobs.

2. In instances where a user's interest lies solely in specific notifications – for instance, those marked "wavi" – and no interest exists in receiving notifications with "buzz" namespace, currently, the server still retains "buzz" notifications in its keystore. This results in allocation of memory to unnecessary notifications such as "buzz".

Enabling APKAM access at the recipient's end allows recipient to unsubscribe from notifications of certain namespace. This also serves to prevent the buildup of uncecessary notifications, thereby conserving memory.

**Comment by sitaram-kalluri** [comment]
Spent 5 SP in PR-69.
APKAM changes for monitor verb is completed and the changes are available in https://github.com/atsign-foundation/at_server/pull/1525. Adding additional SP due to unplanned work around removing the atConnection and regex as instance variables from monitor_verb_handler.dart.

**Comment by gkc** [comment]
> > I'd like you to think this through and come to a conclusion, and then we can discuss your conclusion
> 
> My thoughts are, it is necessary to validate whether the intended recipient has the proper authorization to receive the notification.

I agree - the recipient **client** needs the proper authorization, but I don't understand your rationale as written (see comments below)

> 
> The rationale for this assertion is outlined as follows:
> 
> 1. Currently, the recipient lacks the ability to control the receiving of notifications. Consequently, the sender retains the ability to send notifications, potentially causing the recipient to become overly engaged with processing these notifications. This leads to recipient's server being starved from other jobs.

Recipient server behaviour is not the primary relevant point. The most important consideration is: should a client receive a notification in a namespace it does not have access to? The answer to that is clearly no, given the whole intent of APKAM is to limit and control client applications' access to specific namespaces

> 2. In instances where a user's interest lies solely in specific notifications – for instance, those marked "wavi" – and no interest exists in receiving notifications with "buzz" namespace, currently, the server still retains "buzz" notifications in its keystore. This results in allocation of memory to unnecessary notifications such as "buzz".

This is not relevant. Other client apps may be interested in the buzz namespace

> 
> Enabling APKAM access at the recipient's end allows recipient to unsubscribe from notifications of certain namespace.

No the recipient is not unsubscribing. The atServer is filtering notifications it delivers to monitor connections so that the recipient clients only receive notifications in namespaces for which they are authorized

> This also serves to prevent the buildup of uncecessary notifications, thereby conserving memory.

This is not the case.


Your original question was
> @gkc : Regarding the APKAM changes in "notify" verb, when recipient lacks access to a specific namespace, should a notification be sent or return error message? Additionally, if the recipient has subscribed to a namespace but lacks the authorization to write, should the cached key be stored or ignored?

**Comment by sitaram-kalluri** [comment]
In PR-69, completed the changes related to Monitor verb. Re-estimating to 5-SP in PR-70 for notify verb related changes,

**Comment by sitaram-kalluri** [comment]
In terms of namespace authorization during enrollment, the secondary server must not impose limitations on the transmission or reception of notifications. Regardless of the enrollment's namespace authorization, the server should facilitate the sending and receiving of notifications without restriction. The validation of namespace authorization should occur at the client when sending notifications to the server and at the server when sending notifications to the client. The later is managed handled in the "monitor" verb.

The changes are related to monitor verb are merged to trunk, and hence closing the issue.
