### ISSUE TITLE
APKAM - revoke enrollment changes in enroll verb handler

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1451]
### Is your feature request related to a problem? Please describe.

We have approve/deny features on enroll_verb_handler.dart
Add revoke feature to remove enrollment privileges for the APKAM

### Describe the solution you'd like

* add revoke option to enroll verb syntax in at_commons
sample command enroll:revoke:<enrollmentId>
* In enroll_datastore_value.dart add an enum value revoked to EnrollStatus
* If required add revokeEnrollment to EnrollRequestType
* In enrollVerb handler get the enrollment data for the enrollmentId and update the EnrollStatus to revoked.
* Change isAuthorized method in AbstractUpdateVerbHandler to check for revoked status. 
* add/modify functional tests

**Comment by sitaram-kalluri** [comment]
Work done in PR: 65: Completed the changes and raised a PR.
Pending work is PR review and merge the changes to trunk branch
