### ISSUE TITLE
APKAM Testing - observe sync behaviour

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1452]
### Is your feature request related to a problem? Please describe.

* Test apkam changes with at_client and ensure there are no issues in sync related to new keys added for APKAM feature

### Describe the solution you'd like

* Document issue if any

**Comment by purnimavenkatasubbu** [comment]
Test scenarios:

1) Atsign @ bob - enrolled to buzz app and buzz namespace
@ bob  creates a key in wavi app with wavi namespace

Issues found

1) Wavi app keys are created and synced to the cloud 
2) Connected to another client which has enrolled to buzz namespace. Tried to sync:from with namespace
wavi keys are synced 
3) Scan verb displays each key twice.

Attaching the logs of the test scenarios
[test_logs_apkam_buzz_namespace.txt](https://github.com/atsign-foundation/at_server/files/12036425/test_logs_apkam_buzz_namespace.txt)

**Comment by purnimavenkatasubbu** [comment]
Analysis is done. Raised separate ticket for the bugs. [Ticket](https://github.com/atsign-foundation/at_server/issues/1472)
