### ISSUE TITLE
Refactor the commit log keystore to improve time and space complexity

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1469]
- On the server start-up the commit log key-store causes the initial memory spike which cause the server to crash due to out of memory exception.
- The initial sync and the delta causes the memory spike.

Refactoring the commit log key-store as follows to address the time and space complexity issue:

Refactor "_getCommitIdMap" and "_updateCacheLog" method to sort the entries in ascending order by commit-ids.
To maintain the entries in sorted order, if a key exists in the map, remove the entry and add the key again to ensure the key is added to end of the map.
Refactor "getEntries" method
The "getEntries" at the moment loads all the keys from the commit log keystore into the memory. However, the server only returns 25 keys or untill the buffer is full (which ever happens first). So loading all the keys each time to consumes a lot of memory and time as well.
Refactored the method to load only specific number of keys. Added an optional field "limit" to configure how many keys to load into the memory for a batch. The "limit" is defaulted to 25.

**Comment by purnimavenkatasubbu** [comment]
Test scenario

Left tab shows a client sync 10,000 commits where its secondary server running on trunk branch. 
Right tab shows a client sync 10,000 commits where its secondary server running on commit_log_memory_changes branch

https://github.com/atsign-foundation/at_server/assets/43639593/42ef2af9-77cc-4e2a-b222-4e958746c306
