### ISSUE TITLE
Issues in sync with APKAM changes

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#1472]
### Describe the bug

- [ ] Wavi app keys are created and synced to the cloud
- [ ] Connected to another client which has enrolled to buzz namespace and Tried to run sync, by using the command sync:from. All the keys with wavi namespace are also synced
- [x] Scan verb displays each key twice -- This issue is not reproducible with the latest changes

### Steps to reproduce

Attaching the test steps in the ticket

[test_logs_apkam_buzz_namespace.txt](https://github.com/atsign-foundation/at_server/files/12146639/test_logs_apkam_buzz_namespace.txt)

### Expected behavior

Only buzz keys should be synced

**Comment by gkc** [comment]
Setting priority to P1

**Comment by purnimavenkatasubbu** [comment]
Issue-3 - The (scan verb displays each key twice) is no longer reproducible with the latest trunk branch of the server.

"public:custom_hobbies.wavi@ alice🛠","public:email.wavi@ alice🛠","public:field_order_of_self.wavi@ alice🛠","public:firstname.wavi@ alice🛠","public:lastname.wavi@ alice🛠","public:phone.wavi@ alice🛠","public:pkaminstalled@ alice🛠","public:privateaccount.wavi@ alice🛠","public:pronoun.wavi@ alice🛠","public:publickey@ alice🛠","public:signing_publickey@ alice🛠"]

**Comment by murali-shris** [comment]
PR review pending

**Comment by sitaram-kalluri** [comment]
The changes are completed and PR is ready to merge. Currently, the functional tests are failing in at_server. Waiting for the functional test to pass.
