### ISSUE TITLE
APKAM - update enrollment access

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1499]
### Is your feature request related to a problem? Please describe.

* Currently enrolment access is created when the enrolment request is placed on the server. Access will remain in place until the enrolment is revoked. There is no way to update the access after placing enrolment request

### Describe the solution you'd like

* Update enroll:request command to modify access privileges
E.g r --> rw, rw --> r, r/rw --> no access.
* modify enroll_verb_handler to update the privileges in the keystore for the enrolment id.

**Comment by sitaram-kalluri** [comment]
Sequence diagram representing the enrollment update.

```mermaid
sequenceDiagram
    Client(Requesting App)->>+Server: 1. enroll:update:{"enrollmentId":"123","namespaces",{"wavi":"rw","buzz":"r"}}
    Server->>+Keystore: 2. Create a supplementary enrollment key <enrollmentId>.supplimentary.enrollments.__manage@<currentAtSign> <updated enrollment request>
    Client(Approving App)->>+Server: 3. enroll:approve:{"enrollmentId":"123"}
    Server->>+Keystore: 4. Update the existing enrollment key with the supplementary enrollment data and set supplimentary key status to approved
    Server->>+Client(Requesting App): 4.1 Enrollment approved
    Client(Approving App)->>+Server: 5. enroll:deny:{"enrollmentId":"123"}
    Server->>+Keystore: 6. Set supplementary key status to denied. Do nothing on the existing enrollment key
    Server->>+Client(Requesting App): 6.1 Enrollment denied
```
When an enrollment request is updated, it results in the replacement of the pre-existing enrollment data. For instance, if the current enrollment provides access as "wavi":"rw", in order to acquire access to both "wavi" and "buzz", the client must submit both namespaces as follows: {"wavi":"rw", "buzz":"rw"}.

**Comment by sitaram-kalluri** [comment]
Spent 4SP in PR-68 for the approach. Will take up implementation in PR-69. Adding 5SP for implementation in PR-69

**Comment by srieteja** [comment]
Partial implementation has been done. Will take this up again in PR70 to complete the implementation.

**Comment by srieteja** [comment]
Carrying this forward to PR71 for testing.

**Comment by srieteja** [comment]
Implementation and testing has been completed. Carrying this forward for PR review.

**Comment by sitaram-kalluri** [comment]
Below are queries on enrollment update:

- Consider the following scenarios:
     - a. If a user initially has access to the "wavi" namespace and later updates to include both "wavi" and "buzz" namespaces, we do not currently support syncing keys related to "buzz" that are behind the latest commit ID received by the client. Is this behaviour fine? it should be explicitly mentioned in our documentation for clarity.
     - b. If a user initially has access to both the "wavi" and "buzz" namespaces and then later updates to only include the "wavi" namespace, we must enforce restrictions on the "buzz" namespace keys. This change needs to be implemented on the client side to ensure proper namespace management.

The above items needs a discussion in the arch call.

**Comment by gkc** [comment]
> Below are queries on enrollment update:
> 
> * Consider the following scenarios:
>   
>   * a. If a user initially has access to the "wavi" namespace and later updates to include both "wavi" and "buzz" namespaces, we do not currently support syncing keys related to "buzz" that are behind the latest commit ID received by the client. Is this behaviour fine? it should be explicitly mentioned in our documentation for clarity.
>   * b. If a user initially has access to both the "wavi" and "buzz" namespaces and then later updates to only include the "wavi" namespace, we must enforce restrictions on the "buzz" namespace keys. This change needs to be implemented on the client side to ensure proper namespace management.
> 
> The above items needs a discussion in the arch call.

My two cents
(1) We should not allow enrollment 'updates'. If an app wants to change its permissions then it should do a new enrollment.
(2) When an app completes an enrollment, it should remove all atServer-managed data from local data store and sync from scratch.

**Comment by srieteja** [comment]
This PR requires a discussion to decide if this feature is still relevant. For that reason will be carrying this forward to PR74.

**Comment by sitaram-kalluri** [comment]
Based on the above mentioned complexities, it was decided NOT to have the enrollment update. Hence closing this issue.

**Comment by gkc** [comment]
@sitaram-kalluri Please add a link here to the enhancement ticket in at_client_sdk which addresses the changes we decided we would make (as per https://github.com/atsign-foundation/at_server/issues/1499#issuecomment-1764060445 above)
