### ISSUE TITLE
configKey is not well formed key

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1570]
### Describe the bug

With the changes in the PR: https://github.com/atsign-foundation/at_server/pull/1569, three functional tests are failing with below exception

```
  From verb response data:_60f74087-c688-4c1b-805f-bcb5fe10f12f@alice🛠:eb1042bf-89a1-48c9-8750-130f025c66d7
  
  pkam verb response data:success
  
  FormatException: Unexpected character (at character 1)
  error:null:Exception: configkey is not well-formed key
```

When adding an atSign to the block list, the list of atSigns are stored aganist the key "configKey" which is not a well formed key. "configKey" does not adhere to the key format specified for AtKeys.

Referring to the changes APKAM changes, and the process of retrieving the highest commitId within the enrolled namespaces, we achieve this by extracting the namespace from the key using AtKey.fromString(key).namespace. However, when the key "configKey" is encountered, this action triggers the mentioned error within AtKey.fromString because "configKey" does not conform to the valid AtKey format.

**Comment by gkc** [comment]
See also https://github.com/atsign-foundation/at_server/issues/1204
