### ISSUE TITLE
Prevent the reuse of OTP

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#1578]
### Is your feature request related to a problem? Please describe.

When generating an OTP through the "get:otp" method for the purpose of approving or denying an enrollment, prevent the reuse of the same OTP for a different enrollment request, even if the OTP is still valid.

**Comment by cpswan** [comment]
This is a pattern I had to implement for the Storj token service.

When I generate a nonce (similar to an OTP) a timestamp is stored alongside it. When it comes to validation the timestamp is checked to ensure that it hasn't expired. In the case of the token service that's just 60s, but for other use cases we just need a bigger number.

**Comment by srieteja** [comment]
This change has been made as part of https://github.com/atsign-foundation/at_server/pull/1609

**Comment by srieteja** [comment]
Closing this ticket as completed
