### ISSUE TITLE
Automation of bugs being assigned to the right project

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#158]
Without the issue being tagged into the project bugs do not appear in the project board.

- [x] Automate bugs tag to tag the issue to the right project probably based on the repo it is in.
- [x] Done on at_server 
- [x] Will roll out across all repos

**Comment by cpswan** [comment]
Started out trying [assign-one-project-github-action](https://github.com/srggrs/assign-one-project-github-action) but hit already reported ["No project was found" error](https://github.com/srggrs/assign-one-project-github-action/issues/65)

Then tried [project-bot](https://github.com/philschatz/project-bot), but it failed to install with a 500 error, and it seems that the [Bot is broken](https://github.com/philschatz/project-bot/issues/102) was reported a few weeks ago. The developer seems to have downed tools somewhat in recent weeks.

**Comment by cpswan** [comment]
Gave project-bot another try, and at least it installed this time (now that GitHub seems to have recovered). But it doesn't seem to be working.

**Comment by cpswan** [comment]
PRs raised in at_tools, at_widgets and at_client_sdk
