### ISSUE TITLE
release null safety

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#159]

**Comment by murali-shris** [comment]
- [x] changes version to 1.1.0 in pubspec, modify changelog
- [x] run unit tests
- [x] run functional test
- [x] test with apps
- [x] merge to trunk
- [x] Publish null safety package to pubspec
- [x] Release to prod

**Comment by murali-shris** [comment]
@purnimavenkatasubbu Please run functional tests and app sanity with null_safety branch once again on monday(7-June)

**Comment by sitaram-kalluri** [comment]
The remaining tasks are moved to the next sprint because of the blocker in testing in a staging environment. Hence closing this story
