### ISSUE TITLE
Analysis: Compose a white paper outlining the requirements for the server and client sides of the Dart Hive DB replacement.

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_server#1700]
The memory usage of Dart Hive DB is O(N), where N is the number of keys in a box, according to our previous investigation, which showed that the database is not memory efficient.

This task's goal is to do a thorough investigation and offer recommendations for a potential Dart Hive DB replacement.

**Comment by ksanty** [comment]
New ticket here - https://github.com/atsign-foundation/at_server/issues/1733
