### ISSUE TITLE
Flaky unit test

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#1799]
### Describe the bug

Over the past couple of days I've seen frequent failures of this test:

```
❌ test/enroll_verb_test.dart: A group of tests related to enrollment request expiry A test to verify expired enrollment cannot be approved (failed)
  INFO|2024-02-14 09:49:51.858219|HiveBase|commit_log_5a1fff547b9dafdc95c1938a41e8951bded8a595db3a50ddf0183a67a8a05f6a initialized successfully 
  
  INFO|2024-02-14 09:49:51.859931|HiveBase|5a1fff547b9dafdc95c1938a41e8951bded8a595db3a50ddf0183a67a8a05f6a initialized successfully 
  
  Expected: <true>
    Actual: <false>
  
  package:matcher                   expect
  test/enroll_verb_test.dart 540:7  main.<fn>.<fn>
SEVERE|2024-02-14 09:49:51.908130|NotificationUtil|exception while storing notification : LateInitializationError: Field '_boxName@833204826' has not been initialized. 
```

### Steps to reproduce

1. First I create a PR
2. Then automated tests run
3. And then far too frequently the unit tests are failing

### Expected behavior

Unit tests are a reliable indicator of whether new code is good.

**Comment by purnimavenkatasubbu** [comment]
This issue has been fixed as part of the [commit](https://github.com/atsign-foundation/at_server/commit/1b3f346e011edf6b0fff205be7ef3121b49cbd84) 

[PR](https://github.com/atsign-foundation/at_server/pull/1831)
