### ISSUE TITLE
Move Buzz (and Wasp?) environment(s) from Digital Ocean to GCP

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#188]
**Describe the solution you'd like**
- [x] Turn down Digital Ocean droplets and replace with clusters on GCP.
- [x] VM setup with base software setup
- [x] NFS setup and VPC peering
- [x] Docker Swarm setup with Ansible
- [x] Socat Daemon
- [x] Shepherd Service
- [x] Directory Structure
- [x] Directory Structure
- [x] API Script setup
- [x] LB Setup
- [x] Data Migration
- [x] API connectivity form application

This includes the Ludo k8s Cluster which holds - Sept 30th drop dead date

- [x] root.atsign.wtf
- [x] directory (wavi) .wtf
- [x]  Other stuff ? Needs checking

**Describe alternatives you've considered**
We could continue using Digital Ocean or expand usage of AWS (to use credits)

**Additional context**
I know that @kumarnarendra701 has already done some work on this (Terraform templates etc.) - so putting it here as part of making all work visible.

**Comment by kumarnarendra701** [comment]
@cpswan @athandle - Below are tasks completed to migrate the Buzz Docker Swarm cluster to GCP.
1. VM setup with base software setup. - Completed
2. NFS setup and VPC peering - Completed
3. Docker Swarm setup with Ansible. - Completed.

**Comment by kumarnarendra701** [comment]
@cpswan @athandle 
1. Create Socat Daemon for Port Forwarding
2. Create Shepherd Service
3. Directory Structure.

**Comment by kumarnarendra701** [comment]
@cpswan @athandle -  Below tasks completed.
 - ENCPASS setup
 - API Script setup
 - Directory setup

**Comment by kumarnarendra701** [comment]
Buzz Swarm migrated on GCP.
Mentioned below are the remaining tasks.
- root.atsign.wtf
- directory (wavi) .wtf
- Node API(Registar, infra)
- Other stuff ? Needs checking

**Comment by kumarnarendra701** [comment]
@cpswan - K8 initial migration from DO to GCP completed for below components.
- Node API
- root/root.wtf
- directory
Note - we need downtime to move data for root and switching DNS pointing.

**Comment by cpswan** [comment]
Thanks @kumarnarendra701 

I think @cconstab suggested a downtime slot this weekend. So will we be done once that piece is completed?

**Comment by cconstab** [comment]
The important other stuff on ludo is the api to the clusters.. The TF stuff is all legacy

**Comment by kumarnarendra701** [comment]
@cconstab - Sorry, I didn't get this. can you please explain?

**Comment by kumarnarendra701** [comment]
@cpswan - Below components migrated to GCP.
1. K8 cluster.
2. root, directory, and Node API.
3. CI/CD pointing completed.

**Comment by cpswan** [comment]
@kumarnarendra701 is there anything left to migrate, or can this be closed?

**Comment by cpswan** [comment]
@kumarnarendra701 has confirmed "All components migrated to GCP, now we can close this ticket."
