### ISSUE TITLE
Investigate utility of Portainer CE to help us manage our Docker Swarms

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#189]
**Describe the solution you'd like**
See if [Portainer CE](https://www.portainer.io/products) might be useful for cluster management.

**Additional context**
Mentioned in a highlighted piece from [Docker Community Forums](https://forums.docker.com/t/saas-based-on-docker-1-container-per-client/111156) 'SAAS based on Docker, 1 container per client'

**Comment by cconstab** [comment]
Just a note we tried portainer but it was pretty shaky with the scale we have of containers.. Very often it would fail.. Hence we all went back to cli..
But worth trying again for sure

**Comment by cpswan** [comment]
No need to go over old ground. It's rare for these things to suddenly get better.
