### ISSUE TITLE
Use ZeroSSL API for secondary certificate creation instead of Certbot

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#190]
**Is your feature request related to a problem? Please describe.**
Creation of certificates with Certbot takes ~1m and we can only create one at a time

**Describe the solution you'd like**
Replace Certbot with our Python script that uses the ZeroSSL API. We can then create certificates in parallel, and each cert only takes ~20s

**Describe alternatives you've considered**
We could potentially use DNS validation for Certbot rather than the HTTP callback in use at present.

**Additional context**
[get_certs.py](https://github.com/atsign-foundation/at_virtual_environment/blob/trunk/automation/get_certs.py)

**Comment by cpswan** [comment]
@athandle can you please get an update from @kumarnarendra701 on where he is with this ahead of the Monday sprint planning.

**Comment by athandle** [comment]
sure @cpswan , he deployed changes to Buzz today. He is facing some challenge

**Comment by kumarnarendra701** [comment]
Below tasks completed for parallel SSL/Stack generation - 
1. SSL generation via ZeroSSL API.
2. Tested on Wasp env.
3. Implement secret management(encpass) to store DO and ZeroSSL keys.
4. Create a readme document for secret management.

Partially complete 
Implemented on Buzz but getting below errors, so reverting back to old script and shared logs to the dev team to understand the issue.

Logs - 

INFO|2021-07-09 18:24:47.964836|AtSecondaryServer|Secure Socket open for @shallowwarabeuta ! 

FINER|2021-07-09 18:24:47.964882|AtSecondaryServer|serverSocket _listen : SecureServerSocket 

Unhandled exception:
FileSystemException: Failed to initialize file system entity watcher (OS Error: Too many open files, errno = 24)
SEVERE|2021-07-09 18:24:48.241437|AtSecondaryServer|SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = 0.0.0.0, port = 2787 

SEVERE|2021-07-09 18:24:48.537791|AtSecondaryServer|SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = 0.0.0.0, port = 2787 

SEVERE|2021-07-09 18:24:53.117861|AtSecondaryServer|HandshakeException: Connection terminated during handshake 

SEVERE|2021-07-09 18:24:53.138394|AtSecondaryServer|SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 2787 

SEVERE|2021-07-09 18:25:04.352246|AtSecondaryServer|SocketException: OS Error: Connection reset by peer, errno = 104, address = 0.0.0.0, port = 2787 

SEVERE|2021-07-09 18:25:06.078548|AtSecondaryServer|HandshakeException: Connection terminated during handshake 

SEVERE|2021-07-09 18:25:06.097298|AtSecondaryServer|SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = 0.0.0.0, port = 2787

**Comment by athandle** [comment]
@kalluriramkumar @murali-shris @cconstab please help @kumarnarendra701

**Comment by kumarnarendra701** [comment]
Fixed this issue and implemented the new version of SSL generation on Buzz.

**Comment by cpswan** [comment]
@kumarnarendra701 has this been stable for long enough for us to plan the rollout to Hornet?

**Comment by narendraqa** [comment]
@cpswan - I have already rollout to Buzz and informed Sita to perform one round of testing once I ll get the go-ahead then roll out to the hornet.

@kalluriramkumar - please confirm.

**Comment by athandle** [comment]
@ksanty we can close this ticket as https://github.com/atsign-foundation/at_server/issues/232 is open and we can work over there
