### ISSUE TITLE
When an enrollment is revoked, any clients connected via that enrollment should be immediately disconnected

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#1927]
### Is your feature request related to a problem? Please describe.

Without this safeguard, a revoked app could remain connected until the network connection is lost or the server is restarted etc

### Describe the solution you'd like

When an enrollment is revoked, any clients connected via that enrollment should be immediately disconnected

**Comment by murali-shris** [comment]
@gkc 
If a client submits enroll:revoke for self with force flag, should we drop the client connection on the server?

**Comment by gkc** [comment]
@murali-shris Yes please. Ideally sending a response first so the client knows the revocation was successful and connection will be closed
