### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by vnaresh66** [atsign-foundation/at_server#2006]
### Is your feature request related to a problem? Please describe.

Testing the load

### Describe the solution you'd like

Testing the load

**Comment by vnaresh66** [comment]
1. I have created a notification script which sends the notification to the secondary server 
2. Created a monitor script witch monitor the notification sent to the secondary server
3. Created a dart script which intern creats multiple monitors.
4. Tested the load using above scripts on my local

**Comment by purnimavenkatasubbu** [comment]
Continuing load testing by using the given 2 scripts

Dart Isolates - Uses dart isolates to run multiple monitors at the same time and writes the data from each isolate into a csv
https://gist.github.com/purnimavenkatasubbu/b6a352efe073402348caf5d7257552db

parallel_notification -  Continously sends given number of notifications to the atsign.
https://gist.github.com/purnimavenkatasubbu/d2c6eab2dfc406cd82e8881cbbe5135c

Metrics

https://docs.google.com/spreadsheets/d/1mIk-5CX5YU_wGt_b942Y7Rhq6VcRfAjBlz9KfyI82Ao/edit?gid=1716606720#gid=1716606720
