### ISSUE TITLE
Upgrade test apps to the latest SDK from pub.dev

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#201]
Scope the following by each app

1. Demo (test) apps upgraded
2. Sample apps upgraded

**Comment by ksanty** [comment]
@Intiserahmed can you provide an update?  The team believes you have worked on?

**Comment by Intiserahmed** [comment]
@ksanty Yeap I have upgrade the test app to the latest SDK.

**Comment by ksanty** [comment]
> @ksanty Yeap I have upgrade the test app to the latest SDK.

@Intiserahmed could you please add [label(s)](https://github.com/atsign-company/labels/labels) to this, so we can track better?  TY

**Comment by murali-shris** [comment]
Once RSDK packages are published, this issue will be taken up
