### ISSUE TITLE
add tests for apkam authorization for sub namespaces

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#2030]
### Is your feature request related to a problem? Please describe.

Is an apkam enrollment has access to a namespace, then it should be able to access sub namespaces
e.g 
if enrollment has access to .buzz, then .contacts.buzz, .notifications.buzz should be allowed

### Describe the solution you'd like

write tests to validate the authorization check for sub namespaces

**Comment by murali-shris** [comment]
@gkc @sitaram-kalluri 
subnamespace authorization currently works because of this behavior

```
update:phone.contacts.buzz@alice 1234
```

In AtKey implementation, phone.contacts is treated as key and buzz as the namespace

in the above scenarion AtKey.fromString('phone.contacts.buzz@ alice').namespace should return buzz or contacts.buzz ?

**Comment by gkc** [comment]
It should continue to return buzz.

**Comment by purnimavenkatasubbu** [comment]
Tests has been added in the following [branch](https://github.com/atsign-foundation/at_server/tree/issue_2030)

**Comment by murali-shris** [comment]
https://github.com/atsign-foundation/at_server/pull/2051
