### ISSUE TITLE
Uptake pubKeyHash changes

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#2121]
### Is your feature request related to a problem? Please describe.

pubKeyCS in metadata currently uses md5 checksum which is outdated.
Refer
https://github.com/atsign-foundation/at_libraries/pull/511

### Describe the solution you'd like

Replace pubKeyCS with pubKeyHash using sha512 hash.
Changes are done in at_commons - https://github.com/atsign-foundation/at_libraries/pull/511/files
pubKeyHash should be included in sync from client to server and vice versa.

**Comment by sitaram-kalluri** [comment]
The changes in at_persistence_secondary_server are completed and changes are available in [2121-uptake-public-key-hash-at-persistence_secondary-server](https://github.com/atsign-foundation/at_server/tree/2121-uptake-public-key-hash-at-persistence_secondary-server)

Pending work is code review and publish the package.

**Comment by sitaram-kalluri** [comment]
The changes in at_persistence_secondary_server are released in v3.0.66.

In at_secondary_server, the at_persistence_secondary_server changes are consumed and is released into prod.

There is an open PR for changes in at_secondary_server : https://github.com/atsign-foundation/at_server/pull/2160

**Comment by sitaram-kalluri** [comment]
The changes are released into Canary in c3.1.1. Marking the issue as closed.
