### ISSUE TITLE
Functional tests failing (in stable and beta)

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#2132]
### Describe the bug

```log
❌ test/create_update_key_test.dart: A group of tests to assert on metadata of a key A test to assert of default fields in metadata are populated on creation of a key (failed)
  Expected: <true>
    Actual: <false>
  
  package:matcher                        expect
  test/create_update_key_test.dart 51:7  main.<fn>.<fn>
```

### Steps to reproduce

1. First I add some changes to a PR
2. Then I push the changes
3. And then CI runs tests

### Expected behavior

Tests pass

**Comment by sitaram-kalluri** [comment]
The functional tests are passing now. 

```dart
var keyCreationDateTime = DateTime.now().toUtc();
expect(DateTime.parse(atData['metaData']['createdAt']).millisecondsSinceEpoch > keyCreationDateTime.millisecondsSinceEpoch, true);
```

The failure could be because of the timing issue between the key creation date time and date time in the metadata. Will work on fixing the issue to prevent intermittent failures.

**Comment by murali-shris** [comment]
> The functional tests are passing now.
> 
> ```dart
> var keyCreationDateTime = DateTime.now().toUtc();
> expect(DateTime.parse(atData['metaData']['createdAt']).millisecondsSinceEpoch > keyCreationDateTime.millisecondsSinceEpoch, true);
> ```
> 
> The failure could be because of the timing issue between the key creation date time and date time in the metadata. Will work on fixing the issue to prevent intermittent failures.

try replacing the check with
expect(DateTime.parse(atData['metaData']['createdAt']).millisecondsSinceEpoch >  DateTime.now().toUtc().millisecondsSinceEpoch);

**Comment by murali-shris** [comment]
> > The functional tests are passing now.
> > ```dart
> > var keyCreationDateTime = DateTime.now().toUtc();
> > expect(DateTime.parse(atData['metaData']['createdAt']).millisecondsSinceEpoch > keyCreationDateTime.millisecondsSinceEpoch, true);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The failure could be because of the timing issue between the key creation date time and date time in the metadata. Will work on fixing the issue to prevent intermittent failures.
> 
> try replacing the check with expect(DateTime.parse(atData['metaData']['createdAt']).millisecondsSinceEpoch > DateTime.now().toUtc());

sorry.this check is incorrect. newest time will have greater value of millisecondsSinceEpoch.
