### ISSUE TITLE
Bump at_root_server (and at_persistence_root_server) dependencies

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#2133]
### Is your feature request related to a problem? Please describe.

Dependabot continues to fail to raise PRs for pub deps.

### Describe the solution you'd like

args to be bumped to 2.6.0
at_commons to 5.0.1

Should we take this opportunity to bump dev dependencies like lints (still at ^1.0.1 in at_persistence_root_server)? Also increment patch version for each pubspec? 👀 @gkc

**Comment by gkc** [comment]
> Should we take this opportunity to bump dev dependencies like lints (still at ^1.0.1 in at_persistence_root_server)? Also increment patch version for each pubspec?

👍

**Comment by sitaram-kalluri** [comment]
Updated the dependencies to the latest version and the changes are merged to trunk branch. Marking the issue as closed.
