### ISSUE TITLE
Process documentation - Jagan

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#215]

**Comment by cpswan** [comment]
@VJag can you please add some details so that I know what you need from me for this?

**Comment by VJag** [comment]
The idea behind this task is to document is to cover the following:

 1. Process of @ app release 
     * Document should be able to answer the following questions.
       - Where will Purnima verify a bug on an app (branch, test flight, or after release?)
       - After verification what status does she move it to
      - When will the filer close a bug
      - Where does the product owner verify the features and gives a green signal to publish
      
 2. Process for app developer report a bug/submit a feature request and track the release vehicle
     Ex: @ space signal app needs below changes to the protocol. We should define a process that the app developer follows.
          - notifying caching of a public key
          - scan cached public keys
          - notify delete of a cached public key
          - Some sort of pagination on scan
 
 3. Process for taking contributions from an external contributor

**Comment by cpswan** [comment]
@VJag I think these should be changes to CONTRIBUTING.md so I'd suggest that you get a first pass into a PR and then we can use the PR comments thread to iterate on it.
