### ISSUE TITLE
Unable to send a notification using the syntax in error message

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#221]
**Describe the bug**
Unable to send a notification using the syntax in error message

**To Reproduce**
1. Connect to secondary
2. authenticate pkam
3. Use the notify verb as per errror

**Expected behavior**
should send notification but errors..

**Screenshots**
```
cconstab@cally:~$ openssl s_client -ign_eof -brief 76103630-0f85-5dec-8a91-364bf93b0e8d.hornet.atsign.zone:2499
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = 76103630-0f85-5dec-8a91-364bf93b0e8d.hornet.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@tigerequivalent@notify:list
error:AT0003-Invalid syntax : invalid command
@CONNECTION CLOSED BY SERVER
cconstab@cally:~$ openssl s_client -ign_eof -brief 76103630-0f85-5dec-8a91-364bf93b0e8d.hornet.atsign.zone:2499
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = 76103630-0f85-5dec-8a91-364bf93b0e8d.hornet.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@from:tigerequivalent
data:_c62a97ce-658b-4cd2-90df-c032d4c53879@tigerequivalent:06ccf38c-cc48-48dc-b2a9-cd444320044b
@pkam:XoswIKwrNAfP5JON7VdMeGizqjMiIG66Hf/DC+8ZEBknAk8qv4IZn+6906QtvhC9zYCU/w4LE/4ULJRpwTn4wQRZhzN5gwKBeg3zXj5somSL3mIuNaNOUdYkqyPGTGToeByw5OTPC1c1V287wpECLhBrNAzvASTHHnBOO5Lyss8tbNloJo5YN96dPkIJQ1r1VAX2y9ONNeWQUHwxz2hVWVjG24AEMU2bD/cZgM2MMNUpdvLSk3R+EbeclfPNQEmqpXvMwZHUbUJ7qBlb6t+lm8vAf5IYlDZsoc9JTfbgyyNHy9AqgTOiH4Wq+36CjbB1sD9+RBzkpk5bTLKPHMWhTA==
data:success
@tigerequivalent@notify:all:@realisticforeign:hello
error:AT0003-Invalid syntax : Invalid syntax. e.g notify:all:@alice,@bob:hi
@tigerequivalent@CONNECTION CLOSED BY SERVER
cconstab@cally:~$
```

**Comment by sitaram-kalluri** [comment]
Fixed the issue and tested.

Dev testing notes:
------------------------

CurrentAtSign = @sitaram
read R BLOCK
@from:@sitaram
data:_7675037a-8b98-475d-ba3c-b07ec5fbac96@sitaram:e0ec0180-020b-49e3-86d8-2120967a18f4
@cram:4abdfd0d91f7344cbcba2911264646edfe96606978aff3f7b758618908dcefbb6f0d747bee30c411578e200d9513ec7600343ee96a697d6c08d4d81f6af6d14f
data:success
@sitaram@notify:all:@murali:phone@sitaram
data: {"@murali":"b1fd8274-b2bc-4a1b-8a59-d15fad36e297"}
@sitaram@notify:status:b1fd8274-b2bc-4a1b-8a59-d15fad36e297
data:delivered
@sitaram@notify:all:messageType:text:@murali:hi
data: {"@murali":"baddf2f7-a16b-4f1b-9c7d-aaa83749c6f6"}
@sitaram@notify:status:baddf2f7-a16b-4f1b-9c7d-aaa83749c6f6
data:delivered
@sitaram@


CurrentAtSign = @murali
read R BLOCK
@from:@murali
data:_619ec144-a5d5-4b1f-ac7b-f26689df2181@murali:f3f89cb2-2094-4104-9fad-0ece40e0563b
@cram:1cce2f33dc15e3ab0ef10d0f05d454c8200d5dc52f9aadf410c8fd20ecc042fa930b49a76da90a441362bef526a4534c5b841d04424213437e75c88e9f632b9f
data:success
@murali@notify:list
data:[{"id":"fca071dc-50f3-4b89-9179-f386c32695eb","from":"@sitaram","to":"@murali","key":"@murali:phone@sitaram","value":null,"operation":"update","epochMillis":1626345774782},{"id":"a71f6a3b-28a4-41a3-bca3-c24eacfb53cf","from":"@sitaram","to":"@murali","key":"@murali:hi","value":null,"operation":"update","epochMillis":1626345805299}]
@murali@
