### ISSUE TITLE
Document the protocol verbs in the server code base

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#222]
**Is your feature request related to a problem? Please describe.**
Only some of the network protocol verbs are documented clearly in the codebase others have no or in accurate information

**Describe the solution you'd like**
Each verb to have a full description in the codebase on how to use the wire protocol.
All of these 
https://atsign.dev/at_docs_foundation_master/at_server_spec/verbs/Verb-class.html

e.g OK
https://atsign.dev/at_docs_foundation_master/at_server_spec/verbs/Config-class.html
Bad
https://atsign.dev/at_docs_foundation_master/at_server_spec/verbs/Monitor-class.html

**Describe alternatives you've considered**
We could document outside of the code but it will always be a sync problem.. The codebase should be the right place..

**Additional context**

**Comment by purnimavenkatasubbu** [comment]
Added dart docs and raised PR #444

**Comment by purnimavenkatasubbu** [comment]
@cconstab The PR( https://github.com/atsign-foundation/at_server/pull/444) for the above docs has been merged to trunk. Can we close this issue?

**Comment by murali-shris** [comment]
published version 3.0.2 of server spec containing the updated dart docs

**Comment by murali-shris** [comment]
@cconstab I am closing the issue.
