### ISSUE TITLE
Review for missing documentation - at_persistence_secondary_server (API Reference)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#234]
- [ ] Right nav bar under documentation [API Reference ](https://pub.dev/documentation/at_persistence_secondary_server/latest/)requires content review (samples and examples)
- [ ] Check [documentation link ](https://atsign.dev)pointing to the right locations

Please check library link as well (current, samples and examples)
LIBRARIES

- [ ] [at_persistence_secondary_](https://pub.dev/documentation/at_persistence_secondary_server/latest/at_persistence_secondary_server/at_persistence_secondary_server-library.html)

**Comment by cpswan** [comment]
This should be worked around by https://github.com/atsign-foundation/atsign.dev/pull/217

We need to fix pubspec.yaml and release to pub.dev for a permanent fix (and then we can remove the workaround)

**Comment by ksanty** [comment]
> This should be worked around by [atsign-foundation/atsign.dev#217](https://github.com/atsign-foundation/atsign.dev/pull/217)
> 
> We need to fix pubspec.yaml and release to pub.dev for a permanent fix (and then we can remove the workaround)

Leaving this issue open because the API reference piece still needs to be addressed.

**Comment by ksanty** [comment]
Hi @kalluriramkumar we need to review this very old ticket for accuracy, potentially close it and divert to the new pub.dev publishing issue. Creating new issue cards today.
