### ISSUE TITLE
Missing documentation - at_server_spec (Scores Tab)

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#243]
[Scores tab](https://pub.dev/packages/at_server_spec/score) is missing documentation for the following sections: (8/4 page now showing error - Awaiting analysis to complete)

- [x] follow dart file conventions
- [x] provide documentation (Update - Not required)
- [x] support multiple platforms (Update - Mentioned the reason below in comments)

**Comment by murali-shris** [comment]
@ksanty 
We have fixed dart file convention issue
Since it is server spec
* example is not applicable
* dart.io dependency cannot be removed and hence "cannot support multiple platforms" is reported

**Comment by cpswan** [comment]
The docs should address the fact that this isn't designed to run in a JavaScript environment, so it doesn't support multiple platforms in that respect.

**Comment by murali-shris** [comment]
https://github.com/dart-lang/pub-dev/issues/3995

**Comment by yahu1031** [comment]
## Support multiple platforms Issue ##

https://github.com/dart-lang/pub-dev/issues/3862#issuecomment-667896811 This could give the reason for the 10 points decrement. All most of all our packages/libraries which doesn't support web/native-js will be reduced by 10 points from their score tab. As `dart:io` is not-at-all a web compatible. For web we have `dart:js` and `dart:html` files. If we want to add web support too, then we must go with conditional importing. One of the good references about it can be found [here](https://medium.com/@dvargahali/dart-2-conditional-imports-update-16147a776aa8).

## Documentation ##

We can possibly(if) add documentation for this **at_server_spec** package. I will try working on it.
