### ISSUE TITLE
Libraries and Widgets Documentation Review

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#247]
Multiple repo's (not just at_server)
Individual issues pulled into a separate column on the sprint plan.

- [ ] Readme (new descriptions added, that need review)
- [ ] Changelog
- [ ] Example
- [ ] Installing
- [ ] Versions
- [ ] Score
- [ ] Metadata (updates with readme)
- [ ] Homepage
- [ ] Repository (a few reviews for tree structure)
- [ ] View/Issues report
- [ ] Documentation
- [ ] API reference
- [ ] BSD license
- [ ] Dependencies
- [ ] Thumbsup (everyone be sure to click)

**Comment by CynthiaPeter** [comment]
Hello Kim, 

If you have the time, let me know what needs to be done here.

**Comment by ksanty** [comment]
@CynthiaPeter nothing for this ticket.  This is just an overview of all the sections I reviewed and created tickets for.  Make sense?  It's more of a place marker to check off everything we reviewed across all the libraries and repos.
