### ISSUE TITLE
Certificate update not triggering the restart of the secondary server (possible that this works only on ext4 Filesystems)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#267]

**Comment by cpswan** [comment]
This is related to the issue we've hit with #232 

Once again we're seeing `too many open files`

@kalluriramkumar is going to work with @kumarnarendra701 on getting a filesystem config that fixes this (as we've already done a lot in the code to minimise the number of open files).

**Comment by ksanty** [comment]
@kumarnarendra701 can you please add a [label(s)](https://github.com/atsign-company/labels/labels) to this so we can better track status?  TY

**Comment by kumarnarendra701** [comment]
@cpswan - Performed below debugging on Buzz to fix this issue.
1. Increased Hard/Soft Limit
2. Increased file-max size
3. Increase ulimits from compose file
But still not able to resolve the issue, then finally performed a reboot of the worker node, scheduled a new secondary, and found the restart file working. So it seems that the file open limit is exhausted in the system, but the open file count is less than the specified size.

**Comment by cpswan** [comment]
@kalluriramkumar do you think this is cleared permanently by the changes made, or temporarily by the worker node reboot?

**Comment by athandle** [comment]
@kalluriramkumar any update?

**Comment by sitaram-kalluri** [comment]
@athandle  and @kumarnarendra701 : This issue is fixed and merged to trunk branch. Earlier we have directory file watcher which fails to recognize the file create events when file is created on NFS file system. Now the code is modified to look for presence of file instead of file events. With the latest docker image the issue should be resolved.

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - Is the build deployed on buzz? because I tried to renew various certs but it creates a restart file but secondaries not getting a restart.
![image](https://user-images.githubusercontent.com/29299536/133933453-1d3a781e-5f9d-43a9-8f77-916d1380cae5.png)

**Comment by sitaram-kalluri** [comment]
@kumarnarendra701 : The changes are merged to trunk branch 3 ago and staging servers should be refreshed by now. Also, with the new changes, the job runs only twice a day (once in 12 hours from a random hour generated by the server on start-up). So the moment the restart file is created, the server would not immediately restart.

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - It seems the restart file is not there in the cert directory, I have triegged a few more renewals to see the secondaries status.

**Comment by sitaram-kalluri** [comment]
@kumarnarendra701: restart file will not be there in certs directory, when ever server has to restart, place restart file into the certs directory and server will restart when cron job finds the restart file. Please let me know if you need a quick demo on this feature.

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - I can see the restart file working now with below logs.

INFO|2021-09-22 00:00:01.192858|StatsNotificationService|StatsNotificationService is enabled. Runs every 15 seconds 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | INFO|2021-09-22 00:00:01.193074|AtCertificationValidation|Certificates reload job scheduled to run at 5 hours and 17 hours 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | INFO|2021-09-22 00:00:01.289631|AtSecondaryServer|Secondary server started on version : null on root server : root.atsign.wtf 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | INFO|2021-09-22 00:00:01.289842|AtSecondaryServer|Secure Socket open for @ordinary44 ! 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | FINER|2021-09-22 00:00:01.289875|AtSecondaryServer|serverSocket _listen : SecureServerSocket 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | FINER|2021-09-22 00:00:33.033021|AtSecondaryServer|In _listen - clientSocket.peerCertificate : null 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | FINER|2021-09-22 00:00:33.036683|InboundListener|command received: scan sessionID:_4c198a56-d50f-4e22-ba28-f05bd0591431 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | FINER|2021-09-22 00:00:33.036721|AtSecondaryServer|inside _executeVerbCallBack: scan 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | 
ee32a825-6cb2-5d64-ac76-e0358ea1a47c_secondary.1.yusflwv32tc7@buzz-02    | FINER|2021-09-22 00:00:33.036753|DefaultVerbExecutor|verb handler found : ScanVerbHandler

**Comment by cpswan** [comment]
@cconstab I see @kumarnarendra701 confirming that the work by @kalluriramkumar is doing what's needed, so are you OK to close this one?

**Comment by cconstab** [comment]
For sure
