### ISSUE TITLE
Hive Log files taking up memory (not lazy boxes and hence looks like memory leak)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#269]
The @sign @kryz_9850 is updating continuously metrics from a radio station. But on the backend infrastructure is is hitting swap very badly.

The updates are only 6 keys in the wavi namespace (all public) but the process size is large and causing the swaping.

![image](https://user-images.githubusercontent.com/6131216/129127060-e070bf57-4a4c-44ac-9273-86396b0af846.png)

The process table on hornet-07 shows a lareg process

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 257885 1024      20   0  155068  55864   9080 S   4.3   0.3 367:59.44 secondary
  22346 root      20   0 5004384 989896  25236 S   1.3   6.0  14876:36 dockerd
3078157 root      20   0 3092208   2.6g   5132 S   1.3  16.3   5145:39 ruby
 991656 1024      20   0   78140  57952   8944 S   0.7   0.4   0:30.96 secondary
1058804 root      20   0   11760   4580   3376 R   0.7   0.0   0:00.18 top
     11 root      20   0       0      0      0 I   0.3   0.0 119:58.29 rcu_sched
  22112 root      20   0 4321668  37896   4292 S   0.3   0.2   1474:53 containerd
  24753 root      20   0  416512 298080   6952 S   0.3   1.8   6363:09 agent
  98137 1024      20   0  113728  57276   9064 S   0.3   0.3   4:37.30 secondary
 641678 root      20   0  110128   5944   5136 S   0.3   0.0   0:06.76 containerd-shim
1056254 1024      20   0   37712  19024   8304 S   0.3   0.1   0:00.16 secondary
3741089 1024      20   0   71260  50240   8660 S   0.3   0.3   2:17.23 secondary
3754886 root      20   0   11804   4524   3340 S   0.3   0.0 165:19.92 hornet-07_top
3757447 1024      20   0   45392  26320   8464 S   0.3   0.2   6:29.14 secondary
3773561 1024      20   0   82216  55920   8464 S   0.3   0.3  16:36.83 secondary
3775059 1024      20   0   75948  53204   9268 S   0.3   0.3   3:54.23 secondary
3780535 1024      20   0   64404  47232   9156 S   0.3   0.3  11:38.66 secondary
3789134 root      20   0  108720   5432   4756 S   0.3   0.0   0:18.25 containerd-shim
3851780 1024      20   0   50776  29676   8440 S   0.3   0.2   7:09.03 secondary
3861087 1024      20   0   97840  55084   8976 S   0.3   0.3   6:37.01 secondary
3895630 1024      20   0   50844  30888   8544 S   0.3   0.2   2:40.35 secondary
3945492 1024      20   0   71256  50588   8544 S   0.3   0.3  14:55.51 secondary
3959281 root      20   0  108720   6192   5388 S   0.3   0.0   0:22.08 containerd-shim
3961417 1024      20   0   64336  46564   8672 S   0.3   0.3  11:05.52 secondary
3963693 root      20   0  110128   6240   5452 S   0.3   0.0   0:18.01 containerd-shim
root@hornet-07:~# ps -ef|grep 257885
1024      257885  257862  6 Aug08 ?        06:07:59 /usr/local/at/secondary -a @kryz_9850 -p 2829 -s 3b55b032e6f78186c4017239b5c2c692b746ff4cb373b5814e6075686018278d0f2692502e1a5ee3e365ae5b2969b30b10b3d5e87e80ed2ed52c2d369fc1288c
root     1058908 1058793  0 01:54 pts/1    00:00:00 grep --color=auto 257885
root@hornet-07:~#
```

I think we need to test that we do not have memory leaks, even if small they build up quickly and at some point this will drag down the infrastructure.

I have left the container running but please keep an eye on it..

@cconstab

**Comment by cconstab** [comment]
If need be restart the secondary (the client will recover), my guess is that it will hide the issue for a while.. But we need to find and fix.. 
The secondary is still responding just fine at the time of writing.. I just noticed it as I went through the dashboards.. Am I the only one who does that ?

**Comment by cconstab** [comment]
Moved secondary for kryz_9850 over to sheepdip machine so we can run in JIT mode and run observatory. 

The swap hits on the swarm stopped immediately as predicted..


![image](https://user-images.githubusercontent.com/6131216/129281042-ecdde96f-8942-42cf-bee5-a5710b6de304.png)

**Comment by cconstab** [comment]
To connect to sheepdip

```bash
gcloud compute ssh --ssh-flag="-L  127.0.0.1:8181:localhost:8181"  --zone "us-central1-a" "sheepdip"  --project "secondaries"
```

This will forward the observatory  to your machine locally where you can see what is going on via

[http://localhost:8181/XDJ9scZd4jc=/#/vm](http://localhost:8181/XDJ9scZd4jc=/#/vm)

The actually secondary is running under a new user account 'kryz' and that user has a tmux session running with the secondary in place.


```
cconstab@sheepdip:~$ sudo -s
root@sheepdip:/home/cconstab# su - kryz
kryz@sheepdip:~$ tmux attach -t 0
```

When get you there... `CTRL B` then `d` gets you back out of tmux if you have not used it before

**Comment by cconstab** [comment]
A picture is worth a 1000 words... We need to take a look at the heapsnapshot in a few hours... But BoxImpl and KeyStore are Hive related.. Need to see how they get bigger over time (likely)

![image](https://user-images.githubusercontent.com/6131216/129282956-d7aaebee-81ab-468d-a3ad-513d49ca381f.png)

**Comment by cconstab** [comment]
Some time later... (~2hours)  10Mb larger

![image](https://user-images.githubusercontent.com/6131216/129291441-a1234997-af01-418e-823d-898dfc7f003f.png)

**Comment by cconstab** [comment]
Two hours later up by .5Mb

![image](https://user-images.githubusercontent.com/6131216/129291682-339771e3-6b69-461d-97cd-56de65e1cfae.png)

**Comment by cconstab** [comment]
Up another .4Mb in ~2hours


![image](https://user-images.githubusercontent.com/6131216/129298944-6bf77c5d-5e93-4858-a23c-4a78e7257ec5.png)

**Comment by cconstab** [comment]
3 hours and 1Mb additional

![image](https://user-images.githubusercontent.com/6131216/129313255-fd04a78b-d84d-49b1-9716-7869212a3552.png)

**Comment by cconstab** [comment]
@cpswan @murali-shris @VJag 
I think this def an issue with the logging boxes.. What do you think ? Happy to run a modified branch to prove the point

**Comment by cpswan** [comment]
@cconstab the memory profiling seems to prove your expectation that Hive is doing what an in memory database should be expected to do. So absolutely the next step is to try a Hive config that more aggressively gets old data out of RAM and onto disk. With your particular use case we're using the DB as a message queue, and it seems suffering as a result of that (ab)use.

**Comment by cpswan** [comment]
#271 implements an observable secondary

**Comment by cconstab** [comment]
Needs architectural review but moving some (if not all) Hive boxes to lazy (just index in memory) seems like the best approach. Having this toggle at runtime also seems a reasonable idea and some people might like to run in memory.

**Comment by ksanty** [comment]
Work will be continued on #327
