### ISSUE TITLE
Locked Secondary. Hive error on scan

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#273]
Secondary non responsive and on further investigation looks like a HiveBox error

```
$ openssl s_client -ign_eof -brief 98cb53a3-b7ad-5c22-b56a-bc4803b8a405.hornet.atsign.zone:1898
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = 98cb53a3-b7ad-5c22-b56a-bc4803b8a405.hornet.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@scan
error:AT0010-Internal server error : HiveError: Box has already been closed.
@
```

Restarted secondary and all is well but we need to be able to detect this and recover seamlessly without admin interaction.
Should be straightforward to detect..

**Comment by cconstab** [comment]
We have also put in place monitoring that checks every @ sign every 15 minutes and lets us know if odd stuff is happening!

**Comment by murali-shris** [comment]
@cconstab Please close this issue if you no longer see the error in production
