### ISSUE TITLE
Dev/WTF secondary environment on GCP very ill

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#290]
Many secondaries are down or not coming up

**Comment by cconstab** [comment]
Bot keeps reporting many secondaries down/not responding.. I have looked at a few and whilst there might be other issues as well lets clean this up as we made the effort to migrate everything.

@kumarnarendra701 could you take the lead please..

Thanks


```
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    |
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | FINEST|2021-08-23 22:50:33.484493|AtRefreshJob|scheduleKeyRefreshTask runs at 20 hours
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    |
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | Unhandled exception:
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | Null check operator used on a null value
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #0      AtSecondaryConfig.notificationQuarantineDuration (package:at_secondary/src/server/at_secondary_config.dart:553)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #1      new ResourceManager._internal (package:at_secondary/src/notification/resource_manager.dart:25)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #2      ResourceManager._singleton (package:at_secondary/src/notification/resource_manager.dart:13)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #3      new ResourceManager.getInstance (package:at_secondary/src/notification/resource_manager.dart)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #4      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:175)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | <asynchronous suspension>
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #5      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | <asynchronous suspension>
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | #6      main (file:///app/at_secondary_server/bin/main.dart:21)
ff002b94-ef86-5890-bf9b-a30555575636_secondary.1.f3n18yew73x2@buzz-worker2    | <asynchronous suspension>
cconstab@buzz-master:~$
```

**Comment by sitaram-kalluri** [comment]
@cconstab and @kumarnarendra701 : The above issue is because of missing config.yaml file. The issue is fixed and merged with the following PR: https://github.com/atsign-foundation/at_server/pull/288

@kumarnarendra701 : Please pull the latest docker image and let us know if the issue still persists.

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - It seems the docker image update is completed but still seeing the same logs.
**Shepherd logs -** 
shepherd.1.adga3g8yr4li@buzz-master    | Mon Aug 23 19:06:55 EDT 2021 Cleaning up old docker images, leaving last 5
shepherd.1.vfl3yvr8j7r8@buzz-master    | Mon Aug 23 11:21:48 EDT 2021 Send registry authentication details to swarm agents
shepherd.1.adga3g8yr4li@buzz-master    | Mon Aug 23 19:06:56 EDT 2021 Trying to update service 9ae435ec-8f8b-59d3-80ab-a1e913eee60d_secondary with image reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env
shepherd.1.vfl3yvr8j7r8@buzz-master    | Mon Aug 23 11:21:51 EDT 2021 Trying to update service 0a00e5be-0131-5be4-bf7a-23cd05b9f032_secondary with image reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env
shepherd.1.adga3g8yr4li@buzz-master    | Mon Aug 23 19:08:08 EDT 2021 Service 9ae435ec-8f8b-59d3-80ab-

FINEST|2021-08-24 05:43:23.896614|HiveKeystore|hive value:AtData{data: f84a92170f29859724ea90554945249c47e495fedb266bfb936b76faa5554a0196b29282c8c3035369e856787b79cf7c64668ff49c490127d7e59e04f8fc88fb, metaData: {createdBy: null, updatedBy: null, createdAt: 2021-08-24 05:43:23.896552Z, updatedAt: 2021-08-24 05:43:23.896552Z, availableAt: null, expiresAt: null, refreshAt: null, status: active, version: 0, ttl: null, ttb: null, ttr: null, ccd: null, isBinary: null, isEncrypted: null, dataSignature: null} 

FINEST|2021-08-24 05:43:23.901423|AtRefreshJob|scheduleKeyRefreshTask runs at 13 hours 

**Docker logs -** 
Unhandled exception:
Null check operator used on a null value
#0      AtSecondaryConfig.notificationQuarantineDuration (package:at_secondary/src/server/at_secondary_config.dart:553)
#1      new ResourceManager._internal (package:at_secondary/src/notification/resource_manager.dart:25)
#2      ResourceManager._singleton (package:at_secondary/src/notification/resource_manager.dart:13)
#3      new ResourceManager.getInstance (package:at_secondary/src/notification/resource_manager.dart)
#4      AtSecondaryServerImpl.start (package:at_secondary/src/server/at_secondary_impl.dart:175)
<asynchronous suspension>
#5      SecondaryServerBootStrapper.run (package:at_secondary/src/server/bootstrapper.dart:50)
<asynchronous suspension>
#6      main (file:///app/at_secondary_server/bin/main.dart:21)
<asynchronous suspension>

**Comment by kalluriramkumar** [comment]
@kumarnarendra701: For some reason, the github action to build and push the secondary image to trunk was skipped. Will debug the cause and let you know when the trunk has latest image.
![image](https://user-images.githubusercontent.com/16645698/130566964-f0fe3946-c092-4dcc-8b4c-882e2aacc6fe.png)

**Comment by sitaram-kalluri** [comment]
@kumarnarendra701 : Are the above logs from staging environment or production environment. We merged the changes to staging environment and yet to be released into production.

**Comment by athandle** [comment]
@kalluriramkumar it's of staging(buzz)
You able to find the root cause why latest image was not pushed ?

**Comment by athandle** [comment]
@kalluriramkumar @kumarnarendra701 as per Colin health script 1038 secondaries are unhealthy. Please check

**Comment by cpswan** [comment]
I can see that a new secondary:dev_env image was pushed an hour ago, so @kumarnarendra701 can you please make sure that Shepherd is picking it up and rolling it across the fleet.

@kalluriramkumar the :dev_env image carries its own config.yaml, so the `AtSecondaryConfig.notificationQuarantineDuration` comes from a missing element in the template (which is why the code needs to carry the defaults for when an element [or the whole file] is missing).

**Comment by sitaram-kalluri** [comment]
@cpswan : The defaults are defined in AtSecondaryConfig.dart. Attaching the snippet below.

```dart
  //Notification
  static final int _maxNotificationRetries = 5;
  static int? _maxNotificationEntries = 5;
  static bool? _autoNotify = true;
  static final int _notificationQuarantineDuration = 10;
  static final int _notificationJobFrequency = 5;
```

```dart
  static int? get notificationQuarantineDuration {
    var result = _getIntEnvVar('notificationQuarantineDuration');
    if (result != null) {
      return _getIntEnvVar('notificationQuarantineDuration');
    }
    if (ConfigUtil.getYaml() != null &&
        ConfigUtil.getYaml()!['notification'] != null &&
        ConfigUtil.getYaml()!['notification']['quarantineDuration'] != null) {
      return ConfigUtil.getYaml()!['notification']['quarantineDuration'];
    }
    return _notificationQuarantineDuration;
  }
```

**Comment by cpswan** [comment]
@kalluriramkumar those snippets are from #288 which was merged yesterday to cause [at_server run 227](https://github.com/atsign-foundation/at_server/actions/runs/1158876107) resulting in [secondary:dev_env-trunk-gha227](https://hub.docker.com/layers/atsigncompany/secondary/dev_env-trunk-gha227/images/sha256-10330a217eec89c596da0324062e398fe8f26f1495bf6c9ef6a37e89912f545b?context=explore) and its corresponding :dev_env tag. So the mystery now is why that image appears to have caused the problem as it was rolled out rather than fixing it?

**Comment by kumarnarendra701** [comment]
@kalluriramkumar - Update failed for 61 secondaries with below msg - 

docker service logs -f 3n5wtozukzfb | grep cbe75af5-0f2a-5719-9246-bfaa4b4d3599
shepherd.1.ik6n4vaofhez@buzz-master    | service update paused: update paused due to failure or early termination of task n3trkof83ycc717fyyary9vu0
shepherd.1.xnauc76rg42s@buzz-master    | service update paused: update paused due to failure or early termination of task 60mxfxpki23zgqw0fg0eztiq2
shepherd.1.noxbplj6jc93@buzz-master    | service update paused: update paused due to failure or early termination of task fxu0l778i7xq5zeudoggwxfhl
shepherd.1.aa9qucbgvryp@buzz-master    | service update paused: update paused due to failure or early termination of task ykw9obus7a1bwppgqgkug4gjn

**Comment by athandle** [comment]
@cpswan yes Shephard is picking latest image
@kalluriramkumar can you please check logs shared by Narendra

**Comment by cconstab** [comment]
So I have focused on one secondary `e35d6848-fafd-5f04-8e66-dd839d71a182_secondary` 
aka
```
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary
@aaaa_67
```
It complains of no certificates 

```
cconstab@buzz-master:~$ docker service logs --tail 10 -f e35d6848-fafd-5f04-8e66-dd839d71a182_secondary
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    | INFO|2021-08-25 00:49:48.757742|AtSecondaryServer|certs unavailable. Retry count 58
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    |
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    | INFO|2021-08-25 00:49:58.762371|AtSecondaryServer|certs unavailable. Retry count 59
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    |
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    | INFO|2021-08-25 00:50:08.767905|AtSecondaryServer|certs unavailable. Retry count 60
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    |
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    | INFO|2021-08-25 00:50:18.773273|AtSecondaryServer|certs unavailable. Retry count 61
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    |
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    | SEVERE|2021-08-25 00:50:28.773472|AtSecondaryServer|certs not available
e35d6848-fafd-5f04-8e66-dd839d71a182_secondary.1.jqvmiujtsava@buzz-worker2    |
```

But everything looks just fine in the compose file... So I copied the compose file and changed the image to Ubuntu and exec'd into a bash shell.. And.. I see the certs with correct permissions!

```
root@buzz-worker2:/gluster/@/secondaries/49/d1/4a/47/49d14a47e532d4858712c3ab6a2831fc/e35d6848-fafd-5f04-8e66-dd839d71a182# docker exec -it ffa35db34e9d /bin/bash
root@ffa35db34e9d:/# ls
atsign  bin  boot  dev  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@ffa35db34e9d:/# cd /atsign
root@ffa35db34e9d:/atsign# ls
certs     config                    docker-compose.yml           docker-compose.yml-06-16-21  docker-compose.yml-08-04-21  storage
certscol  docker-compose-colin.yml  docker-compose.yml-06-12-21  docker-compose.yml-07-08-21  docker-compose.yml-08-21-21
root@ffa35db34e9d:/atsign# cd certs
root@ffa35db34e9d:/atsign/certs# ls
cacert.pem  e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.csr   e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.vald
cert.pem    e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.name  fullchain.pem
chain.pem   e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.resp  privkey.pem
root@ffa35db34e9d:/atsign/certs# ls -la
total 276
drwxr-xr-x 2 1024 1024   4096 Aug 21 21:09 .
drwxr-xr-x 6 1024 1024   4096 Aug 25 01:30 ..
-rw-r--r-- 1 1024 1024 228974 Aug 21 21:09 cacert.pem
-rw-r--r-- 1 1024 1024   2408 Aug 21 21:09 cert.pem
-rw-r--r-- 1 1024 1024   4399 Aug 21 21:09 chain.pem
-rw-r--r-- 1 1024 1024   1074 Aug 21 21:09 e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.csr
-rw-r--r-- 1 1024 1024    310 Aug 21 21:09 e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.name
-rw-r--r-- 1 1024 1024   2015 Aug 21 21:09 e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.resp
-rw-r--r-- 1 1024 1024   2038 Aug 21 21:09 e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone.vald
-rw-r--r-- 1 1024 1024   6807 Aug 21 21:09 fullchain.pem
-rw-r--r-- 1 1024 1024   1704 Aug 21 21:09 privkey.pem
root@ffa35db34e9d:/atsign/certs#
```

So confirmed the certs should be seen in the compose file but the secondary clearly does not see them which is VERY odd

**Comment by cconstab** [comment]
Ok secondary up... 
The only thing this could be is the cacert.pem file as the rest of the certs are seen. So I created a cacert/ directory and copoed over and permissioned a cacert.pem file

```
root@buzz-worker2:/gluster/@/secondaries/49/d1/4a/47/49d14a47e532d4858712c3ab6a2831fc/e35d6848-fafd-5f04-8e66-dd839d71a182# ls -l cacert/
total 228
-rw-r--r-- 1 atsign atsign 228974 Aug 25 02:09 cacert.pem
root@buzz-worker2:/gluster/@/secondaries/49/d1/4a/47/49d14a47e532d4858712c3ab6a2831fc/e35d6848-fafd-5f04-8e66-dd839d71a182#
```

restarted the secondary and its up

```
cconstab@buzz-master:~$ openssl s_client -brief 0:2279
Can't use SSL_get_servername
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = e35d6848-fafd-5f04-8e66-dd839d71a182.buzz.do-sf2.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@scan
data:["signing_publickey@aaaa_67"]
@
error:AT0003-Invalid syntax : invalid command
@CONNECTION CLOSED BY SERVER
cconstab@buzz-master:~$
```

**Comment by cconstab** [comment]
This seems to point to the Dockerfile not pulling over the file correctly or permissions of the file being mounted over. Also indicates to me that we could have the same issue in production so we need be careful!

**Comment by cconstab** [comment]
Built a secondary docker image from trunk then run it from compose file same issue found 
```
root@buzz-master:/home/cconstab# docker service ls |grep colin
137el7tt4vib   colin_secondary                                  replicated   1/1        cconstab/secondary:latest                                     *:2279->2279/tcp
root@buzz-master:/home/cconstab#
```
and  

```
cconstab@buzz-master:~$ docker service logs --tail 10 -f colin_secondary
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    | INFO|2021-08-25 02:56:01.374942|AtSecondaryServer|certs unavailable. Retry count 7
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    |
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    | INFO|2021-08-25 02:56:11.380360|AtSecondaryServer|certs unavailable. Retry count 8
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    |
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    | INFO|2021-08-25 02:56:21.385671|AtSecondaryServer|certs unavailable. Retry count 9
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    |
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    | INFO|2021-08-25 02:56:31.390498|AtSecondaryServer|certs unavailable. Retry count 10
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    |
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    | INFO|2021-08-25 02:56:41.395326|AtSecondaryServer|certs unavailable. Retry count 11
colin_secondary.1.lc3wkmj17bnj@buzz-worker2    |

```

**Comment by cconstab** [comment]
So the issue is the Dockerfile sets up /atsign/cacert which is just fine BUT the docker-compose.yaml file mounts /atsign NOT containing a cacert directory right on top of it.

**Solution is to move the cacerts directory in the docker image to another location that does not get mounted over for example /etc/cacerts**
Alternative we could just mount the needed subdirectories in /atsign but I think moving cacerts to etc make more sense but see what you think.

@cpswan 
@kalluriramkumar 
@murali-shris 


I suspect the secondaries all down and ones that are not are secondaries that failed to migrate to the new image and are running the old one..

**Comment by cconstab** [comment]
Maybe a better idea not to mount /atsign in the compose files.. That way we only mount /certs and everything works

**Comment by cpswan** [comment]
I applaud your optimism @kalluriramkumar, but let's keep this open until we have (the majority of) the staging secondaries back up.

**Comment by cpswan** [comment]
I just checked the new image for @survivingtaichi(2181) and it's connecting and scanning fine. So early signs are good.

@kumarnarendra701 can you please prod Shepherd into action to roll out the new image across staging.

I am however seeing our old nemesis `Too many open files`

```
f49ebec6-3ed8-59a5-96ba-6cfe743e762e_secondary.1.td5nl3eypl1d@buzz-worker2    | FileSystemException: Failed to initialize file system entity watcher (OS Error: Too many open files, errno = 24)
```

Also we need to do better with version info for dev_env builds (maybe GHA run numbers instead of `null`?):

```
f49ebec6-3ed8-59a5-96ba-6cfe743e762e_secondary.1.td5nl3eypl1d@buzz-worker2    | INFO|2021-08-25 10:06:36.347169|AtSecondaryServer|Secondary server started on version : null on root server : root.atsign.org
```

**Comment by cpswan** [comment]
NB with the staging secondaries binding `\atsign` it overrides having `\atsign\config\config.yaml` in the container, which is why we see staging secondaries connecting to production root `root.atsign.org`:

```
f49ebec6-3ed8-59a5-96ba-6cfe743e762e_secondary.1.td5nl3eypl1d@buzz-worker2    | INFO|2021-08-25 10:06:36.347169|AtSecondaryServer|Secondary server started on version : null on root server : root.atsign.org
```

This is another good reason for #214 but would also be taken care of by #296

Also `null` version comes from `\atsign\pubspec.yaml` being stomped, it should be showing the last release version (presently 2.0.7), though for dev_env we should add +GHArun so we can trace to specific test builds.

**Comment by cconstab** [comment]
Just FYI production secondaries also mount /atsign so we ned to be careful when we release..

```
 Target:        /atsign
  Source:       /gluster/@/secondaries/d5/01/96/5c/d501965ca45fe2425bc0f4892ec852d5/0a86ffbc-5944-5c34-a88f-d822f44e750e
  ReadOnly:     false
  Type:         bind
```


In better news 

```
Buzz, Bot, Now
26 Problematic Secondaries 
```

There are a few (2 so far) that do not startup and they were holding up shepherd.. For the moment I have set then to scale to 0 so they do not get in shepherds way..

**Comment by cconstab** [comment]
OK down to 12 and Shepherd is still updating stuff.. I have stopped 2 secondaries as they would not start, not investigated further..

How to find them `docker service ls |grep 0/0`

Also have TMUX session running as root on buzz-master1 if you want to watch the updates and spot anything than hangs shepherd..

`root@buzz-master:/tmp/seccheck# tmux attach -t top`

So more work to be done but in a better place...

**Comment by cconstab** [comment]
Started looking at secondaries in the last 12 .. Very odd this one.. not looked the others yet.. Seems to run out of memory and exit NO logs in dart land that are usefull, just opening boxes..

```
root@buzz-master:/gluster/@/secondaries/57/bd/6e/36/57bd6e36643e9b723dc4d10803f8c818/03a5cbe1-f183-5184-bbb4-3b7decd02f20# docker service ps 03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary --no-trunc
ID                          NAME                                                   IMAGE                                                                                                                                 NODE           DESIRED STATE   CURRENT STATE           ERROR                         PORTS
1fejhnb7yay0qihccjdx2fozf   03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1       reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:3e4d282a9f43c7f2b1a6fee3e4b48e1da4ed5054ad3792ff490c32db14e8028e   buzz-worker1   Running         Starting 1 second ago
bsrdnznp8zvdvodhn0psee30y    \_ 03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1   reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:3e4d282a9f43c7f2b1a6fee3e4b48e1da4ed5054ad3792ff490c32db14e8028e   buzz-worker2   Shutdown        Failed 6 seconds ago    "task: non-zero exit (137)"
sj4li5mhh1v0geb78n38g85wp    \_ 03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1   reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:3e4d282a9f43c7f2b1a6fee3e4b48e1da4ed5054ad3792ff490c32db14e8028e   buzz-worker1   Shutdown        Failed 16 seconds ago   "task: non-zero exit (137)"
vmma941su39kfn1jnjn9mvg9y    \_ 03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1   reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:3e4d282a9f43c7f2b1a6fee3e4b48e1da4ed5054ad3792ff490c32db14e8028e   buzz-worker2   Shutdown        Failed 27 seconds ago   "task: non-zero exit (137)"
vm5pzr7sbbpy5zx7got3mzb74    \_ 03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1   reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env@sha256:3e4d282a9f43c7f2b1a6fee3e4b48e1da4ed5054ad3792ff490c32db14e8028e   buzz-worker1   Shutdown        Failed 39 seconds ago   "task: non-zero exit (137)"
root@buzz-master:/gluster/@/secondaries/57/bd/6e/36/57bd6e36643e9b723dc4d10803f8c818/03a5cbe1-f183-5184-bbb4-3b7decd02f20#

```

dart logs

```
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.2tquecl49j4l@buzz-worker2    | INFO|2021-08-26 05:19:08.634171|CommitLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.2tquecl49j4l@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.2tquecl49j4l@buzz-worker2    | INFO|2021-08-26 05:19:08.653875|AccessLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.2tquecl49j4l@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    | INFO|2021-08-26 05:19:19.268813|AtSecondaryServer|currentAtSign : @amazingskyrunning
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    | FINER|2021-08-26 05:19:19.337604|CommitLogKeyStore|last committed sequence: 3026
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    | INFO|2021-08-26 05:19:19.337654|CommitLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    | INFO|2021-08-26 05:19:19.426218|AccessLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.k8etggltqmdn@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    | INFO|2021-08-26 05:19:29.280291|AtSecondaryServer|currentAtSign : @amazingskyrunning
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    | FINER|2021-08-26 05:19:29.347226|CommitLogKeyStore|last committed sequence: 3026
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    | INFO|2021-08-26 05:19:29.347265|CommitLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    |
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    | INFO|2021-08-26 05:19:29.432711|AccessLogKeyStore|Keystore initialized successfully
03a5cbe1-f183-5184-bbb4-3b7decd02f20_secondary.1.vo3a9x4cbq3z@buzz-worker2    |

```

Need to get some sleep so following the 🌞over to you...

**Comment by kumarnarendra701** [comment]
It seems 4-5 secondaries are not healthy and the rest are fixed by the new build.

@kalluriramkumar 
Logs - 
root@buzz-worker1:~# docker logs -f 27bcc40b9f43
INFO|2021-08-24 06:06:06.005750|AtSecondaryServer|currentAtSign : @excitedpuri😎 

FINER|2021-08-24 06:06:06.033375|CommitLogKeyStore|last committed sequence: 186 

INFO|2021-08-24 06:06:06.033422|CommitLogKeyStore|Keystore initialized successfully 

INFO|2021-08-24 06:06:06.044726|AccessLogKeyStore|Keystore initialized successfully 

FINER|2021-08-24 06:06:06.063586|HivePersistenceManager|AtPersistence.init received storagePath: storage/hive 

FINER|2021-08-24 06:06:06.063661|HivePersistenceManager|getHiveSecretFromFile fetching hiveSecretString for @excitedpuri😎 from file 

FINER|2021-08-24 06:06:06.063702|HivePersistenceManager|getHiveSecretFromFile found filePath: storage/hive/ecf03d82396109a503bedfc1ccb16a8725bffc89a26a07d474a86a04fc8692c6.hash 

AtServer.getHiveSecretFromFile file found
FINER|2021-08-24 06:06:06.069314|HivePersistenceManager|AtPersistence.openVault received atsign: @excitedpuri😎

Secondaries to debugs -
03a5cbe1-f183-5184-bbb4-3b7decd02f20
9b5e7c23-fe77-5b02-b84f-05cc72641bfd
943215b0-7977-5855-9450-814b8b439ed9
bb48453f-c560-59ac-815f-99703fd53488
d74250dd-0ab9-5ad4-a04c-1be1c4f223bd

**Comment by kumarnarendra701** [comment]
Directory for debugging -
/gluster/@/secondaries/d1/af/40/7d/d1af407dc4bb3aea6c873b785408e0ad/bb48453f-c560-59ac-815f-99703fd53488
Atsign uuid - bb48453f-c560-59ac-815f-99703fd53488

**Comment by kumarnarendra701** [comment]
@cpswan @cconstab - Can I close this ticket?

**Comment by cpswan** [comment]
Closing this now that the rebuilt environment appears stable.
