### ISSUE TITLE
Null certificates

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#302]
**Describe the bug**
The certificate refresh process sometimes creates an empty `cert.pem`, which then causes the secondary to fail.

**To Reproduce**

Not reproducable, but happens regularly enough to be a frequent issue detected by seccheck finding secondary failures.

**Expected behavior**
If the certificate refresh script fails to get a correct new cert then it should leave the existing cert in place and try again later

**Comment by cpswan** [comment]
@kumarnarendra701 has extended the sleep time while waiting for an API response from 10s to 30s, which will result in fewer empty certs, but we still need to have more robust retry logic and checking.

**Comment by kumarnarendra701** [comment]
Currently trying to test retry mechanism to fix it and down the line will move it to python script.

**Comment by kumarnarendra701** [comment]
@cpswan - Added retry for SSL get, please review and share your feedback.
https://github.com/atsign-company/secondaries-scripts/pull/4

**Comment by cpswan** [comment]
@kumarnarendra701 modified script to check that a cert is written
