### ISSUE TITLE
Increase the limit on Progressive Sync,

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#318]
**Is your feature request related to a problem? Please describe.**
At the moment, the limit on progressive sync is 10. which would a batch of 10 entries to the client. When there are more commit id's (around 30,000+) it would take a lot of time to complete the process. 

**Describe the solution you'd like**
Increase the limit and validate the large commit id's

**Describe alternatives you've considered**

**Additional context**

**Comment by sitaram-kalluri** [comment]
Enhance the sync verb handler to send data of 5 MB or 100 entries.

**Comment by sitaram-kalluri** [comment]
- [x] Development
- [x] QA

**Comment by purnimavenkatasubbu** [comment]
Tested with the 3 staging atsigns that were updated with the progressive sync changes. Whenever there are many images, Sync remains in the inprogress state for a long time. Adding logs for reference.

**atsign - gorgeouskicking**

INFO|2021-10-04 14:50:38.826192|SyncService|Returning the serverCommitId 1925
I/flutter (25909): FINEST|2021-10-04 14:50:38.834815|SyncService|server commit id: 1925 last synced commit id: 1925
I/flutter (25909): FINER|2021-10-04 14:50:38.843666|SyncUtil|localCommitId:1925
I/flutter (25909): FINER|2021-10-04 14:50:38.844052|SyncUtil|serverCommitId:1925
I/flutter (25909): FINER|2021-10-04 14:50:38.844438|SyncUtil|changed entries: 31
I/flutter (25909): INFO|2021-10-04 14:50:39.112578|SyncService|Returning the serverCommitId 1925
I/flutter (25909): FINER|2021-10-04 14:50:39.121635|SyncService|Sync in progress
I/flutter (25909): FINER|2021-10-04 14:50:39.130425|SyncService|syncing to remote. Total uncommitted entries: 31
I/flutter (25909): FINER|2021-10-04 14:50:39.182480|SyncService|batchId:1 key:@ gorgeouskicking:persona.pictures.buzz@ gorgeouskicking
I/flutter (25909): FINER|2021-10-04 14:50:39.184077|SyncService|batchId:2 key:_latestnotificationid.buzz@ gorgeouskicking

**atsign - average74crane**

**** another sync in progress
I/flutter (31654): FINER|2021-10-04 11:20:00.013276|SyncService|**** another sync in progress
I/flutter (31654): FINER|2021-10-04 11:20:05.005097|SyncService|**** another sync in progress
I/flutter (31654): FINER|2021-10-04 11:20:06.855444|SyncService|got stats notification in sync: 519
I/flutter (31654): FINER|2021-10-04 11:20:10.005736|SyncService|**** another sync in progress

**Comment by sitaram-kalluri** [comment]
For the above issue opened following bug: https://github.com/atsign-foundation/at_server/issues/342 and closing this issue.
