### ISSUE TITLE
Error handling of cert renewal crons / SSL alerts

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#326]
Chris: 
Stuff like that we should be just using Certbot, as we don’t need to create many certificates at once

@cconstab @cpswan feel free to update description

**Comment by cconstab** [comment]
Waht happened this morning was the cron job on Ludo created a secret with no files in it so the root daemon could not start.. All I did was re run the cron job ..

But we should check the files before turning them in to a secret and also make sure the secret is created properly!

**Comment by cpswan** [comment]
This is being addressed by the work @kumarnarendra701 is doing for #157

**Comment by athandle** [comment]
done as #157 is complete
