### ISSUE TITLE
additional stats

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#328]
- [X] "changes for stats and code review"
- [x] "publish packages"
- [x] "release to canary "
- [x] "release to prod"

**Comment by yahu1031** [comment]
May be to the next week(first 2 days for the perfection).

**Comment by yahu1031** [comment]
Set up everything related to stats (local secondary server, AWS - dess). Now working on CRUD operations and learning(understanding) the stats (diskSize, secondaryStorageSize).

**Comment by murali-shris** [comment]
Please include this stats as well 
Expose Health of compaction jobs

**Comment by yahu1031** [comment]
Face some issues with the windows machine. So setting up a Linux machine and setting up everything necessary for the stats development.

**Comment by yahu1031** [comment]
Notification count was done. (16-11-2021)
Working on count of keys

**Comment by yahu1031** [comment]
Notification stats were modified and done. Need to discuss notifications expiry with @VJag. And the rest 2 were on hold by Jagan. Have done some modifications in other stats too. Here are sample stats [output](https://cdn.sourceb.in/bins/ZePgEFuXI4/0).

### Modified

> stats:5

**Old :** `{"@minnu": "1"}`

**New :** `{@minnu: 1}`

> stats:6

**Old :** `{"signing_publickey@sunny": "4"}`

**New :** `{signing_publickey@sunny: 4}`

> stats:9 (diskSize)

**Old :** `"25.5 KB"`

**New :** `{size: 8.54, units: KB}`

**Comment by gkc** [comment]
@yahu1031 @murali-shris what's latest on this issue?

**Comment by murali-shris** [comment]
moving this to PR32..since compaction stats will help us to analyse sync issues better

**Comment by srieteja** [comment]
Compaction stats was completed in https://github.com/atsign-foundation/at_server/pull/459. Since it was not linked to this issue, this was not closed. As the PR linked was successfully merged, tested and released I will be closing this issue.
