### ISSUE TITLE
Production Issue with certificates

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#340]
**Symptoms**

@signs not being created on the registrar site. After activation no QR codes are received...

**Root Causes** 

From looking at the logs of the secondary creation both ZeroSSL and DigitalOcean are having issues with API's.

The cert creation script hits the ZeroSSL API and sometimes fails. Currently 50% failure rate in my testing that is better than earlier in the day it was 100% failure.

Next the Digital Ocean API is called and that was giving an 500 error message along with a huge amount of errors from Cloudflare (I know why have Cloudflare on an API!)

In either case these problems cause the script to backoff at a rate of 3X (With no limit on backoff!) 

This has then clogged the infrastructure API as it waits for a Q length of 5 before sending more atsign creation jobs to the script (This was my missing link in the problem)

**Situation now**

1) The Infrastructure API will not send jobs to create secondaries so no new secondaries are being created..
Options

- [x] Up the limit
- [x] unblock the Q

2) We still have a problem with the ZeroSSL API not being reliable

- [x] We have a direct connection to the CEO & CTO suggest Chris calls/emails them with hard facts

**Comment by cconstab** [comment]
Things I see runing the ZEROSSL API script on two machines one in the US (orac) one in DE (ubuntu)... Both work about 50% of the time right now 8:14PM PST



Orac
```
cconstab@orac:/tmp$ ./get_certs.py -c cconstabtest27 -d hornet.atsign.zone
Drafting certificate success
{"id":"c49b93d380e13cc127e55c818575f892","type":"1","common_name":"cconstabtest27.hornet.atsign.zone","additional_domains":"","created":"2021-10-14 02:10:45","expires":"2022-01-12 00:00:00","status":"draft","validation_type":null,"validation_emails":null,"replacement_for":"","validation":{"email_validation":{"cconstabtest27.hornet.atsign.zone":["admin@cconstabtest27.hornet.atsign.zone","administrator@cconstabtest27.hornet.atsign.zone","hostmaster@cconstabtest27.hornet.atsign.zone","postmaster@cconstabtest27.hornet.atsign.zone","webmaster@cconstabtest27.hornet.atsign.zone","admin@hornet.atsign.zone","administrator@hornet.atsign.zone","hostmaster@hornet.atsign.zone","postmaster@hornet.atsign.zone","webmaster@hornet.atsign.zone","admin@atsign.zone","administrator@atsign.zone","hostmaster@atsign.zone","postmaster@atsign.zone","webmaster@atsign.zone"]},"other_methods":{"cconstabtest27.hornet.atsign.zone":{"file_validation_url_http":"http:\/\/cconstabtest27.hornet.atsign.zone\/.well-known\/pki-validation\/3F59E25A8AD35CC4BEEA9E1181F9D879.txt","file_validation_url_https":"https:\/\/cconstabtest27.hornet.atsign.zone\/.well-known\/pki-validation\/3F59E25A8AD35CC4BEEA9E1181F9D879.txt","file_validation_content":["4A3EB44A5F651794CE006076561378804C9CDCE6C6107D29F97BA07A023B8B5E","comodoca.com","36a39c832591aaf"],"cname_validation_p1":"_3F59E25A8AD35CC4BEEA9E1181F9D879.cconstabtest27.hornet.atsign.zone","cname_validation_p2":"4A3EB44A5F651794CE00607656137880.4C9CDCE6C6107D29F97BA07A023B8B5E.36a39c832591aaf.comodoca.com"}}}}
CNAME looking for _3F59E25A8AD35CC4BEEA9E1181F9D879.cconstabtest27
CNAME found: <dns.resolver.Answer object at 0x7fa5b09a9c10>
Traceback (most recent call last):
  File "./get_certs.py", line 224, in <module>
    get_cert()
  File "./get_certs.py", line 178, in get_cert
    cert_file.write(cert.json()['certificate.crt'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
cconstab@orac:/tmp$
```

and ubuntu

```
ubuntu@ip-172-31-13-231:~/certs$ ./get_certs.py -c cconstabtest26 -d hornet.atsign.zone
Drafting certificate success
{"id":"e3dcfdfa4fc18234cf43ab1d9ca88612","type":"1","common_name":"cconstabtest26.hornet.atsign.zone","additional_domains":"","created":"2021-10-14 02:10:48","expires":"2022-01-12 00:00:00","status":"draft","validation_type":null,"validation_emails":null,"replacement_for":"","validation":{"email_validation":{"cconstabtest26.hornet.atsign.zone":["admin@cconstabtest26.hornet.atsign.zone","administrator@cconstabtest26.hornet.atsign.zone","hostmaster@cconstabtest26.hornet.atsign.zone","postmaster@cconstabtest26.hornet.atsign.zone","webmaster@cconstabtest26.hornet.atsign.zone","admin@hornet.atsign.zone","administrator@hornet.atsign.zone","hostmaster@hornet.atsign.zone","postmaster@hornet.atsign.zone","webmaster@hornet.atsign.zone","admin@atsign.zone","administrator@atsign.zone","hostmaster@atsign.zone","postmaster@atsign.zone","webmaster@atsign.zone"]},"other_methods":{"cconstabtest26.hornet.atsign.zone":{"file_validation_url_http":"http:\/\/cconstabtest26.hornet.atsign.zone\/.well-known\/pki-validation\/DCF7C2CC56D95E260EBAB47D741FBA48.txt","file_validation_url_https":"https:\/\/cconstabtest26.hornet.atsign.zone\/.well-known\/pki-validation\/DCF7C2CC56D95E260EBAB47D741FBA48.txt","file_validation_content":["894B6A928CB0D9CEBE74BE861DA314DFC1632894D07EE733567587C833AB3BDC","comodoca.com","5d948572bb409f3"],"cname_validation_p1":"_DCF7C2CC56D95E260EBAB47D741FBA48.cconstabtest26.hornet.atsign.zone","cname_validation_p2":"894B6A928CB0D9CEBE74BE861DA314DF.C1632894D07EE733567587C833AB3BDC.5d948572bb409f3.comodoca.com"}}}}
CNAME looking for _DCF7C2CC56D95E260EBAB47D741FBA48.cconstabtest26
CNAME found: <dns.resolver.Answer object at 0x7fd82fe5d1c0>
ubuntu@ip-172-31-13-231:~/certs$

```

**Comment by cconstab** [comment]
Long Term Thoughts

Need to come up with a long term plan and multiple suppliers.

Cannot be reliant on SPOF

Need to Abstract cert file generation

Possibly with new Abstraction or Using ACME ?

**Comment by cpswan** [comment]
I'm presently testing ACME (against Letsencrypt) with the [Digital Ocean DNS validator](https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-dns-validation-with-certbot-dns-digitalocean-on-ubuntu-20-04).

My thinking behind this:
* If ZeroSSL is having upstream problems then it will impact their ACME as well as the REST API
* DNS validation gets us away from having to queue up on port 80, so this should still be parallisable

I'll also look at doing a version of get_certs.py with greater debug output.

**Comment by cpswan** [comment]
Certbot with Digital Ocean DNS validation takes around 30-40s to create a certificate, of which 10s (by default) is spent waiting for DNS propagation. There's no automatic retry on failure.

I tried creating 10 certs in parallel, but that just resulted in 9 cases of `Another instance of Certbot is already running.`

My immediate take is that we can (and should) use Letsencrypt as a fallback for when we fail to get a cert from ZeroSSL, but there's more work to be done unpicking the inner working of Certbot and the ACME API inside before we can get what we really want.

**Comment by cpswan** [comment]
@athandle @kumarnarendra701 has the number of secondaries that can be spun up at once been increased yet?

I'm planning on closing this ticket, and creating some standalone tickets for enhancements.

**Comment by athandle** [comment]
@cpswan increased to 9 for now

**Comment by cpswan** [comment]
Closing, as the immediate actions are now completed, and longer term actions continue in other tickets.
