### ISSUE TITLE
Sync remains in-progress when there are multiple images.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#342]
**Describe the bug**

**To Reproduce**
1. First I '...' With Sync Progressive changes, when there are multiple images, sync remains in-progress.
2. Attaching the feature : https://github.com/atsign-foundation/at_server/issues/318
2. Then I '...'
3. And then '...'
4. 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - [e.g. @‎buzz, @‎tmosphere]

**Additional context**

**Comment by murali-shris** [comment]
@kalluriramkumar please validate whether this issue is still valid

**Comment by purnimavenkatasubbu** [comment]
We no longer use progressive sync and with the current implementation, Sync is completed successfully even with multiple images. Hence, closing the ticket.
https://drive.google.com/file/d/17QV-CfF1XVi7Tjwl2qKv-4-OIyyvX571/view?usp=share_link
