### ISSUE TITLE
benchmark lazybox on DESS server

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#347]
benchmark these metrics on a DESS server
https://docs.google.com/spreadsheets/d/1816Fmh-JrDUdnV4H_bq6iC_FOxl629JOfP0lSNcCTxU/edit#gid=46369083

**Comment by gkc** [comment]
@murali-shris old ticket, can we close it?

**Comment by ksanty** [comment]
@murali-shris can we close this issue?
