### ISSUE TITLE
Batch verb throws invalid syntax error - encoding of newline and tab chars

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#35]
Tested scenario

Using the @persona app, I created a key 'about' which has a multiple line value in it. The update is failing with the error as "Invalid syntax" 

Tried the same scenario in the terminal adding both app logs and server command.

App Logs

I/flutter (14885): SEVERE|2021-01-27 18:09:22.904166|SyncManager|update/delete for key public:about.persona@purni failed. Error code AT0003 error message Invalid syntax

Terminal command.

@purni@batch:[{"id":1,"command":"update:dataSignature:SG5DO9xXHJeo86cwPmd6SoFZRGauWV53ptthrrOsMLaBeti/SxWd0FsjgnpGsVCTEry7dsJSKTLlZG4tnD+8OwpKE5lrBaTHEKnRm4CG7NG5AKtJ8Q+fX7dWDyoJV+HA5eo4jSYrtpzfUFVkXuJYvV1WgKuaZHkJgM3tduY/UWThajr8Q85Dut5BXc09PdxT38bO2EMTEn0IuuD4/0EUyTalWEYbVG7lT26vFySFV3RL29H9JhmIIrf8WlHWg9E9tYkoPIfixs0uONtLpuZwnSGjYlslJVVWl8VsWff848hQ6aJ/iSlsGzxpfOVMGSnVZxLMkjxXfwvDq7WHOIvHgw==:isBinary:false:isEncrypted:false:public:about.persona@purni \rThanksgiving is a beloved American holiday celebrated on the 4th Thursday in November every year. On this day, delicious food is prepared and all the family members gather around the table and enjoy the tasty food together and say what they are grateful together. But What is the main purpose of Thanksgiving? Let us talk about the history and the purpose of Thanksgiving in this article.\r\rPurpose of Thanksgiving\r\rThanksgiving originally originated as a harvest festival. It has been celebrated as a national holiday since 1789 but after the proclamation of Congress by George Washington, it has been celebrated as a Federal holiday since 1864.\r\rFurthermore, the then President Abraham Lincoln proclaimed the holiday as “Thanksgiving and Praise to our beneficent Father who dwelleth in the Heavens”.\r\rThe “First Thanksgiving” was celebrated by Pilgrims after the first harvest in the new world October in 1621.\r\rThe celebration had a grand feast which lasted for 3 days and as per the attendee Edward Winslow, the celebration was attended by 90 Native Americans and 53 Pilgrims."}]
data:[{"id":1,"response":{"error_code":"AT0003","error_message":"Invalid syntax"}}]

key - about.persona.
Value -  
Thanksgiving is a beloved American holiday celebrated on the 4th Thursday in November every year. On this day, delicious food is prepared and all the family members gather around the table and enjoy the tasty food together and say what they are grateful together. But What is the main purpose of Thanksgiving? Let us talk about the history and the purpose of Thanksgiving in this article.

Purpose of Thanksgiving

Thanksgiving originally originated as a harvest festival. It has been celebrated as a national holiday since 1789 but after the proclamation of Congress by George Washington, it has been celebrated as a Federal holiday since 1864.

Furthermore, the then President Abraham Lincoln proclaimed the holiday as “Thanksgiving and Praise to our beneficent Father who dwelleth in the Heavens”.

The “First Thanksgiving” was celebrated by Pilgrims after the first harvest in the new world October in 1621.

The celebration had a grand feast which lasted for 3 days and as per the attendee Edward Winslow, the celebration was attended by 90 Native Americans and 53 Pilgrims.

**Comment by purnimavenkatasubbu** [comment]
This issue still exists. Assigning it to the developer.

**Comment by murali-shris** [comment]
new line/tab chars in values has to be encoded and stored

**Comment by murali-shris** [comment]
this requires discussion in architecture call regarding encoding of values with special chars. Moving this to backlog.

**Comment by gkc** [comment]
@murali-shris Was there a conclusion reached about way forward for this issue?

**Comment by gkc** [comment]
@murali-shris I'm setting priority to High on this one as per recent discussions.

**Comment by sitaram-kalluri** [comment]
If the value contains the new line character, the data is encoded. The changes are in the following PR's 
1 https://github.com/atsign-foundation/at_server/pull/835
2. https://github.com/atsign-foundation/at_client_sdk/pull/623

**Comment by sitaram-kalluri** [comment]
The changes are merged to trunk branch. Updating the tag to fixed for QA to test.

**Comment by gkc** [comment]
Moved to PR43

**Comment by purnimavenkatasubbu** [comment]
Verified the bug with the latest trunk branch. Now I don't see the invalid syntax error. But the data is not being displayed in the app. Raised a bug for the same.
[https://github.com/atsign-foundation/apps/issues/686](apps/issues/686)

**Comment by purnimavenkatasubbu** [comment]
A separate bug is open for the data not being displayed on both the client and app sides. Hence closing this issue.
[Data not displayed](https://github.com/atsign-foundation/apps/issues/686)
[Sync happens forever](https://github.com/atsign-foundation/at_client_sdk/issues/659)
