### ISSUE TITLE
CommitEntry is Null when syncing with the secondary

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/at_server#353]
**Describe the bug**
The CommitEntry is null when syncing with the secondary.

**To Reproduce**
1. Share keys to another atsign
2. Wait for sync to happen

Alternatively using [my demo app](https://github.com/XavierChanth/runtime_live/tree/main/episode_002):
1. Launch app and onboard
2. Create list items
3. Use share button on a list item to share to another atsign
4. Wait for sync
5. Restart the app and onboard again
6. Idle the app, and the background sync will fail

**Expected behavior**
Sync happens successfully.

**Screenshots**
In [my demo app](https://github.com/XavierChanth/runtime_live/tree/main/episode_002) the sync failing:
![image](https://user-images.githubusercontent.com/33691921/138003068-4967ef94-c833-4840-9e3a-6b9aa9d7259d.png)
When I relaunch the app and onboard:
![image](https://user-images.githubusercontent.com/33691921/138003107-709d0a95-e9e5-4376-9735-bc631911c8fc.png)

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Windows / Android API 31

**Additional context**
Looks like the issue starts [here](https://github.com/atsign-foundation/at_server/runs/3411555730).
The SDK tests start failing shortly after due to the server issues [here](https://github.com/atsign-foundation/at_client_sdk/runs/3926754974).

**Comment by sitaram-kalluri** [comment]
Fixed the issue in [PR-355](https://github.com/atsign-foundation/at_server/pull/355). Merged the changes to trunk branch and published to pub.dev. at_persistence_secondary_server - v.3.0.3 contains the changes

**Comment by sitaram-kalluri** [comment]
Please use at_client 3.0.4 version in the apps to resolve the issue.

**Comment by ksanty** [comment]
@XavierChanth are you still blocked?

**Comment by xavierchanth** [comment]
I'm no longer blocked, thanks @kalluriramkumar
