### ISSUE TITLE
100% CPU at Secondary startup

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#354]
**Describe the bug**
Secondary startup causes 100% CPU on startup (Constrained to %25 on docker swarm machine)

**To Reproduce**
1.  Start secondary
2. Seems to be tied to the opening/scanning of the log files '|CommitLogKeyStore|Keystore initialized successfully' 
3. After this message CPU shoots up
4. Once passed this step things calm down

**Expected behavior**
Not to have max CPU at startup 

This is causing start up issues on the secondaries as other problems seem to be making the logs larger as well ?

Do we really need to keep all the Keystore logs ?

**Screenshots**
Cut paste below

**Additional context**

**Comment by cconstab** [comment]
Max CPU

```
top - 00:08:43 up 68 days,  5:19,  2 users,  load average: 0.35, 0.55, 0.51
Tasks: 107 total,   1 running, 105 sleeping,   0 stopped,   1 zombie
%Cpu(s): 13.2 us,  7.1 sy,  0.0 ni, 79.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.3 st
MiB Mem :   1983.9 total,    913.7 free,    552.9 used,    517.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   1275.6 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 990364 kryz      20   0  391444 367428   7036 S 108.3  18.1   2:15.16 secondary
      1 root      20   0  168512   8016   3772 S   0.0   0.4   1:04.25 systemd
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.73 kthreadd
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par_gp
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker/0:0H-kblockd
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_percpu_wq
     10 root      20   0       0      0      0 S   0.0   0.0   0:06.16 ksoftirqd/0
     11 root      20   0       0      0      0 I   0.0   0.0   3:20.34 rcu_sched
 
```

The startup stalls here

```
kryz@sheepdip:~/secondary$ while true
> do
>  /home/kryz/at_server/at_secondary/at_secondary_server/secondary -a @kryz_9850 -p 6464 -s sjksadjfklsadfjk
> echo REBOOTED
> sleep 10
> done
INFO|2021-10-20 00:06:40.043097|AtSecondaryServer|currentAtSign : @kryz_9850

FINER|2021-10-20 00:06:51.907119|CommitLogKeyStore|last committed sequence: 984528

INFO|2021-10-20 00:06:51.907484|CommitLogKeyStore|Keystore initialized successfully
```

**Comment by cconstab** [comment]
You can look at this effect yourself on the sheepdip machine and the @kryz_9850 @sign.. My code uses atlookup not the atclientmobile code hence it is updating..

tmux will show the CPU via to and the running secondary in the other pane


```
cconstab@cally:~$ gcloud beta compute ssh --zone "us-central1-a" "sheepdip" --project "secondaries"
Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-1038-gcp x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

56 updates can be applied immediately.
7 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

*** System restart required ***
Last login: Tue Oct 19 23:23:18 2021 from 64.118.104.90
cconstab@sheepdip:~$ sudo -s
root@sheepdip:/home/cconstab# su - kryz
kryz@sheepdip:~$ tmux attach -t 0

```

**Comment by cconstab** [comment]
![image](https://user-images.githubusercontent.com/6131216/138016489-5a994891-bca1-4f74-8cbf-8a24cbabd7da.png)

**Comment by cconstab** [comment]
From what I am seeing CPU shoots up also on interaction with a client..

**Comment by cconstab** [comment]
Production Stats since the upgrade


![image](https://user-images.githubusercontent.com/6131216/138115673-1bda834c-461d-4597-b0ad-a7549735ad82.png)

**Comment by cconstab** [comment]
Prod is very unhappy with high load average an alarms all day.. Let us know what progress you make!

**Comment by murali-shris** [comment]
![cpu_profile_lazybox](https://user-images.githubusercontent.com/18326522/138268188-26ab3620-8b9b-4a5a-afd9-6f45eb2c7dff.png)
Compaction strategy that we are using in commit log is causing high CPU when there are frequent updates to secondary (file StorageBackendVM in attached pic).
Removing the compaction strategy and allowing hive to use default compaction strategy reduces the CPU .

**Comment by murali-shris** [comment]
![cpu_lazy_box_with_compaction](https://user-images.githubusercontent.com/18326522/138271297-b0cc1f08-c696-41fd-9601-8a8ec013d0f8.png)
CPU usage with compaction

**Comment by murali-shris** [comment]
![cpu_lazy_box_no_compaction](https://user-images.githubusercontent.com/18326522/138271364-8372b42a-8adb-413b-9cdc-b4cdab6e036a.png)
CPU usage without compaction

**Comment by cpswan** [comment]
Thanks @murali-shris

As we're not quite ready for canarying, and as this is affecting the whole prod environment, let's get this released to the whole estate.

**Comment by cconstab** [comment]
Things are stable but we need a Canary cage!

Thanks everyone for the new release..

There are still some atsigns that big memory so next step to find out why

**Comment by murali-shris** [comment]
@cconstab can this issue be closed?
