### ISSUE TITLE
Notification expiry

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#375]
- [ ] Compact notification keystore
- [x] Design **PR24**
- [ ] Implementation **PR25**

**Comment by ksanty** [comment]
Hi all, loving the lists and appreciate them.  Quick reminder to please use the check box, so we can track progress.  TY!!

**Comment by murali-shris** [comment]
Implementation sub tasks:
- [x] Server changes - TTL support on notify - server changes
- [x] cron changes to delete expired notifications
- [x] notify status changes
- [x] monitor changes
- [x] at client changes
- [x] dev testing, unit and functional tests
- [x] publish packages and merge to trunk
- [x] testing in staging
- [x] release to prod

**Comment by murali-shris** [comment]
testing and release pending.

**Comment by murali-shris** [comment]
released to canary servers
