### ISSUE TITLE
TTB Metadata persists even after updating the key with a TTL

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#379]
**Describe the bug**

A key set with a TTB has to be deleted before a TTL can be set.. Sample below the updated key is still only visible after 60seconds

**To Reproduce**
1. Create a key with a TTB and then update that key with a TTL 
2. The TTB persists and you have to delete the key and then set the TTL
3. Looks like a secondary code problem as the atClient sends the right metadata
4. 

**Expected behavior**
Old meta data should be ignored when the key is set

**Screenshots**
''' 
var metaData = Metadata()
    ..isPublic = true
    ..isEncrypted = false
    ..namespaceAware = true
    // // one minute
     ..ttb = 60000 ;

  var key = AtKey()
    ..key = hamradio.radioName
    ..sharedBy = currentAtsign
    ..sharedWith = null
    ..metadata = metaData;
;
  await atClient.put(key, message)

var metaData = Metadata()
    ..isPublic = true
    ..isEncrypted = false
    ..namespaceAware = true
    // // one minute
     ..ttl = 60000 ;

  var key = AtKey()
    ..key = hamradio.radioName
    ..sharedBy = currentAtsign
    ..sharedWith = null
    ..metadata = metaData;
;
 /// await atClient.delete(key); <- This line should not have to be used
  await atClient.put(key, message)
'''
**Additional context**

**Comment by ksanty** [comment]
Feature or bug @VJag will review

**Comment by gkc** [comment]
Seems like a bug ... @VJag what are next steps with this?

**Comment by VJag** [comment]
For now not passing the value is not conisdered a reset.

One way to deal with the problem is:

*. Set the TTL/TTB to Zero so that the value will be reset in the server.

or

*. Delete the key and add it again

**Comment by cconstab** [comment]
I have tried deleting the key and that worked fine.. I have to try setting to Zero.

I either case a sample/example would help here in the documentation

**Comment by VJag** [comment]
I will take care of adding a sample code for setting/resetting TTL/TTB

**Comment by gkc** [comment]
Is the correct behaviour here that setting a TTL should always clear any existing TTB? And also should we (or do we already) prevent something trying to set both a TTB/TTL at the same time?

**Comment by sitaram-kalluri** [comment]
@gkc : At the moment, TTL and TTB are not mutual exclusive. For a same key if TTB and TTL are set, the key is available when TTB is met and expires after the time mentioned in TTL. 
Also we have a way to reset the TTB in metadata. Setting to 0 would make the key available immediately. However this requires a minor code change (Modify IF condition that checks the TTB value) which are done in local and tested. Attaching the test log.

@sitaram@update:ttb:100000:@sitaram:key4@sitaram value4
data:5
@sitaram@llookup:@sitaram:key4@sitaram
data:null
@sitaram@update:ttb:0:@sitaram:key4@sitaram value4
data:6
@sitaram@llookup:@sitaram:key4@sitaram
data:value4
@sitaram@
