### ISSUE TITLE
New root deployment workflow for GCP

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#385]
**Describe the solution you'd like**
We previously had a workflow job that deployed the root server to Digital Ocean, but that infrastructure has been moved to GCP.

So we need a new version of that job that targets the GCP infrastructure, but it should only run when we do a release to production, so maybe use a tag rX.Y.Z where **r** is for Root.

**Describe alternatives you've considered**
We could continue running root deploys every time we push to staging, but this provides less control, and is potentially dangerous when trying to make changes to root.

**Comment by cpswan** [comment]
No progress on this in PR36, so bumping to PR37

**Comment by kumarnarendra701** [comment]
@cpswan - Added GitHub action workflow for root server deployment. Please review and let me know if you see any improvements.
https://github.com/atsign-foundation/at_server/pull/708

**Comment by kumarnarendra701** [comment]
@cpswan - Can we close this?
