### ISSUE TITLE
commit log - enhancements

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#392]
- [x] commit log compaction runs every 24 hrs. 
- [x] reduce the run frequency or consider compacting the log when an entry is added
- [x] QA testing
- [x] publish to pub.dev and release

**Comment by sitaram-kalluri** [comment]
Released code to production where the compaction job to run every one hour on commit log and access log.

Further, we have a version where compaction check triggers after every insert into the commit-log. If the criteria is met, compaction runs. The changes are currently in-development. Completed the implementation for commit-log compaction. and following is the PR: https://github.com/atsign-foundation/at_server/pull/412

**Comment by sitaram-kalluri** [comment]
[PR-412](https://github.com/atsign-foundation/at_server/pull/412) changes are deployed into canary atsign's

**Comment by purnimavenkatasubbu** [comment]
Tested the new changes with canary atsigns and came across issues. Attaching the logs and screenshots below.

**jittery5justfriends** 

SEVERE|2021-12-13 11:24:22.888746|AtLookup|Error in remote verb execution Exception: unable to connect to secondary
I/flutter (27539): _onSuccessCallback 2021-12-13 11:24:22.903596Sync status: SyncStatus.failure lastSyncedOn: 2021-12-13 05:54:22.903424Z Exception: AT0025: ErrorCode: AT0021 - Exception: Unable to connect to secondary true
I/flutter (27539): SEVERE|2021-12-13 11:24:23.007125|AtMeService|Fetching @ jittery5justfriends throws AT0014: Decryption failed. Encrypted value is null
I/flutter (27539): INFO|2021-12-13 11:24:23.007662|DashboardWidget|loading first atsign throws AT0014: Decryption failed. Encrypted value is null
2

**17robust**

 _onSuccessCallback 2021-12-13 11:35:04.416804Sync status: SyncStatus.success lastSyncedOn: 2021-12-13 06:05:04.416778Z Exception: null true
I/flutter (27539): INFO|2021-12-13 11:35:04.554619|EncryptionService|isEncrypted is set to false, Returning the original value without decrypting
I/flutter (27539): SEVERE|2021-12-13 11:35:04.565798|AtMeService|Fetching @17robust throws AT0014: Decryption failed. Encrypted value is null
I/flutter (27539): INFO|2021-12-13 11:35:04.566668|DashboardWidget|loading first atsign throws AT0014: Decryption failed. Encrypted value is null.

![Screenshot from 2021-12-13 13-13-49](https://user-images.githubusercontent.com/43639593/145785467-26022b99-83b5-4e04-9b17-316aa41664b2.png)
![1639380188182](https://user-images.githubusercontent.com/43639593/145785531-490b5021-2f6f-40d8-a765-333421fcb90e.JPEG)
![1639380506006](https://user-images.githubusercontent.com/43639593/145785536-388ad8a9-3647-493f-be52-ee36a3ef13f5.JPEG)

**Comment by sitaram-kalluri** [comment]
The changes are deployed to canary servers, Among the issue mentioned by @purnimavenkatasubbu 
1. Decryption failed is because of value being null.
2. The jitter5justfriend atsign crashes during initial sync. Debugged and turned out to be a memory issue. Pulled the hive storage directory to local and sync works fine,.
