### ISSUE TITLE
Move (some) canary secondaries from hornet to canary

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#411]
**Describe the solution you'd like**
Reconfigure ingress so that canaries can be moved to canary cluster

**Describe alternatives you've considered**
We already went with the alternative of having some secondaries configured to use

**Comment by athandle** [comment]
@cpswan is this for @kumarnarendra701 ? Not sure what I have to do in this

**Comment by cpswan** [comment]
@athandle we'll have to update a bunch of entries on the root server to make this work.

**Comment by kumarnarendra701** [comment]
@cpswan - Please confirm what details need to update for which atsign.

**Comment by cpswan** [comment]
Maybe the best way to explain it is in terms of what stays the same, and what's different:

## Stays the same:

* The /storage and /certs mount points on the hornet NFS - so the existing secondaries will stay where they are in terms of storage, and any new ones can be created on hornet and then moved.

## Different:

* The docker service will run on the canary cluster rather than hornet, so these secondaries will have to be turned down and removed from hornet, and re-instantiated on canary
* The network entry point - we'll need a new load balancer, and this will have different FQDNs that will need to be in the root server.

**Comment by athandle** [comment]
@cpswan do we need API to update the root entry or we need UI also?
uuid.domain:port is the current entry
Mentioned below are 4 parameters that are required
{ 
               atsign:${atsign},
               uuid:${uuid},
               domain:${domain},
               port:${port}
            }

**Comment by cpswan** [comment]
At this stage just the API, as I'd expect that we'll be using scripts to make the moves

**Comment by athandle** [comment]
Curl example 
Buzz(dev) RootURL: https://root-manager-b.dev.atsign.cloud
Hornet(prod) RootURL: https://root-api.prod.atsign.cloud
ACCESS_TOKEN_SECRET is in .env file of project
curl --location --request POST 'RootURL/api/atsign-infra/create' \
--header 'authorization: ACCESS_TOKEN_SECRET' \
--header 'Content-Type: application/json' \
--data-raw '{"atsign":"atsigntobeupdated", "uuid":"uuidofatsign",
               "port":"portnumber", "domain":"buzz.do-sf2.atsign.zone"}'

**Comment by cpswan** [comment]
Thanks @athandle 

I now have the first secondary relocated.

**Comment by kumarnarendra701** [comment]
@cpswan - Please check and confirm if we can close this ticket.

**Comment by cpswan** [comment]
This ticket wasn't just for registry work. I've kept it open whilst developing the script for secondary migration.

I still need to fix certs for the migrated secondaries, and automate how that gets done going forward.

**Comment by cpswan** [comment]
Scripts now completed for migrating and fixing certs.

@cconstab just waiting on you for https://github.com/atsign-company/secondaries-scripts/pull/11
