### ISSUE TITLE
Notification performance benchmarking

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#416]
* Notification subsystem benchmarking
* Notify status benchmarking

**Comment by sitaram-kalluri** [comment]
Send 500 and 1,00,000 notifications  from one atsign to another and captures the time take to deliver the notifications. Attaching the link's to CSV:

[notify-500-keys](https://drive.google.com/file/d/1ll-4Awy1gHzOaL9xJPAlrSuBL1f7zBIq/view?usp=sharing)
[notify-1lakh-keys](https://drive.google.com/file/d/1OtMslo4r-k0ZUvFhqGs3l40iK127XFUb/view?usp=sharing)

**Comment by gkc** [comment]
@cconstab did you get a chance to look at the benchmarking results?
