### ISSUE TITLE
Staging atsigns are stuck in the activating mode

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#428]
**Describe the bug**
Unable to use the staging atsigns as the atsigns in the dashboard remains in the activating state.

**To Reproduce**
1. Login to the dashboard 
2.  Check the status of the atsign.

**Expected behavior**
Atsign state should either be activated.

**Screenshots*
![Screenshot from 2021-12-06 19-57-24](https://user-images.githubusercontent.com/478926/145057542-65a7b6bf-339c-4730-9626-3a53a917fabd.png)
*
![1638860896156](https://user-images.githubusercontent.com/478926/145057596-11565781-0cb3-4b63-a80d-7caac8cd30de.JPEG)

**Comment by athandle** [comment]
SSL not generating

**Comment by purnimavenkatasubbu** [comment]
Restarted the atsigns average74crane and disgustedcontinentaljazz again and tried to run the app by pointing to the latest code of at_client and at_client_mobile. I was able to authenticate to the apps. But the activating issue with the remaining atsigns still exists

**Comment by athandle** [comment]
secondaries are working fine now, let me know if you still face any issues

**Comment by purnimavenkatasubbu** [comment]
Now the staging atsigns are working.
