### ISSUE TITLE
Unable to get into the wavi app with the canary atsigns

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#432]
**Describe the bug**
After authenticating into the wavi app, Unable to perform any action. An error message as "something went wrong" or the Edit icon being missed.

**To Reproduce**
1. First I authenticate to the wavi app
2. Then check the dashboard

**Expected behavior**
Edit icon and the list of authenticated atsigns should be displayed. 

**Screenshots**
![1639380506006](https://user-images.githubusercontent.com/43639593/145810812-041fca69-c7d6-4700-aff0-d57d33dab703.JPEG)
]

**Smartphone (please complete the following information):**
 - Device: [e.g.Samsung Galaxy]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - [e.g. @ wavi]

**Additional context**
Atsigns Used - 17robust, jittery5justfriends, bluegreen129slow

**App logs**
 _onSuccessCallback 2021-12-13 11:35:04.416804Sync status: SyncStatus.success lastSyncedOn: 2021-12-13 06:05:04.416778Z Exception: null true
I/flutter (27539): INFO|2021-12-13 11:35:04.554619|EncryptionService|isEncrypted is set to false, Returning the original value without decrypting
I/flutter (27539): SEVERE|2021-12-13 11:35:04.565798|AtMeService|Fetching @17robust throws AT0014: Decryption failed. Encrypted value is null
I/flutter (27539): INFO|2021-12-13 11:35:04.566668|DashboardWidget|loading first atsign throws AT0014: Decryption failed. Encrypted value is null

**Comment by purnimavenkatasubbu** [comment]
Re-tested the issue with the latest at_client: 3.1.3 & at_client_mobile: 3.0.7, With the 17robust atsign. I was able to get into the app. But with the other atsign, bluegreen129slow and jittery5justfriends the issue still exists.

SEVERE|2021-12-20 14:59:16.727327|AtMeService|Fetching @ bluegreen129slow throws Exception: public:_latestnotificationid.wavi@bluegreen129slow does not exist in keystore
I/flutter (31794): INFO|2021-12-20 14:59:16.728244|DashboardWidget|loading first atsign throws Exception: public:_latestnotificationid.wavi@bluegreen129slow does not exist in keystore

Note: This issue is already been fixed earlier and has not occurred with 17robust atsign.

**Comment by yahu1031** [comment]
For `privatekey:self_encryption_key` Key, The value is being null. Not sure why. Checking on it.

**Comment by yahu1031** [comment]
It is an issue with the app get method in [`sdk_service.dart line#86`](https://github.com/atsign-company/at_settings/blob/master/lib/services/sdk_service.dart#L85). That must be handled with try-catch.

```dart
Future<AtValue> get(AtKey atKey) async {
  AtValue atValue;
  bool validKey = _isValidKey(atKey);
  atKey.metadata!.isPublic = atKey.sharedWith == null;
  try {
    var atKeyCopy = AtKey()
      ..key = atKey.key
      ..isRef = atKey.isRef
      ..metadata = atKey.metadata
      ..sharedBy = atKey.sharedBy
      ..sharedWith = atKey.sharedWith
      ..namespace = atKey.namespace;
    if (atKeyCopy.namespace == AppConstants.personaNameSpace) {
      atKeyCopy.metadata!.namespaceAware = false;
      atKeyCopy..key = '${atKeyCopy.key}.${AppConstants.personaNameSpace}';
    }
    atValue = await _getAtClientForAtsign().get(atKeyCopy);

    if (atKeyCopy.namespace == AppConstants.personaNameSpace &&
        atValue.value != null) {
      await delete(atKeyCopy);
      atKey.metadata!.namespaceAware = true;
      await put(atKey, atValue.value);
      atValue = await _getAtClientForAtsign().get(atKey);
    }
    if (isValid(atValue.value) && validKey) return atValue;
    //cached keys cannot be updated
  } on KeyNotFoundException {
    return AtValue();
  }
  return AtValue();
}
```
something similar to this.

**Comment by yahu1031** [comment]
Looks like we were having issues with getting values from keys for a very long time. As we already know there will be some failures in getting values, wrapping up the logic with try-catch will avoid it.

**Additional Info:**
Tested with `@judicialabseiling` and `@bluegreen129slow` atsigns and it was handled correctly.

**Comment by purnimavenkatasubbu** [comment]
Tested the issue with the latest fix. Now the issue is resolved and I'm able to get into the wavi app successfully.
![Screenshot_20211221-201339](https://user-images.githubusercontent.com/43639593/146948825-4362ee4c-9f02-48a1-a129-7f471edd0172.jpg)

https://user-images.githubusercontent.com/43639593/147537944-c7b6e333-f8e2-450b-8262-6a1851735dcf.mp4

**Comment by murali-shris** [comment]
@purnimavenkatasubbu please verify and close this issue after app is released to test flight/playstore
