### ISSUE TITLE
API new status request 

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#439]
Problem statement: When the secondary is creating or in unhealthy state registrar always shows Activating
We have mentioned below code with status API (https://wavi.ng/status/atsign)
418 - secondary created
200 - Activated
500 - secondary not created

Solution: Show unhealthy state when secondary is unhealthy and Activating when it's actually activating
503 - unhealthy . It will be great if API can return status code as 503 for unhealthy secondary
Registrar need 1 status which will show that secondary was created successfully but now secondary is in unhealthy state.
Linked to https://github.com/atsign-company/at_find_api/issues/27

**Comment by gkc** [comment]
This issue has caused some confusion recently so am setting priority to High.

**Comment by gkc** [comment]
@athandle what do you need in order to add this new status to the Registrar?

**Comment by athandle** [comment]
@gkc @srieteja is working on this. I just need 503 as status if secondary is unhealthy

**Comment by srieteja** [comment]
deployed to staging at_find_api. Will close this after further testing.

**Comment by gkc** [comment]
@srieteja any update?

**Comment by srieteja** [comment]
@gkc my changes have been deployed to staging env and I have verified them. They are working as expected. @athandle can provide more info reg deployment to production environment.

**Comment by athandle** [comment]
moved to prod
