### ISSUE TITLE
Move build deployment to into GitHub Actions from buddy

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#441]
![image](https://user-images.githubusercontent.com/61007675/146231056-0e977ebd-eea3-4e47-840d-5862bee743c2.png)

- [x] https://github.com/atsign-company/at_find_api
- [x] https://github.com/atsign-company/at_handle_registrar_web
- [x] https://github.com/atsign-company/infrastructure_api
- [x] https://github.com/atsign-company/registrar_node
- [x] https://github.com/atsign-company/infrastructure_root_manager

**Comment by kumarnarendra701** [comment]
@cpswan - I have created a GitHub action workflow for the infra_api dev branch. Please review and share your feedback.
Repo - https://github.com/atsign-company/infrastructure_api/blob/dev/.github/workflows/infra_api_dev.yml

Need your input for the production k8 cluster. Actually, we have IP's bassed restriction k8 cluster i.e "Control plane authorized networks" and earlier we had whitelisted buddy works IP to make the connection via Buddy works but Github has a large no of IP's pools for whitelisting. So there is an option to use self-hosted runners for that.

**Comment by cpswan** [comment]
@kumarnarendra701 please create a pull request and make me a reviewer.

We should be using identity (in secrets) rather than IPs for the connections to k8s.

**Comment by kumarnarendra701** [comment]
@cpswan - Raised PR for your review. 
https://github.com/atsign-company/infrastructure_api/pull/9

Can you please guide and point me to any reference doc for identity (in secrets) to connect with K8s?

**Comment by cpswan** [comment]
@kumarnarendra701 here's the [Deploying to Google Kubernetes Engine](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine) guide for GitHub Actions.

**Comment by kumarnarendra701** [comment]
@cpswan - I have followed the same steps and authenticated Dev K8 cluster via "GKE_SA_KEY" but on prod, we have an additional layer of security i.e "Control plane authorized networks".

**Comment by cpswan** [comment]
@kumarnarendra701 how about using a self hosted runner for the deploy part of the action (per https://suspendfun.com/2020/Continuous-deployment-to-gke-with-github-actions/)?

**Comment by kumarnarendra701** [comment]
@cpswan - Yeah, that's is what I mentioned in the first comments to use self-runner for deployment on the private cluster and asked for your input. We will spin up one runner in the same network and connect with GitHub action for deployment.

**Comment by athandle** [comment]
infrastructure_api moved to github actions

**Comment by kumarnarendra701** [comment]
@cpswan - Please review and let me know if you see any refactoring.
https://github.com/atsign-company/infrastructure_api/pull/10

**Comment by kumarnarendra701** [comment]
@cpswan - Raised below PR's for review.
https://github.com/atsign-company/registrar_node/pull/27
https://github.com/atsign-company/infrastructure_root_manager/pull/3

**Comment by cpswan** [comment]
@kumarnarendra701 they're now approved - please merge.

**Comment by kumarnarendra701** [comment]
@cpswan - Please find below PR for at_handle_registrar_web
https://github.com/atsign-company/at_handle_registrar_web/pull/267

**Comment by kumarnarendra701** [comment]
@cconstab @cpswan - Created GitHub action pipeline for "at_find_api" but we need to run a few commands before Docker build. So I tried to find it in Buddy.works variables but it seems variables are encrypted.

Need the below variables -
cp $CONFIG ~/.ssh
cp $PRIVATE_KEY ~/.ssh

Here is the GitHub action file - https://github.com/atsign-company/at_find_api/blob/feature/ci-cd-411/.github/workflows/infra_api_dev.yml

**Comment by kumarnarendra701** [comment]
@cpswan - Can we please help me with an alternative of this and can replace this with another auth like GitHub token. Please share your thoughts.
```
          cp $CONFIG ~/.ssh
          cp $PRIVATE_KEY ~/.ssh
          **mv ~/.ssh/CONFIG ~/.ssh/config
          mv ~/.ssh/PRIVATE_KEY  ~/.ssh/id_rsa**
          chmod 0600 ~/.ssh/id_rsa
          #ls ~/.ssh
          #cat ~/.ssh/config
          #cat ~/.ssh/id_rsa
          #echo $GIT_SSH_COMMAND
          eval `ssh-agent -s`
          #cat $PRIVATE_KEY
          ssh-add <(cat $PRIVATE_KEY) 
          # List out your new key's fingerprint
          ssh-add -l
          **ssh -o "StrictHostKeyChecking no" -T git@github.com || echo working**
          cd /buddy/at-find-api
          pub get
          pub update
          cd bin
          dart compile exe main.dart -o directory
```
GitHub Action file - https://github.com/atsign-company/at_find_api/blob/feature/ci-cd-411/.github/workflows/infra_api_dev.yml

**Comment by kumarnarendra701** [comment]
@cpswan @athandle - at_find_api repo migrated to GitHub action. Below are the workflows and updated Dockerfile.
https://github.com/atsign-company/at_find_api/tree/trunk/.github/workflows
https://github.com/atsign-company/at_find_api/blob/trunk/Dockerfile

**Comment by cpswan** [comment]
Thanks @kumarnarendra701 

Please see https://github.com/atsign-company/at_find_api/pull/33 for a final refinement.

And then are we done with this ticket?

**Comment by kumarnarendra701** [comment]
@cpswan - Can we close this?
