### ISSUE TITLE
Fix root k8 renewal cronjob

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#454]
Lead: @athandle 

Earlier we have Cronjob on DO and with help of LB routing we had directed 80 port for the renewal of cronjob but we had to restore DO backup to GKE and cronjob not working because 80 port is not redirecting to the renewal pod.

**Comment by kumarnarendra701** [comment]
@cpswan @athandle - Need your help on this, Actually, we have one cronjob in K8 to renew SSL for "root.atsign.wtf" but when it migrated to GCP it's not forwarding to port 80. 
Service Name - root-ssl-renewal-svc

**Comment by athandle** [comment]
cc @gkc @cconstab

**Comment by cpswan** [comment]
Noting the agreed way ahead for this:

Done by @cpswan :

- [x] Move root.atsign.wtf and root.atsign.org DNS to Digital Ocean for API access
- [x] Modify ACME cert script to allow creation of root certs

Todo @kumarnarendra701 :

- [x] Create GitHub action to use cron to create new certs on a schedule
- [x] Connect that action to staging and prod root K8s secrets

**Comment by kumarnarendra701** [comment]
@cpswan - I have created a GitHub workflow to generate certs and update them to k8 secrets.

Note - During my multiple retries it blocked my certs generation for "root.atsign.wtf" domain. So temporarily added another buzz domain to complete the workflow without the "-r" flag and will replace it before making it live. Please review and let me know if you see any improvement.

PR - https://github.com/atsign-company/infrastructure_root_manager/pull/12

Need to add/change the below lines before cron scheduler.

```
To generate certs for root.atsign.wtf
# python3 acme_certs.py -r ${{ secrets.STAGING_ROOT_DOMAIN }}
To refresh new certs for root pods.
kubectl create secret generic narendra-certs --from-file=/tmp/certs -n root
```

**Comment by kumarnarendra701** [comment]
@cpswan - Added prod and stage YAML file with cronjob scheduler.

**Comment by kumarnarendra701** [comment]
@cpswan- Can you please merge my PR and close this ticket.
https://github.com/atsign-company/infrastructure_root_manager/pull/12
