### ISSUE TITLE
The regex in the scan from AtLookupImpl does not result in the right results. 

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#458]
**Describe the bug**
The regex in the scan from AtLookupImpl does not result in the right results. 

**To Reproduce**
1. This was found in the at_find_api repo with this line of code ` await atLookupImpl.scan(regex: '.(wavi|persona)@', auth: false);`
2. It resulted in the rights keys returning but in addition a key that had no atsign 
3. So to reproduce create an atsign and add a key that has no mention of an atsign 
4.  use  atLookupImpl.scan(regex: '.(wavi|persona)@ to search for just keys with .wavi@ and .persona@

**Expected behavior**
Only keys with regex should be returned

**Screenshots**
```
_dataHandler received keysList: [about.wavi@barbara, custom_about_our_company.wavi@barbara, custom_more_profiles.wavi@barbara, custom_our_company.wavi@barbara, custom_recent_articles_and_posts.wavi@barbara, custom_recent_reads.wavi@barbara, custom_recentlyreadbooks, 1.persona@barbara, custom_things_that_not_even_google_knows_about_me.wavi@barbara, custom_welcome.wavi@barbara, email.wavi@barbara, field_order_of_self.wavi@barbara, firstname.wavi@barbara, followers_of_self.at_follows.wavi@barbara, following_by_self.at_follows.wavi@barbara, image.wavi@barbara, instagram.wavi@barbara, lastname.wavi@barbara, linkedin.wavi@barbara, location.wavi@barbara, locationnickname.wavi@barbara, phone.wavi@barbara, privateaccount.wavi@barbara, theme.wavi@barbara, theme_color.wavi@barbara, twitter.wavi@barbara]

```

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS14.1]
 - Version [e.g. 59]

**Were you using an @‎application when the bug was found?**
  - @wavi

**Additional context**

**Comment by yahu1031** [comment]
@cconstab Is that only with wavi and persona namespaces? Can you please check and tell us if it happens with any other namespaces.

**Comment by yahu1031** [comment]
`custom_recentlyreadbooks` this data is from regex `.persona@`. `.wavi@` has healthy data 
```lua
-- scan .wavi@

data:[
    "about.wavi@barbara",
    "custom_about_our_company.wavi@barbara",
    "custom_more_profiles.wavi@barbara",
    "custom_our_company.wavi@barbara",
    "custom_recent_articles_and_posts.wavi@barbara",
    "custom_recent_reads.wavi@barbara",
    "custom_things_that_not_even_google_knows_about_me.wavi@barbara",
    "custom_welcome.wavi@barbara",
    "email.wavi@barbara",
    "field_order_of_self.wavi@barbara",
    "firstname.wavi@barbara",
    "followers_of_self.at_follows.wavi@barbara",
    "following_by_self.at_follows.wavi@barbara",
    "image.wavi@barbara",
    "instagram.wavi@barbara",
    "lastname.wavi@barbara",
    "linkedin.wavi@barbara",
    "location.wavi@barbara",
    "locationnickname.wavi@barbara",
    "phone.wavi@barbara",
    "privateaccount.wavi@barbara",
    "theme.wavi@barbara",
    "theme_color.wavi@barbara",
    "twitter.wavi@barbara",
]
```
where
```lua
-- scan .persona@
data:[
    "custom_recentlyreadbooks",
    "1.persona@barbara",
]
```

Image
<img width="1667" alt="Screenshot 2022-01-05 at 11 59 52 AM" src="https://user-images.githubusercontent.com/35523357/148170813-c3235cd2-8c8b-48b2-ab9f-ef035d402d41.png">

**Comment by yahu1031** [comment]
@cconstab When I tried scanning with the regex `.(wavi|persona)@` i got the list of these keys :
```lua
data:[
  "about.wavi@barbara",
  "custom_about_our_company.wavi@barbara",
  "custom_more_profiles.wavi@barbara",
  "custom_our_company.wavi@barbara",
  "custom_recent_articles_and_posts.wavi@barbara",
  "custom_recent_reads.wavi@barbara",
  "custom_recentlyreadbooks",
  "1.persona@barbara",
  "custom_things_that_not_even_google_knows_about_me.wavi@barbara",
  "custom_welcome.wavi@barbara",
  "email.wavi@barbara",
  "field_order_of_self.wavi@barbara",
  "firstname.wavi@barbara",
  "followers_of_self.at_follows.wavi@barbara",
  "following_by_self.at_follows.wavi@barbara",
  "image.wavi@barbara",
  "instagram.wavi@barbara",
  "lastname.wavi@barbara",
  "linkedin.wavi@barbara",
  "location.wavi@barbara",
  "locationnickname.wavi@barbara",
  "phone.wavi@barbara",
  "privateaccount.wavi@barbara",
  "theme.wavi@barbara",
  "theme_color.wavi@barbara",
  "twitter.wavi@barbara"
]
```

Then i tried with `.wavi@`, And I got :
```lua
data:[
  "about.wavi@barbara",
  "custom_about_our_company.wavi@barbara",
  "custom_more_profiles.wavi@barbara",
  "custom_our_company.wavi@barbara",
  "custom_recent_articles_and_posts.wavi@barbara",
  "custom_recent_reads.wavi@barbara",
  "custom_things_that_not_even_google_knows_about_me.wavi@barbara",
  "custom_welcome.wavi@barbara",
  "email.wavi@barbara",
  "field_order_of_self.wavi@barbara",
  "firstname.wavi@barbara",
  "followers_of_self.at_follows.wavi@barbara",
  "following_by_self.at_follows.wavi@barbara",
  "image.wavi@barbara",
  "instagram.wavi@barbara",
  "lastname.wavi@barbara",
  "linkedin.wavi@barbara",
  "location.wavi@barbara",
  "locationnickname.wavi@barbara",
  "phone.wavi@barbara",
  "privateaccount.wavi@barbara",
  "theme.wavi@barbara",
  "theme_color.wavi@barbara",
  "twitter.wavi@barbara"
]
```
I didn't find those suspicious keys there. And then I tried with `.persona@`, Then I found these :
```lua
data:[
  "custom_recentlyreadbooks",
  "1.persona@barbara"
]
```
### Explanation ###

The keys that we should get with the `.person@` regex scan is **`data:[custom_recentlyreadbooks,1.persona@barbara]`**.

Finally manipulating this data with the `scan` logic, is what happens
- This data will be converted to String and filtered as `custom_recentlyreadbooks,1.persona@barbara`.
- As the list.toString() will convert the data with `,` we are splitting it with `,`.
- And as we have `,` in the key, That will be split as `[custom_recentlyreadbooks,  1.persona@barbara]`.
- There we go, This is the reason we are getting this issue.

**Comment by cconstab** [comment]
So what is the answer here ? Do we need to prevent ',' in keys ?

**Comment by yahu1031** [comment]
@cconstab The idea I can tell is to avoid all the special chars except `_` in the keys to come over this kind of issue in the future.

**Comment by yahu1031** [comment]
Or the other idea is, iterate through the list of keys and return the matched list instead of converting them to string and splitting up with `,`.

**Comment by yahu1031** [comment]
I think I got a fix. Can you please verify @cconstab @murali-shris @kalluriramkumar 
![image](https://user-images.githubusercontent.com/35523357/148254485-756c67c0-2abf-4edc-9031-af51911a0af0.png)

**Comment by yahu1031** [comment]
Well, I have tried with `at_find_api` and got this healthy result
```
_dataHandler received keysList: [
  about.wavi@barbara,
  custom_about_our_company.wavi@barbara,
  custom_more_profiles.wavi@barbara,
  custom_our_company.wavi@barbara,
  custom_recent_articles_and_posts.wavi@barbara,
  custom_recentlyreadbooks,1.persona@barbara,
  custom_things_that_not_even_google_knows_about_me.wavi@barbara,
  custom_welcome.wavi@barbara,
  email.wavi@barbara,
  field_order_of_self.wavi@barbara,
  firstname.wavi@barbara,
  followers_of_self.at_follows.wavi@barbara,
  following_by_self.at_follows.wavi@barbara,
  image.wavi@barbara,
  instagram.wavi@barbara,
  lastname.wavi@barbara,
  linkedin.wavi@barbara,
  location.wavi@barbara,
  locationnickname.wavi@barbara,
  phone.wavi@barbara,
  privateaccount.wavi@barbara,
  theme.wavi@barbara,
  theme_color.wavi@barbara,
  twitter.wavi@barbara
]
```
@cconstab

**Comment by murali-shris** [comment]
increased estimate to 3SP since @yahu1031 has some review comments to address

**Comment by yahu1031** [comment]
Issue fixed with #461

**Comment by murali-shris** [comment]
server code released to canary servers

**Comment by gkc** [comment]
@murali-shris @yahu1031  Is it possible to verify the fix on a canary @ sign?
