### ISSUE TITLE
Spike Multiple PKAMS

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#464]
Lead: @kalluriramkumar 

Solution needed to provide access to applications without having to hand over the "master key".. Build on the ideas in the PKAM document ready for development in next sprint

- [x] Initial analysis of the issue
- [x] Brainstorm potential solutions
- [x] Come up with a design that we would like to build on

**Comment by cconstab** [comment]
Solution needed to provide access to applications without having to hand over the "master key".. Build on the ideas in the PKAM document ready for development in next sprint

**Comment by ksanty** [comment]
@cconstab please add Google doc. TY

**Comment by gkc** [comment]
Here's the link to the google doc: https://docs.google.com/document/d/1hp47VLT2ZzrQXonvEGTidEf8rX45bg02OeqDNFKKVYY

**Comment by sitaram-kalluri** [comment]
Complete task 1 and 2 in PR 29(burn down 8 SP). Re-estimating the task with 5 SP for task-3

**Comment by VJag** [comment]
We have analyzed various ideas for:

1. How apps can claim ownership of a namespace
2. How an @ app becomes known
3. Potential use of the secondary server for @ company can potentially solve some of the issues related to publishing and exchanging data with the apps.

Conclusions and next steps:

1. An @ app need not prove that it is a genuine @ app
2. @ app's writing to each other namespace is a separate problem that needs solving
3. All that is left now is to come up with spikes and sub-tasks around Colin's design and implement them in this sprint. This needs to be tracked through a separate task.
