### ISSUE TITLE
Change default log level for prod secondaries to INFO

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#472]
**Describe the bug**
Logging is very verbose by default, and this verbosity has not proven useful in resolving issues in the past

**Expected behavior**
Logging level should be set to WARN by default in prod secondaries

See also #433 for broader context

**Comment by gkc** [comment]
@VJag @murali-shris @kalluriramkumar As part of this work I notice that currently, in the secondary config, we have 'debug' and 'trace' options - only one of which is actually used, and neither of which are used as levels by the dart logger package (which uses FINEST, FINER, INFO, WARN etc)

I propose removing both, and adding a LogLevel param to the config instead, setting it to WARN by default, and modifying logging and config-setting code accordingly.

Does this sound OK to you?

**Comment by VJag** [comment]
@gkc I agree.

**Comment by cpswan** [comment]
As I just noted in #445 I think INFO should be the default.

**Comment by gkc** [comment]
Should be able to close when changes in #476 are rolled out

**Comment by cpswan** [comment]
@gkc how about a Canary release?

**Comment by gkc** [comment]
@cpswan SGTM. Good exercise for me to do it. Can you ping me on chat to let me know the tasks required?

**Comment by murali-shris** [comment]
closing this issue since server code is released to canary
