### ISSUE TITLE
at_onboarding_cli -- An onboarding library for cli/dart code

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#474]
Lead: @cconstab 

**Is your feature request related to a problem? Please describe.**
Currently we have an onboarding widget for Flutter apps but we do not have the same concept for cli apps. This leaves the developer to code their own that causes all manner of bad results.

**Describe the solution you'd like**
A unified way to 

- [x] create/get/use atKeys from the command line. 
- [ ] create keys in TPM/SIM other custom hardware
- [x] save keys safely 

**Describe alternatives you've considered**
The only alternative currently 

1. hardcode PKAM/Encryption keys into code
2. pull keys from atKey files in numerous good/bad ways

**Additional context**
We already have some code with hard coded keys (including mine!)

**Comment by cconstab** [comment]
I am very happy to test this for you with live code when you are ready

**Comment by xavierchanth** [comment]
I'd like to see us using [args](https://pub.dev/packages/args) classes for this cli (and the same for at_cli), so that we can include commands from this cli into at_cli.

**Comment by murali-shris** [comment]
@cconstab 
* Should the at_cli widget have the ability to do perform first time onboarding for an atsign ?
i.e do initial cram, generate key pair etc. ?

**Comment by murali-shris** [comment]
@cconstab @gkc 
@srieteja has checked in version 1 of the library
https://github.com/atsign-foundation/at_libraries/tree/at_onboarding_cli
* path of key file is mentioned in config.yaml
* Pkam auth is done and the app can use atlookup from onboarding service to run verbs against secondary

Next steps:
* Read QR code for CRAM auth and perform pkam keypair, encryption keypair etc., Generate and save key file
* Pass the key file from command line app to onboarding service and remove the atkey file from config.yaml
* Replace atlookup in onboardingservice with atClient for functionalities such as sync, monitor etc.,

**Comment by cpswan** [comment]
For me the MVP of this would be something that takes the atsign and CRAM key (as args) and creates the .atKeys file

**Comment by srieteja** [comment]
As this is a library it might not interact with actual command line args. In the last commit, I have created a class that would store required attributes and which will be passed on to the concerned class. As of now there is functionality to create .atKeysFile but hasn't been tested yet. @cpswan I hope this is equally useful.

**Comment by cpswan** [comment]
@srieteja perhaps the library needs a minimal CLI wrapper that serves as an example of how to invoke it,

**Comment by murali-shris** [comment]
code review, merge and publish pending

**Comment by srieteja** [comment]
The latest commit includes code to activate an atsign which is working as expected. @cpswan you can use this to activate your atsigns now.

**Comment by cpswan** [comment]
Thanks @srieteja 

Can you please update the README to provide a walk through of how this use case (and others) can be satisfied? Hopefully this is as simple as writing down how you tested the code.

**Comment by gkc** [comment]
@srieteja is https://github.com/atsign-foundation/at_libraries/pull/134 ready to merge?

**Comment by srieteja** [comment]
@gkc the functionality is complete, but there are minor complications with the functional tests. It should be good to go very soon.

**Comment by murali-shris** [comment]
reopening the issue until at_onboarding_cli is published

**Comment by murali-shris** [comment]
published at_onboarding_cli 1.0.0
@srieteja for other enhancements related to TPM etc., please create a new task
