### ISSUE TITLE
Enhance e2e test harnesses for server version interoperability

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#491]
Lead: @gkc 

**Describe the bug**
https://github.com/atsign-foundation/apps/issues/495 was only detected in canary environment because our e2e tests only test the current server build - i.e. we don't verify interop between latest version and prod version to pick up backwards and forwards compatibility issues

**Expected behavior**
(Simplified summary) In e2e tests (e.g. client 1 connected to server 1, client 2 connected to server 2) we currently run the tests with server 1 and server 2 both running the current trunk version. We need to _also_ run the tests with
* server 1 running current prod version, server 2 running current trunk version
* server 1 running current trunk version, server 2 running current prod version

i.e. three e2e test runs in total

**Comment by gkc** [comment]
@ksanty FYI I'm adding this unplanned work into the PR29 sprint as a follow-on from https://github.com/atsign-foundation/apps/issues/495

**Comment by gkc** [comment]
No progress in PR29 as some more urgent unplanned work appeared.

**Comment by gkc** [comment]
What needs to get done in order to allow tests to run in parallel

- Spin up 4 additional secondaries on cicd1 and cicd2
- Add to the e2e setup workflow to have the appropriate dockerfile for each secondary 
- Add to the e2e secondaries setup to configure all necessary atSigns on each secondary
- Modify the e2e tests so they can be run with one of three configs
  - against the current two secondaries (both running the PR branch)
  - against two secondaries (secondary 1 running PR branch, secondary 2 running prod branch)
  - against two secondaries (secondary 1 running prod branch, secondary 2 running PR branch)

**Comment by cpswan** [comment]
New cicd3,4,5,6 secondaries created (on same VMs as cicd1,2) - just need to create .atKeys for them, and then extract keys for atDemoData.

**Comment by cpswan** [comment]
I now have .atKeys files for cicd3-6, so I'll extract the keys tomorrow for demodata files
