### ISSUE TITLE
at-length not working

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#495]
**Describe the bug**
After node upgrade to node:16.13.2-alpine from node:12.2.0 
at-length is not working

Linked to https://github.com/atsign-company/at_handle_registrar_web/issues/251 

Node 16 is not allowing to execute command, not even on terminal

at-length is binary to check length of atsign generated by mentioned repo
https://github.com/atsign-company/Colin-snippets/blob/master/at-length/bin/at_length.dart

**To Reproduce**
1. https://github.com/atsign-company/at_handle_registrar_web setup registrar environment and update node to node:16.13.2-alpine is server docker file
2. try to execute at-length on terminal
3. command not found error will come

**Expected behavior**
Should return length of atsign

**Screenshots**
![image](https://user-images.githubusercontent.com/61007675/152339575-f68fa68a-d753-44b7-b4a4-e5729854927a.png)

**Comment by cpswan** [comment]
@athandle how is it not working? Can you please fill out our usual bug report template type stuff so that we have the proper context for what should be happening, what is happening etc.

**Comment by athandle** [comment]
@cpswan updated

**Comment by cpswan** [comment]
@athandle what are you doing to start the container and get the shell from the screenshot above?

**Comment by gkc** [comment]
@athandle also, which version of docker are you running?

**Comment by kumarnarendra701** [comment]
@gkc - We are running this container on K8 pods, Actually earlier we were using "FROM node:12.2.0" in Dockerfile and upgraded to "FROM node:16.13.2-alpine" and after this upgrade, this binary is not working. So no changes at the docker daemon version.

Old Dockerfile-
```
FROM node:12.2.0
RUN mkdir /opt/app-be
RUN mkdir /var/ssl
RUN mkdir /var/env
COPY ./at-length /usr/local/bin/
RUN chmod 755 /usr/local/bin/at-length
WORKDIR /opt/app-be
COPY . /opt/app-be
RUN ln -s /var/env/.env .env
RUN npm install --unsafe-perm
EXPOSE 443
CMD [ "npm", "run", "start:prod"]
```

New Dockerfile -
```
FROM node:16.13.2-alpine
RUN mkdir /opt/app-be
RUN mkdir /var/ssl
RUN mkdir /var/env
COPY ./at-length /usr/local/bin/
RUN chmod 755 /usr/local/bin/at-length
WORKDIR /opt/app-be
COPY . /opt/app-be
RUN ln -s /var/env/.env .env
RUN npm install --unsafe-perm
EXPOSE 443
CMD [ "npm", "run", "start:prod"]
```

**Comment by athandle** [comment]
@cpswan screenshot is from my local docker

**Comment by cpswan** [comment]
@athandle I was asking how you got to that screenshot on your local docker. I've tried the obvious stuff, and my container isn't staying up, so even when I get a shell on it the container shuts down before I have a chance to try anything.

**Comment by athandle** [comment]
@cpswan  I have older version of docker I suppose. 
Anyways we were able to resolve the issue, thanks Colin, Gary
I will take help of Narendra to setup Dockerfile
Source: https://github.com/CargoSense/dart_sass/blob/main/README.md#compatibility-with-alpine-linux-mix-sass-default-exited-with-2

Mentioned below are notes from call
uninstall glibc 
uninstall glibccompat
//to set env variable, check if we have better way
export LD_LIBRARY_PATH=/usr/glibc-compat/lib/

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk
RUN apk add glibc-2.34-r0.apk

**Comment by cpswan** [comment]
@athandle or maybe just use node:16-slim if Alpine is problematic

**Comment by gkc** [comment]
Sage advice from https://medium.com/swlh/alpine-slim-stretch-buster-jessie-bullseye-bookworm-what-are-the-differences-in-docker-62171ed4531d

> For some projects that I have time to test thoroughly, and have extreme space constraints, I will use the Alpine
> images. But be aware that this can lead to longer build times and obscure bugs. If you are having trouble porting 
> your docker containers to new environments, or something breaks as you add new packages, it may be because 
> of the Alpine image.

**Comment by gkc** [comment]
@athandle Has the dockerfile been updated, is functionality now working, can this ticket be closed?
