### ISSUE TITLE
A failed lookup hangs the TCP session and this builds up to a DoS on the secondary

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#501]
Lead: @cconstab 

**Describe the bug**
When using the at_find_api to lookup a value if that value exists everything works. But if that value does not exist sessions to the secondary do not close and eventually the secondary starts rejecting connections (too many sessions)

**To Reproduce**
1. make a call to an @sign via the at_find_api to lookup a 'key' that does not exist
 `https://wavi.ng/api?atp=snackbarsforever.fourballcorporate9@ai6bh' - snackbarsforever.fourballcorporate9 does not exist !
2. AFter 20 + requests the secondary becomes unavailable
3. Connecting to the secondary using openssl the message that too many sessions 
```
read R BLOCK
error:AT0012-Inbound connection limit exceeded
read:errno=0
```

**Expected behavior**
If the value being looked up  this should not hang a TCP session perhaps that session should get dropped.

This is likely an at_lookup issue but could be in the at_find_api perhaps ?

**Comment by gkc** [comment]
Moved to this repo as the problems diagnosed to date as part of investigating this issue are in the at_secondary_server codebase. There may be an issue with how at_lookup handles `error:` responses, if so then will create another issue in the at_libraries repo

**Comment by gkc** [comment]
Remaining work for PR #504 : Write e2e tests (positive plookip, negative plookup) to verify behaviour. Write unit test to verify timeout behaviour. Estimate 2 SP

Work for other issues uncovered via this ticket will be in #503
