### ISSUE TITLE
Potential bug in outbound_message_listener ?

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#514]
**Describe the bug**
At [line 54 in outbound_message_listener.dart](https://github.com/atsign-foundation/at_server/blob/trunk/at_secondary/at_secondary_server/lib/src/connection/outbound/outbound_message_listener.dart#L54) is this code 
  `_queue.addFirst(result);` 
which adds to the front of the queue instead of the end. This seems wrong, even if normal behaviour is that the queue will only ever have one item in it, and I would expect it to be 
  `_queue.add(result);` 

The fix is easy but I wanted to ask if there's a reason for it being this way (it's been this way since initial commit)

**Comment by gkc** [comment]
PS Same line of code exists in at_lookup's outbound_message_listener

**Comment by gkc** [comment]
The fixes here are trivial but require all tests to be run and possibly some new ones added

**Comment by murali-shris** [comment]
@gkc we use addFirst and removeFirst..
remove doesn't specifically state whether it removes element from end of the queue. Hence I used addFirst/removeFirst instead of just add/remove.
/// Remove a single instance of [value] from the queue.
  ///
  /// Returns `true` if a value was removed, or `false` if the queue
  /// contained no element equal to [value].
  bool remove(Object? value);

**Comment by gkc** [comment]
addFirst adds items to the beginning of the queue
removeFirst removes from the beginning of the queue

So if we add two items, response 1 and response 2, they would actually be
consumed in the order 'response 2' and 'response 1'

Hence I think addFirst is incorrect

addFirst and removeFirst equates to a "Last In, First Out" queue
whereas what we need is a "First in, First Out" queue

**Comment by murali-shris** [comment]
> addFirst adds items to the beginning of the queue removeFirst removes from the beginning of the queue So if we add two items, response 1 and response 2, they would actually be consumed in the order 'response 2' and 'response 1' Hence I think addFirst is incorrect addFirst and removeFirst equates to a "Last In, First Out" queue whereas what we need is a "First in, First Out" queue Message ID: ***@***.***>
> […](#)

Got it Gary..Thanks for the clarification

**Comment by murali-shris** [comment]
published at_lookup 3.0.10 and at_client 3.0.11 with the fix
server changes merged to trunk

**Comment by murali-shris** [comment]
> published at_lookup 3.0.10 and at_client 3.0.11 with the fix server changes merged to trunk

@gkc can we close this issue?

**Comment by gkc** [comment]
Yep LGTM
