### ISSUE TITLE
Update at_server_spec

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_server#521]
Update Github documentation for to be [unlisted pub.dev package at_server_spec](https://github.com/atsign-foundation/at_server/issues/450).  

Review [at_server_spec](https://github.com/atsign-foundation/at_server/tree/trunk/at_server_spec) readme.md, changelog.md and look for standard archetype template updates to make current.  Repo will remain active even though it will be unlisted on Pub.dev.

- [ ]  Review for current logo
- [ ] Add badging
- [ ]  Does text body map to current standard archetype for consistency (dependency on [archetype update](https://github.com/atsign-foundation/at_client_sdk/issues/398))
- [ ] Update readme.md
- [ ] Update changelog.md

**Comment by xavierchanth** [comment]
Closed by @cpswan in [at_client_sdk#398](https://github.com/atsign-foundation/at_client_sdk/issues/398).
