### ISSUE TITLE
update hive version

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#544]
latest version of hive has partly addressed hive crash
https://pub.dev/packages/hive/changelog

Upgrade persistence to latest version of hive

**Comment by murali-shris** [comment]
executed the below snippet using hive 2.0.4
import 'package:hive/hive.dart';

void main() async {
  Hive.init('test/upgrade');
  var box = await Hive.openBox('sample.hive');
  await box.put('alice🛠_1', 1);
  await box.put('alice🛠_2', 2);
  await box.put('alice🛠_3', 3);
  await box.put('alice🛠_4', 4);
  await box.put('alice🛠_5', 5);
  box.keys.forEach((key) async {
    print(await box.get(key));
  });
}

Updated the hive version to 2.1.0 and re-ran the same code snippet. Ran into the below exception
Unhandled exception:
FormatException: Missing extension byte (at offset 7)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      BinaryReaderImpl.readKey (package:hive/src/binary/binary_reader_impl.dart:224:39)
#3      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:269:19)
#4      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
#5      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
<asynchronous suspension>
#6      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11)
<asynchronous suspension>
#7      HiveImpl._openBox (package:hive/src/hive_impl.dart:110:9)
<asynchronous suspension>
#8      HiveImpl.openBox (package:hive/src/hive_impl.dart:140:12)
<asynchronous suspension>
#9      main (package:test_hive/src/test_hive_upgrade.dart:5:13)
<asynchronous suspension>

**Comment by gkc** [comment]
How about version 2.0.6? (Which contains the fix for the
crash-during-crash-recovery problem)

**Comment by murali-shris** [comment]
> How about version 2.0.6? (Which contains the fix for the crash-during-crash-recovery problem)
> […](#)
> Message ID: ***@***.***>

Same behaviour while upgrading from 2.0.6 to 2.1.0

**Comment by murali-shris** [comment]
in persistence layer we encode the key using utf7
 String prepareKey(String key) {
    key = key.trim().toLowerCase().replaceAll(' ', '');
    return Utf7.encode(key);
  }
  below code snippet works fine with 2.0.4 and after  upgrade to 2.1.0
   Hive.init('test/upgrade');
  var box = await Hive.openBox('sample.hive');
  await box.put(Utf7.encode('alice🛠_1'), 1);
  await box.put(Utf7.encode('alice🛠_2'), 2);
  await box.put(Utf7.encode('alice🛠_3'), 3);
  await box.put(Utf7.encode('alice🛠_4'), 4);
  await box.put(Utf7.encode('alice🛠_5'), 5);
  box.keys.forEach((key) async {
    print(await box.get(key));
  });

**Comment by gkc** [comment]
Great, so OK to proceed with fuller testing?

PS to my mind it's not (at least, not now) worth the effort to do a
migration from utf7-encoded to unicode - as this would require us to fully
rebuild the data stores for no particular gain. What do you think?

**Comment by murali-shris** [comment]
> Great, so OK to proceed with fuller testing? PS to my mind it's not (at least, not now) worth the effort to do a migration from utf7-encoded to unicode - as this would require us to fully rebuild the data stores for no particular gain. What do you think?


Right Gary..We can leave the utf7 encoding as it is..

**Comment by murali-shris** [comment]
changes merged to trunk
https://github.com/atsign-foundation/at_server/pull/619
https://github.com/atsign-foundation/at_server/pull/620

**Comment by gkc** [comment]
(Weird: Had to re-open and re-close the issue in order for its status to update on the project board, refreshing the project board still showed issue as open even though it was closed)
