### ISSUE TITLE
Create swarm0002 cluster

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#578]
**Describe the solution you'd like**

Spin up a new production Docker Swarm cluster similar to swarm0001

**Describe alternatives you've considered**

We could repave hornet, but probably better to tear it down

**Comment by cpswan** [comment]
Cluster created with 3 managers and 3 workers (worker pool can be expanded later)

Still needs:

- [x]  Shepherd
- [x] Seccheck
- [x] Cron jobs

**Comment by cpswan** [comment]
@kumarnarendra701 can you please take care of seccheck and cron jobs (e.g. cert renewal) on swarm0002

**Comment by kumarnarendra701** [comment]
@cpswan - Added below cronjobs.
1. seccheck
2. certcheck
3. desscheck(It's throwing dess.text: No such file or directory)
4. SSL renewal

**Comment by gkc** [comment]
Looks like this ticket is complete ... can it be closed?
