### ISSUE TITLE
Renew staging environment

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#582]
**Is your feature request related to a problem? Please describe.**

Staging is presently out of sync with prod on:

- [x] DNS - still using names that suggest Digital Ocean even after migration to GCP
- [x] Base OS - still using Ubuntu rather than flatcar

**Describe the solution you'd like**

- [x] Create a new staging Docker Swarm (similar to swarm0001)
- [x] Migrate secondaries
- [x] Turn down Buzz

**Describe alternatives you've considered**

Repave Buzz with Flatcar Nodes.

**Comment by cpswan** [comment]
staging0001 swarm is now up:

01:02 manager nodes (Ubuntu)
03:06 worker nodes (Flatcar)

New registry - reg.swarm0001.atsign.zone

Monitoring configured as a global service

Shepherd running

Migration of the first ~100+ secondaries in progress. Will start batches of 600/day.

**Comment by cpswan** [comment]
~50 secondaries still running on buzz

Next step is for new secondaries to be created on staging0001 - @athandle can you please make the change.

**Comment by athandle** [comment]
@cpswan @kumarnarendra701 I changed the settings but there is an error, secondaries are not starting

**Comment by cpswan** [comment]
What is the error?

**Comment by athandle** [comment]
@kumarnarendra701  is looking into it, @kumarnarendra701  can you please share

**Comment by kumarnarendra701** [comment]
@cpswan @athandle  - Below are the changes to run secondaries on staging0001.
1. Fixed DO connectivity.
2. Changes in docker-compose.yml
    image: reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env -> image: **reg.staging0001.atsign.zone**/atsigncompany/secondary:dev_env

    - "/etc/letsencrypt/live/UUID.SWARM.do-sf2.atsign.zone:/atsign/certs" - >     "/etc/letsencrypt/live/UUID.SWARM.**atsign.zone**:/atsign/certs"
   
Please let me know if you see any issues with this.

Note - To run this script in Buzz, we need to replace old docker-compose.yml

**Comment by athandle** [comment]
32 SSL s added for new domain

**Comment by cpswan** [comment]
The last few secondaries on buzz have been deleted (if they were orphaned in the registry) or migrated.

Still need to set up seccheck on staging0001

**Comment by kumarnarendra701** [comment]
@cpswan - Added seccheck on staging0001.

**Comment by cpswan** [comment]
Last remaining docker services (shepherd and registry) removed from buzz cluster and buzz VMs stopped.

**Comment by cpswan** [comment]
Buzz VMs have been deleted
