### ISSUE TITLE
Dynamically adjust server config to facilitate testing

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#588]
We need ability - intended for use in test environments **_only_** - to dynamically adjust server config from an authenticated client. See https://github.com/atsign-foundation/at_server/issues/542 for a specific example of a test that is currently effectively impossible to implement

Implementation could be via a new verb, 'set:param1=val1,param2=val2,param3=val3' where parameter could be server-wide (possibly indicated by prefix of 'server.' to param name) or for just this connection (possibly indicated by prefix of 'connection.' to param name). In server code, request parameters could be handled by having the config verb handler 'store' those parameters on the connection handler, then individual verb handlers could pick up those params when they are executing.

Initial scope :
* Add a verb (e.g. 'set') which requires user authentication to execute
* For each specific config parameter required by https://github.com/atsign-foundation/at_server/issues/542 (inbound_connection_limit, compactionJobRun)
  * Find its usages and ensure that if it is changed then the changed value will be used
  * Add explicit support to the verb handler for just that config parameter
* Add a server config parameter which by default has the 'set' verb disabled for use; and let's specifically enable it for the testing servers

**Comment by gkc** [comment]
No progress in sprint PR33 due to unplanned higher priority work (identifying and analysing bugs in server notification subsystem - https://github.com/atsign-foundation/at_server/issues/617 and https://github.com/atsign-foundation/at_server/issues/621).

**Comment by gkc** [comment]
Pulling in to PR36 - time-boxing to 3 SP to support just what is needed by #542

**Comment by gkc** [comment]
Work:
* Add a verb (e.g. 'set') which requires user authentication to execute
* For each specific config parameter required by #542 (inbound_connection_limit, compactionJobRun)
  * Find its usages and ensure that if it is changed then the changed value will be used
  * Add explicit support to the verb handler for just that config parameter
* Add a server config parameter which by default has the 'set' verb **disabled** for use; and let's specifically enable it for the testing servers

**Comment by VJag** [comment]
@srieteja can you please take up this.

**Comment by gkc** [comment]
Changing priority to high as Purnima's been blocked by this for a while now

**Comment by srieteja** [comment]
Could not do much work on this in the current sprint, I could manage to only complete a basic implementation. This shall be carried on to the next sprint.

**Comment by srieteja** [comment]
Implementation and testing completed. Working on a failing test due to unreachable secondary.

**Comment by srieteja** [comment]
Implementation and tests are done. The feature has been tested and is working as expected. Figuring out how to set env variables for the tests so that they can pass.
