### ISSUE TITLE
Enhance notifications to have same notification ID on sender and receiver side.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#592]
**Is your feature request related to a problem? Please describe.**
At the moment, the notification id is not same on the sender side and receiver side when notification is shared. This becomes difficult to correlate the notification status.

**Describe the solution you'd like**
Enhance the notification to use the same id across the notification life cycle.

**Comment by gkc** [comment]
Covered by #546 . Closing this one.
