### ISSUE TITLE
Scan returns expired keys

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#600]
**Describe the bug**
The scan verb returns the expired keys in the server and SDK.

**To Reproduce**
1. Create a key with TTL.
2. Once the key is expired (TTL met), run scan verb
3. The expired key is also returned.

**Expected behavior**
Scan should not return the expired keys.

**Additional context**
@VJag and myself had a discussion on this and below are the approaches:

Approach  - 1
------------------
1. Return a map from the key store.
2. Iterate on the map; For each key, on its metadata verify if key is expired.

Approach - 2
------------------
1. Maintain an internal data structure to cache the key and its expired time.

Approach - 3
------------------
1. Add a plugin to hive keystore which will not return the keys that are expired.

**Comment by srieteja** [comment]
An in-memory metadata cache has been implemented that will be used to compare the metadata(expiresAt attribute) of all the keys with the present time and only unexpired keys will be returned to the scan verb handler. This comparison happens on-demand and the use of a cache makes it relatively faster. Testing the implementation in process.

**Comment by srieteja** [comment]
Implementation and testing completed. Ready to merge
