### ISSUE TITLE
Enhance NSS to delete notification using notification id.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#610]
**Is your feature request related to a problem? Please describe.**
Enhance the NSS to delete notifications in keystore before expiry to keep the secondary thin. Provide a delete method that takes notification id as input and removes the notification against the ID from the keystore.

**Comment by gkc** [comment]
Covered by https://github.com/atsign-foundation/at_server/issues/546 ; closing this one
