### ISSUE TITLE
Add alerts for 1/0 containers

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#622]
Describe the bug
Add checks for 1/0 containers in a daily check.

**Comment by athandle** [comment]
@cconstab @cpswan  Created a similar behavior by deleting directory on test secondary and I can see that seccheck job sending alerts to for problematic secondary on gchat channel.

root@staging0001-01:~# docker service ls | grep 58d7ae57-08bb-5053-868b-91794734fedd
67roiarn658n   58d7ae57-08bb-5053-868b-91794734fedd_secondary   replicated   0/1        reg.staging0001.atsign.zone/atsigncompany/secondary:dev_env      *:12490->12490/tcp

Alerts - Of the 1 these are the first few effected @Signs, @test_ashish7 (12490),

Above comment is from @kumarnarendra701 

https://github.com/atsign-company/shepherd/issues/6#issuecomment-1091754532

**Comment by kumarnarendra701** [comment]
@cpswan @cconstab - Can we close this because we are getting alerts for the above scenario.

**Comment by cpswan** [comment]
Before we close I just want to check if @cconstab meant 1/0 or 0/1 (as it may be possible to have a situation where there's a container stuck running when the requested scale is 0)?

**Comment by cconstab** [comment]
Original intent was 1/0 i.e things that should be running but are not. But I would also like to see 0/0 i.e things that have been scaled down and left in the docker
 service

**Comment by cpswan** [comment]
@cconstab I think that original ask should have been 0/1 (0 running of 1 demanded) rather than 1/0 (1 running of 0 demanded) but keeping track of the 0/0s is useful too.

**Comment by kumarnarendra701** [comment]
@cpswan - Please review the below PR.
https://github.com/atsign-foundation/seccheck/pull/12

**Comment by athandle** [comment]
@cpswan can we close this?
