### ISSUE TITLE
Add SSL validation in create secondary script

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#625]
**Is your feature request related to a problem? Please describe.**
Secondaries are created without SSL

**Describe the solution you'd like**
Add a check if SSL exists and valid

**Comment by kumarnarendra701** [comment]
@cpswan - Made changes and raised PR for review.
https://github.com/atsign-company/secondaries-scripts/pull/36

**Comment by kumarnarendra701** [comment]
@cpswan @athandle  - Script deployed to production. Now we can close this ticket.
