### ISSUE TITLE
Implement unit tests to prevent regression of the notifications bug fixed by #621

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#633]
**Describe the bug**
See #621 for full detail. TL;DR, that pull request fixed this issue:
<blockquote>
In [this method](https://github.com/atsign-foundation/at_server/blob/883623b080b5247f5b6528edad88fe112d8639ef/at_secondary/at_secondary_server/lib/src/notification/resource_manager.dart#L90)

* if an exception happens while sending a notification
* and the iterator has other notifications not yet processed
* then those other notifications are not added to the errorList
* and therefore they are not re-enqueued
</blockquote>

**Expected behaviour**
The bug has been fixed, but we need a set of unit tests which cover this case, to prevent regression in future. The Notification ResourceManager is complex but we should be able to implement the required unit tests by allowing dependencies to be injected into ResourceManager, and injecting mocks of those dependencies at test time.

**Additional context**
As mentioned above, the Notifications ResourceManager has complex behaviour and lots of complex dependencies. This is likely 2-3 days of work to cover just this particular scenario - but that work will also provide the foundation that will allow us to cover all of the Notifications ResourceManager's error handling with unit tests - which is much to be desired, as notifications need to be rock solid.

**Comment by purnimavenkatasubbu** [comment]
Had a discussion with @VJag about the scenarios that need to be handled. Following are the scenarios discussed that needs to be covered in tests.

- [ ]  If there are a couple of notifications, Out of which a notification is invalid(server is down) - The remaining valid notifications in the queue should be delivered 
- [ ] Within the retry time, if the server is back up and running, then the notification which was invalid should be delivered

**Comment by VJag** [comment]
Scenario 1 is related to the re-queueing logic

**Comment by purnimavenkatasubbu** [comment]
Had a session with @VJag, Where we wrote some sample implementation to understand how mocktail works, 

[mocktail_sample.zip](https://github.com/atsign-foundation/at_server/files/8552559/mocktail_sample.zip)

**Comment by purnimavenkatasubbu** [comment]
Added initial unit tests for the prepareNotificationkey() and pushed the changes to the [branch](https://github.com/atsign-foundation/at_server/tree/unit_tests%23633)

**Comment by purnimavenkatasubbu** [comment]
Added the tests for the sendNotifications() to the [branch](https://github.com/atsign-foundation/at_server/tree/resource_manager_test) . Blocked with an issue that @murali-shris is looking at. Hence moving the issue to the next sprint.

**Comment by murali-shris** [comment]
> Added the tests for the sendNotifications() to the [branch](https://github.com/atsign-foundation/at_server/tree/resource_manager_test) . Blocked with an issue that @murali-shris is looking at. Hence moving the issue to the next sprint.

Test is working now..I can see notifications being added to the queue.

**Comment by purnimavenkatasubbu** [comment]
Raised the following [PR](https://github.com/atsign-foundation/at_server/pull/703) for unit tests

**Comment by purnimavenkatasubbu** [comment]
As the PR is merged to trunk. Can we close this issue @gkc

**Comment by gkc** [comment]
Yep, thanks Purnima
