### ISSUE TITLE
New swarm0002 not working

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#639]
- [x] SSL generation script is giving success
- [x] Secondary not creating

**Comment by cpswan** [comment]
Certs weren't being created because the NS records pointing to Digital Ocean were missing from Namecheap. Now fixed.

**Comment by athandle** [comment]
@cpswan we figured that yesterday but my problem is shell was giving me a success because of which I was marking this uuid as valid SSL can we return error in such scenarios so that I don't create corrupted entries

**Comment by kumarnarendra701** [comment]
@cpswan @athandle - Performed below steps on Swarm0002-02.
1. Mount letsencrypt directory.
2. Setup env file for secondary.
3. Setup Digit ocean authentication
4. Debug NS record issue.

Now we can close this ticket.
