### ISSUE TITLE
Clear orphan SSLs

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#642]
Remove orphan SSLs directory and certificates

**Comment by kumarnarendra701** [comment]
@athandle @cpswan - Script is almost done and working on handling for pool UUID(getting from API).

**Comment by kumarnarendra701** [comment]
@cpswan - Please review the below PR and let me know your feedback.
https://github.com/atsign-company/secondaries-scripts/pull/43/files

**Comment by kumarnarendra701** [comment]
@cpswan  @athandle - I have rollout script for all prod swarms and enabled cronjob.

**Comment by athandle** [comment]
@cpswan  can we close this?

**Comment by cpswan** [comment]
#43 needs to be merged, and please also confirm that the code has been deployed. Once those things are done this can be closed.
