### ISSUE TITLE
Remove print statements and `_debug` to false in production code

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#643]
A number of our dart libraries have print statements and _debug code that needs to be removed or at least set to false so apps built against the SDK do not have odd print statements inherited into client code.

Ideally useful debug / print statements could be migrated to using the _logger methods which is very useful to us and developers.

Some examples :- 
hive_manger.dart  line 100                        ` if (_debug) print('AtServer.getHiveSecretFromFile file found');`

storage_manger.dart line 28                        `print('initializing storage');`

**Comment by murali-shris** [comment]
published the below packages after removing the print statements
at_persistence_secondary_server 3.0.24
 at_commons 3.0.14
 at_lookup 3.0.20
 at_client 3.0.20
 @cconstab please verify the fix in your app

**Comment by cconstab** [comment]
Will do thanks !

**Comment by cconstab** [comment]
@murali-shris thanks so much.. This now works as I had hoped..

```
cconstab@cally:~/sshnoports$ $(dart run bin/sshnp.dart  -f @lostblue64 -t @blueamateurbinding  --host cally.lan  -l 2001 -d iot)
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue 26 Apr 2022 04:57:30 AM UTC

  System load:  0.0                Processes:              144
  Usage of /:   22.3% of 31.37GB   Users logged in:        1
  Memory usage: 44%                IPv4 address for ens18: 192.168.1.64
  Swap usage:   5%

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

3 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


*** System restart required ***
Last login: Tue Apr 26 04:50:57 2022 from 192.168.1.52
cconstab@iot:~$ 
cconstab@iot:~$ 
cconstab@iot:~$ 
cconstab@iot:~$ 
cconstab@iot:~$ ls
Colin-snippets  psshd  sshnoports
cconstab@iot:~$ 
```
