### ISSUE TITLE
stats not being written by server to monitor connections with frequent heartbeats

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#646]
**Describe the bug**
If the client-side monitor heartbeat interval is too short, stats are no longer being delivered to the client, because the server-side stats notification service decides to write the stats to the monitor only if it is at least 15 seconds since the connection was last written to by the server

There is a workaround available which is to set the monitor heartbeat interval to a larger value on the client. Current default is 10 seconds; changing it to a much higher value (e.g. 60 seconds) will limit the impact of this bug while still retaining the value of the monitor heartbeat.

**Expected behavior**
Instead of checking when the monitor connection was last accessed (currently this means the last time it was written to by the server), the stats_notification_service should instead keep track of when the stats were last sent, and only send again if it's been more than 15 seconds since the last time the stats were sent

**Comment by gkc** [comment]
@kalluriramkumar let's take this up in this sprint. I think the fix is very simple as it is localized in stats_notification_service.dart

**Comment by murali-shris** [comment]
@gkc change released to canary server. Please verify the fix

**Comment by murali-shris** [comment]
@gkc change released to canary server - version 3.0.15b . Please verify the fix

**Comment by gkc** [comment]
Verified
