### ISSUE TITLE
Stand up swarm0003

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#652]
- [x] managers 01-03
- [x] workers 04-06
- [x] Digital Ocean DNS zone with CAA records
- [x] Namecheap NS records
- [x] Load balancer on NS1
- [x] Docker login and pull images
- [x] GCP custom monitoring
- [x] /root/.env file
- [x] Shepherd
- [x] `doctl auth init`
- [x] Seccheck
- [x] Cron jobs for cert renewal

**Comment by cpswan** [comment]
@athandle @kumarnarendra701 over to you for shakedown

**Comment by kumarnarendra701** [comment]
@cpswan - Verified all settings and creation of secondary.
