### ISSUE TITLE
Stand up swarm0004

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#653]
- [x] managers 01-03
- [x] workers 04-06
- [x] Digital Ocean DNS zone with CAA records
- [x] Namecheap NS records
- [x] Load balancer on NS1
- [x] Docker login and pull images
- [x] GCP custom monitoring
- [x] /root/.env file
- [x] Shepherd
- [x] `doctl auth init`
- [x] Seccheck
- [x] Cron jobs for cert renewal

**Comment by cpswan** [comment]
@athandle @kumarnarendra701 another one ready for shakedown over the weekend

**Comment by kumarnarendra701** [comment]
@cpswan - Verified all settings and creation of secondary.
Moved "seccheck" binaries and crontab from root to seccheck user.

**Comment by cpswan** [comment]
@kumarnarendra701 we decided to run seccheck as root (as for a non root user it needs to be part of the docker group, which is effectively root anyway), and also it keeps all the cron jobs in one place. But you weren't to know that.
