### ISSUE TITLE
Use NFS for .docker/config.json

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#662]
**Is your feature request related to a problem? Please describe.**

At the moment secondaries need to use `docker login` to connect to registries.

**Describe the solution you'd like**

Place config.json on NFS and create a symlink to it
- [x] staging
- [x] canary
- [x] swarm0004
- [x] swarm0003
- [x] swarm0002
- [x] swarm0001

**Comment by cpswan** [comment]
I wasn't able to get started on this during PR36

**Comment by athandle** [comment]
not able to work on this sprint moving to PR46

**Comment by kumarnarendra701** [comment]
@cpswan - I have moved the .docker directory to /gluster/@/.docker and created a symlink on /root for all swarm nodes.

![image](https://user-images.githubusercontent.com/29299536/191911296-b71a9f95-ce90-4b0e-9952-54ac8e50b16b.png)

Please review and let me know if there's anything I need to do.

**Comment by cpswan** [comment]
@kumarnarendra701 have you restarted any Flatcar nodes to ensure that the symlink is persistent across reboots?

We also have work to do on the build scripts to put the symlink in place for new nodes.

**Comment by kumarnarendra701** [comment]
@cpswan - I have verified this and symlink is available after reboot. Where I'll get the build script? so that I'll update it for docker config.

**Comment by kumarnarendra701** [comment]
@cpswan - Added symlink for docker config in build scripts. Please review and let me know if any changes are required.

https://github.com/atsign-company/secondaries-scripts/pull/58

**Comment by cpswan** [comment]
Some more testing needed. Bumping to PR47 and reducing to 2SP.

**Comment by cpswan** [comment]
Moving to PR48

**Comment by kumarnarendra701** [comment]
@cpswan - I have tested this and working as expected and testing took lot of time because when I was generating the ign file and version in the ign file was "version":"2.2.0" and with this version VM was not getting up so after debugging, I found this version difference in new or old ign file and when I changed it to "2.3.0" then it's started working.
