### ISSUE TITLE
Refactor seccheck to run from NFS rather than a home directory

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#663]
**Is your feature request related to a problem? Please describe.**
This should simplify the installation of seccheck so that it can be made part of an automated install

**Describe the solution you'd like**
Run seccheck from NFS, and make use of [converged .env/.ENV](https://github.com/atsign-foundation/seccheck/issues/10) files to minimise touchpoints for cluster specific config.

**Comment by cpswan** [comment]
I wasn't able to get started on this during PR36

**Comment by kumarnarendra701** [comment]
@cpswan - After the below PR changes, moved seccheck script inside "/gluster/@/api/seccheck" and added the below cronjob from the root.

```
##############################################
## To run seccheck scripts
##############################################
*/15 * * * * /gluster/@/api/seccheck/seccheck >/dev/null 2>&1
*/15 * * * * /gluster/@/api/seccheck/desscheck >/dev/null 2>&1
0 23 * * * /gluster/@/api/seccheck/certcheck.sh >/dev/null 2>&1
15 23 * * * /gluster/@/api/seccheck/secscan >/dev/null 2>&1
30 23 * * * /gluster/@/api/seccheck/inforeport >/dev/null 2>&1
0 */6 * * * /gluster/@/api/seccheck/secstatecheck-0 >/dev/null 2>&1
0 */6 * * * /gluster/@/api/seccheck/secstatecheck-1 >/dev/null 2>&1
```
