### ISSUE TITLE
ttl value is being stored to ttln in atNotification

### ISSUE THREAD

**Issue by purnimavenkatasubbu** [atsign-foundation/at_server#667]
**Describe the bug**
The ttl value is being stored to ttln 

**To Reproduce**
1. First Pass the value of ttl
2. Then run the [unit test](https://github.com/atsign-foundation/at_server/commit/089556efd53eff7fd4a0509dacd16d4fdb6bdfb0)

**Expected behavior**
ttl value should be added to ttl instead of ttln

**Screenshots**
![Screenshot from 2022-05-04 12-29-10](https://user-images.githubusercontent.com/43639593/166635399-f69777c2-74eb-4232-9ad8-bb9c2e4e4256.png)

**Smartphone (please complete the following information):**

**Were you using an @‎application when the bug was found?**
  

**Additional context**

**Comment by gkc** [comment]
This seems bad. Setting priority High

**Comment by murali-shris** [comment]
@purnimavenkatasubbu there are two values on the notify verb
ttl - expiry of the key
ttln - expiry of the notification
ttl set on the notificationBuilder will correspond to ttln on the notify verb.

**Comment by purnimavenkatasubbu** [comment]
Oh ok. As it is expected behavior I'll close the bug.
