### ISSUE TITLE
Mechanism to request and deliver registration API key

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_server#686]
Requirement:
What we have today is a single API key for every @app invoking the registration API. For a better developer experience, we need a way to request the API key using the registered email.

In order to facilitate this we have to do the following:

- After the user logs in to the atsign website he/she should be able to request the API key. API key should be delivered to the registered email id
(TBD: Showing it on the website is not a bad idea too as the user has logged in already)
- There should be a way to request more than one API key (Probably more than one @app being developed) 

Rate limiting and showing the number of activations done using a given API key are outside the scope of this ticket.

**Comment by athandle** [comment]
Ticket linked to https://github.com/atsign-company/at_handle_registrar_web/issues/211 
@gkc @nickelskevin @cconstab @cpswan please confirm if we can go with the approach

@VJag minor correction all apps which are live and who requested API key are using separate API keys.

**Comment by gkc** [comment]
See also https://github.com/atsign-foundation/at_widgets/issues/287 which we can make progress on once this issue is resolved

**Comment by athandle** [comment]
@gkc if we can go with the description of this ticket(#686 or https://github.com/atsign-company/at_handle_registrar_web/issues/211) then we don't https://github.com/atsign-foundation/at_widgets/issues/287 
I can take care of everything

**Comment by gkc** [comment]
@athandle Sounds good - thanks!

**Comment by ksanty** [comment]
Issue is being worked on the web registrar board - https://github.com/atsign-company/at_handle_registrar_web/issues/211

**Comment by gkc** [comment]
Lots of progress during PR37. A few things left to do - see https://github.com/atsign-company/at_handle_registrar_web/issues/211

**Comment by athandle** [comment]
@gkc  https://github.com/atsign-company/at_handle_registrar_web/issues/211 is also deployed on dev. Minor UI changes are pending.

**Comment by athandle** [comment]
The feature is deployed on production
@sachins-geekyants we have to update onboarding documentation to get API key
@tinashe404 @cconstab  we have to discuss info text

**Comment by athandle** [comment]
closing this ticket as task is done only documentation is pending created a new ticket for the same
https://github.com/atsign-foundation/at_server/issues/797
