### ISSUE TITLE
Pass client version in the from verb

### ISSUE THREAD

**Issue by VJag** [atsign-foundation/at_server#691]
A client should be able to pass the version to the server so that the server can respond in a backward-compatible way. "from" verb seems to be a good place to pass this information. This task requires the following changes:
 - Sever should expose an additional parameter in the from verb to accept the client version
- Clients to pass this information when connecting to the server 

- [x] Implement changes to at_commons
- [x] Implement changes in at_server
- [x] Merge and publish at_commons
- [x] Merge changes in at_server

**Comment by sitaram-kalluri** [comment]
The implementation is completed and changes are available in 

at_commons: https://github.com/atsign-foundation/at_tools/tree/add_version_to_from_verb

at_server: https://github.com/atsign-foundation/at_server/tree/add_version_to_from_verb

Spent 3 SP on at_server and at_commons. Carry forwarding to raise and merge changes to trunk.

**Comment by sitaram-kalluri** [comment]
The changes are merged to trunk. Awaiting for the server changes to be released to prod before publishing the packages.

**Comment by gkc** [comment]
Great! We can now make progress on #850 to which we can add a check as to whether the client is on a version which can cope with JSON-encoded error responses.

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client: 3.0.38
