### ISSUE TITLE
Staging secondaries unable to communicate with each other

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#697]
**Describe the bug**
Secondaries in the staging environment are not able to communicate with other secondaries in the staging environment; It's because the staging environment is injecting the rootServerUrl via environment, but instead of "root.atsign.wtf" it is injecting an empty string

```
gary@staging0001-01:~$ sudo docker service inspect 4f3f81d4-4825-5e3a-a916-727ccfbeeedc_secondary | grep rootServer
                        "rootServerUrl="
                        "rootServerUrl="
```

**Expected behavior**
rootServerUrl should be set with correct value for staging, `root.atsign.wtf`

**Additional context**
Background to how this is supposed to work is in https://github.com/atsign-foundation/at_server/issues/214 and https://github.com/atsign-foundation/at_server/issues/296 

As a stopgap:
1. I manually patched some containers yesterday to set correct rootServerUrl 
2. Chris is currently running a script to chug through all staging secondaries and set the correct rootServerUrl:
```
#!/usr/bin/env bash

set -e

EXCLUDE_LIST="(_db|portainer|broker|traefik|prune|logspout|NAME)"

for service in $(sudo docker service ls | egrep -v $EXCLUDE_LIST |
                 awk '{print $2}'); do
  sudo docker service update --force $service --env-add rootServerUrl=root.atsign.wtf
done
```
3. I have modified /root/.env on staging0001-01, adding `export root_server_url="root.atsign.wtf"`

**Comment by gkc** [comment]
@kumarnarendra701 looks like the thing that was missing here was the line I've added now to /root/.env on staging0001-01 ... is the template for .env in a repo somewhere?

**Comment by cpswan** [comment]
@gkc it's at https://github.com/atsign-company/secondaries-scripts/blob/trunk/env_example

**Comment by cpswan** [comment]
@kumarnarendra701 I think the actions in 1,2,3 take care of the immediate situation, so now we just need a script to run through the existing docker-compose.yml files and ensure they have a correct rootServerUrl set.

**Comment by kumarnarendra701** [comment]
@cpswan @gkc - There are 63 secondaries that are missing the environment for the root URL in the docker-compose.yml file. So I have updated the file and stacks.
