### ISSUE TITLE
null commit id is getting updated in commit log

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#717]
**Describe the bug**
* while testing app like CATWEB which updates the same key with different values at periodic intervals, null commit id entries are seen on server commit log

**To Reproduce**
Steps to reproduce the behaviour:
* happens intermittently while testing CATWEB app or running at client sample which updates same key multiple times with few seconds delay between updates

**Expected behaviour**
* server commit entry should never contain null value

**Were you using an @‎application when the bug was found?**
  - CATWEB

**Comment by murali-shris** [comment]
- add() method in CommitLogKeyStore is seen creating entries in the commit log with null commit id’s. We have seen this happening a number of times in the past. When this happens system goes into an inconsistent state and we have to deal with this at various places.

    - One possible cause of null commit ID is, the server unexpectedly restarting between the add and put invocations on the hive box in add method of the CommitLogKeyStore

It is worth analysing how to recover from unexpected server crashes. For example, what if put to key store is successful but an entry to commit log could not be made.

    - We do not yet know if there is anything else that causes a null to be inserted for a commit id. The objective of this task is to analyse the same and document the findings.

**Comment by sitaram-kalluri** [comment]
One of potential cause of having null commitId's to be inserted into the commit log keystore when server restarts during the updating the commit id.

Fixed the issue with the following [PR](https://github.com/atsign-foundation/at_server/pull/734)
