### ISSUE TITLE
server stops sending  periodic notifications for commit log stats

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#720]
- Secondary server stops sending periodic stats notifications
   - When the server gets into this state it does respond to other verbs (Ex: scan), however, it is just stuck sending the stats notification
   - What is also observed is that server somehow recovers from this state automatically after a very long time

**Comment by sitaram-kalluri** [comment]
Moving the PR to PR 39 - PR review pending and releasing to canary. Reducing the SP to 1 SP
