### ISSUE TITLE
2 secondaries for 1 atsign 99thirsty1

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#728]
**Describe the bug**
secondary for 99thirsty1 was not created properly.  When I requested to create it again it created 2nd secondary for the atsign

**Expected behavior**
2 secondaries should not be there for 1 atsign. 

**Screenshots**
![image](https://user-images.githubusercontent.com/61007675/171445632-a1a3ae2e-cab3-4843-93de-18d857529ebb.png)
cconstab@swarm0002-01:~$ docker service inspect --pretty  6c314a20-71e9-55a9-b4a8-a4136bf2e8e9_secondary

ID:             q6ffpqulsdupqrb2k6gs69nk5
Name:           6c314a20-71e9-55a9-b4a8-a4136bf2e8e9_secondary
Labels:
 com.docker.stack.image=reg.swarm0001.atsign.zone/atsigncompany/secondary:prod
 com.docker.stack.namespace=6c314a20-71e9-55a9-b4a8-a4136bf2e8e9
Service Mode:   Replicated
 Replicas:      0
Placement:
 Constraints:   [node.role == worker]
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         reg.swarm0001.atsign.zone/atsigncompany/secondary:prod@sha256:21d53f5753b09ed79f72989921a5639bc97f28f67bef4fd3a2cf0ef437ec52d0
 Args:          -a @99thirsty1 -p 4334 -s d095095931b54096d87c9aed4d4af1b0554b1a96c633cc1ce6b2aeb03d6b70cd78210dc7c5449c8d49ff34a0d76ea2b880b92f30938fc92e8e2b598fbf51de1d
Mounts:
 Target:        /atsign/certs
  Source:       /etc/letsencrypt/live/6c314a20-71e9-55a9-b4a8-a4136bf2e8e9.swarm0002.atsign.zone
  ReadOnly:     false
  Type:         bind
 Target:        /atsign/storage
  Source:       /gluster/@/secondaries/80/d7/e7/28/80d7e728b6c9a37e708830d908f81437/6c314a20-71e9-55a9-b4a8-a4136bf2e8e9/storage
  ReadOnly:     false
  Type:         bind
Resources:
 Reservations:
  Memory:       6MiB
 Limits:
  CPU:          0.25
  Memory:       50MiB
Networks: secondaries
Endpoint Mode:  vip
Ports:
 PublishedPort = 4334
  Protocol = tcp
  TargetPort = 4334
  PublishMode = ingress

cconstab@swarm0002-01:~$

cconstab@swarm0002-01:~$ docker service inspect --pretty  1744fcf1-8bb9-532a-82fc-f8ef2354fa20_secondary

ID:             4gxnknijuteys78wif4qes9p9
Name:           1744fcf1-8bb9-532a-82fc-f8ef2354fa20_secondary
Labels:
 com.docker.stack.image=reg.swarm0001.atsign.zone/atsigncompany/secondary:prod
 com.docker.stack.namespace=1744fcf1-8bb9-532a-82fc-f8ef2354fa20
Service Mode:   Replicated
 Replicas:      1
Placement:
 Constraints:   [node.role == worker]
UpdateConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:   1
 On failure:    pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:         reg.swarm0001.atsign.zone/atsigncompany/secondary:prod@sha256:21d53f5753b09ed79f72989921a5639bc97f28f67bef4fd3a2cf0ef437ec52d0
 Args:          -a @99thirsty1 -p 4368 -s ac8889956d2eefc1f29b3a1dac08f0a5ebe1bdc6770af270c1cbc5b699ca7c326c7d03862cc277f15a97515aa482ed4725c1bfdf45d6fe7b639e59f7f46e3d2d
Mounts:
 Target:        /atsign/storage
  Source:       /gluster/@/secondaries/80/d7/e7/28/80d7e728b6c9a37e708830d908f81437/1744fcf1-8bb9-532a-82fc-f8ef2354fa20/storage
  ReadOnly:     false
  Type:         bind
 Target:        /atsign/certs
  Source:       /etc/letsencrypt/live/1744fcf1-8bb9-532a-82fc-f8ef2354fa20.swarm0002.atsign.zone
  ReadOnly:     false
  Type:         bind
Resources:
 Reservations:
  Memory:       6MiB
 Limits:
  CPU:          0.25
  Memory:       50MiB
Networks: secondaries
Endpoint Mode:  vip
Ports:
 PublishedPort = 4368
  Protocol = tcp
  TargetPort = 4368
  PublishMode = ingress

**Comment by kumarnarendra701** [comment]
@athandle @cpswan - Based on logs analysis, found below observations.
First Node API tried to delete secondaries on "May 30 00:28" and it seems there was no stack available for the secondary.
```
root@swarm0002-01:/gluster/@/api/secondaries-logs/delete# ls -lrt |  grep 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9
-rw-r--r-- 1 nobody 4294967294   127 May 30 00:28 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9-delete_log.txt
root@swarm0002-01:/gluster/@/api/secondaries-logs/delete# 
root@swarm0002-01:/gluster/@/api/secondaries-logs/delete# 
root@swarm0002-01:/gluster/@/api/secondaries-logs/delete# cat 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9-delete_log.txtSecondaries delete started
Nothing found in stack: 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9
314776762
Secondaries delete completed
```
And then it tried to create secondary on "May 30 13:03" 

```
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# ls -lrt |  grep 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9-rw-r--r-- 1 nobody 4294967294    808 May 30 13:03 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9-create.log
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# cat 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9-create.log
Secondary creation started.
99thirsty1
4334
6c314a20-71e9-55a9-b4a8-a4136bf2e8e9
80/d7/e7/28/80d7e728b6c9a37e708830d908f81437
d095095931b54096d87c9aed4d4af1b0554b1a96c633cc1ce6b2aeb03d6b70cd78210dc7c5449c8d49ff34a0d76ea2b880b92f30938fc92e8e2b598fbf51de1d
swarm0002
/etc/letsencrypt/live/6c314a20-71e9-55a9-b4a8-a4136bf2e8e9.swarm0002.atsign.zone
notAfter=Aug 27 06:46:38 2022 GMT
Certificate will not expire
Given certificate is valid.
ID           Type     Name                                    Data                        Priority    Port    TTL     Weight
314776762    CNAME    6c314a20-71e9-55a9-b4a8-a4136bf2e8e9    swarm0002.lb.atsign.zone    0           0       1800    0
Creating service 6c314a20-71e9-55a9-b4a8-a4136bf2e8e9_secondary
Secondary creation completed.
--------------------------------
```

Again new secondary request on Jun  1 15:23

```
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# ls -lrt | grep  1744fcf1-8bb9-532a-82fc-f8ef2354fa20
-rw-r--r-- 1 nobody 4294967294    808 Jun  1 15:23 1744fcf1-8bb9-532a-82fc-f8ef2354fa20-create.log
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# 
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# 
root@swarm0002-01:/gluster/@/api/secondaries-logs/create# cat 1744fcf1-8bb9-532a-82fc-f8ef2354fa20-create.log
Secondary creation started.
99thirsty1
4368
1744fcf1-8bb9-532a-82fc-f8ef2354fa20
80/d7/e7/28/80d7e728b6c9a37e708830d908f81437
ac8889956d2eefc1f29b3a1dac08f0a5ebe1bdc6770af270c1cbc5b699ca7c326c7d03862cc277f15a97515aa482ed4725c1bfdf45d6fe7b639e59f7f46e3d2d
swarm0002
/etc/letsencrypt/live/1744fcf1-8bb9-532a-82fc-f8ef2354fa20.swarm0002.atsign.zone
notAfter=Aug 29 09:22:54 2022 GMT
Certificate will not expire
Given certificate is valid.
ID           Type     Name                                    Data                        Priority    Port    TTL     Weight
315365655    CNAME    1744fcf1-8bb9-532a-82fc-f8ef2354fa20    swarm0002.lb.atsign.zone    0           0       1800    0
Creating service 1744fcf1-8bb9-532a-82fc-f8ef2354fa20_secondary
Secondary creation completed.
--------------------------------
```

**Comment by cpswan** [comment]
@kumarnarendra701 thanks. I think we now have a picture of **what** happened, but maybe we still don't understand **why** (and maybe that's why @athandle wants extra logging).

**Comment by athandle** [comment]
@cpswan I added extra logging for delete secondary as well.
I think this issue was related to https://github.com/atsign-foundation/at_server/issues/735 
where success was not returning. Hopefully, this will not happen again. But will keep an eye.
