### ISSUE TITLE
@kevin secondary infra was not deleted properly 

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#735]
**Describe the bug**
@kevin secondary infra was not deleted properly 

Info: It was on canary

**Expected behavior**
Infra should delete cleanly

**Screenshots**
![image](https://user-images.githubusercontent.com/61007675/171809573-39dba694-1141-4ccc-9805-8594bc23021d.png)
![image](https://user-images.githubusercontent.com/61007675/171809627-628e5821-be7f-4cd4-9ffb-a48cc2863810.png)

**Comment by athandle** [comment]
@cconstab looks kevin atsign was expired and was deleted because of that

The secondary was not deleted properly because of a warning thrown, hopefully that was the root cause we will try to replicate tomorrow and will fix the same as required

**Comment by kumarnarendra701** [comment]
@athandle - The node code detects SSH connection waring msg as an error. So we need to ignore this string "Error: Writing 3 keys to /root/.ssh/google_compute_known_hosts"

**Comment by athandle** [comment]
this is fixed. Hopefully the issue will not reproduce in future. But we need to track how many such atsigns are there that were not deleted properly
@cconstab  any quick way to check?
