### ISSUE TITLE
Prod releases from Canary images

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#750]
**Is your feature request related to a problem? Please describe.**

Generally we want to promote a well tested Canary release rather than cut a new Prod release, as this might have **slightly** different underlying dependencies.

**Describe the solution you'd like**

Use a Dockerfile that takes the most recent Canary as its base and add a newer pubspec.yaml to carry prod release version.

**Describe alternatives you've considered**

We could spend more effort on creating repeatable builds.

**Comment by cpswan** [comment]
Still waiting on #706 to be completed before this can be put in place, so bumping to PR41

**Comment by kumarnarendra701** [comment]
@cpswan - As suggested added workflow to deploy the canary image to prod. Please review the PR.
https://github.com/atsign-foundation/at_server/pull/817

**Comment by cpswan** [comment]
Moving to PR42, just needs to be merged and tested,

**Comment by kumarnarendra701** [comment]
@cpswan - Please let me know if any work is required on this ticket or can we close this?

**Comment by cpswan** [comment]
@kumarnarendra701 this still needs to be tested. The plan is for @gkc and I to run it under supervision on Thu 4 Aug.

**Comment by kumarnarendra701** [comment]
@cpswan @gkc - Any update on this?

**Comment by cpswan** [comment]
We had planned to test the functionality last Thu, but that's now been moved to tomorrow (Tue 9), so bumping this to PR43.

**Comment by cpswan** [comment]
Testing did not go well today, so adding some additional story points so that the workflow elements can be broken out into new workflows and tested.

**Comment by cpswan** [comment]
More testing now needed after #857 gets merged.

**Comment by cpswan** [comment]
Canary c3.0.21d was just release to prod using the new workflow.
