### ISSUE TITLE
Registrar: [Design & Impl Spike] Decouple AtSign reservation from secondary activation

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#785]
**Is your feature request related to a problem? Please describe.**
Currently as soon as the reservation process is complete, the secondary is activated. When we have IOT customers who want to reserve very large numbers of atSigns many of which will not need to be activated for a very long time, then, if we still have activation happening as soon as reservation is complete, we will consume lots of infrastructure for no reason. 

**Describe the solution you'd like**
Would like to decouple reservation from activation, so that an IOT partner can reserve atSigns at will, but only activate them at a later date when the activation is actually needed.

See the sequence diagram [here](https://github.com/atsign-company/gary-snippets/blob/main/diagrams/iot_provisioning-integration.md) for an outline of what we need in terms of process

**Additional context**
* I am defining "AtSign Reservation complete" as "The registrar has supplied the AtSign and CRAM Key to the requester"
* The 'activate' API method should require only the AtSign and its CRAMKey as parameters
* The 'reserve' parts of the flow will need a small bit of reworking so that it is possible at some stage for the requester to provide a 'deferActivation=true' parameter in order to prevent immediate activation

**Comment by athandle** [comment]
@gkc to generate cramkey we need uuid, it's hash of uuid.
Best we can do is to give an API to assign free atsign and when user will login, we can give cramkey.

Like we are doing in registrar site, users can get atsign and can activate later on

**Comment by gkc** [comment]
I don't think that will work for the use case. Let's talk - I'll grab some time with you tomorrow

**Comment by gkc** [comment]
Discussion moved to https://github.com/atsign-company/at_handle_registrar_web/issues/382

**Comment by gkc** [comment]
Closing this issue as we completed design and @athandle has a working spike implementation. Created new issue at #796 for completion of the implementation
