### ISSUE TITLE
Registrar: [Design & Impl Spike] Enable some registrar requests to bypass or streamline the OTP validation step

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#786]
**Is your feature request related to a problem? Please describe.**
One-time PIN requests are perfect for when humans are reserving new AtSigns. However the current mechanism is a blocker for a partner system reserving hundreds or thousands or millions of AtSigns.

**Describe the solution you'd like**
Either
1. Bypass OTP validation
  * A customer can tag one or more of their API keys as 'No OTP validation required'
  * When an AtSign is reserved using an API key tagged as such, then the OTP validation steps are bypassed
2. Streamline OTP validation
  * Customer can tag one or more of their API keys with a WebHook where we can POST a message containing [AtSign, OTP]
  * Customer can then supply the OTP through the current API

**Additional context**
See also #785

**Comment by athandle** [comment]
@gkc in either case we have to trust API key owner that the owner will not misuse

**Comment by gkc** [comment]
Yes these will usually be special partnerships; OTP via webhook would preserve a second auth factor; I'm not sure it's really necessary, but it would keep the overall flow very similar to current flow

**Comment by gkc** [comment]
Closing this issue as we completed design and @athandle has a working spike implementation. Created new issue at #796 for completion of the implementation
