### ISSUE TITLE
feat: Complete implementation of IOT partner Registrar APIs for atsign reservation and activation

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#796]
Follow-on from #785 and #786

**Comment by gkc** [comment]
Hi Ashish - I've created this as a new issue because I think we can close the 'design and implementation spike' tickets from last sprint

**Comment by gkc** [comment]
In addition to @athandle's work to wrap up the registrar implementation, we also need to update the registration / activation parts of the Java and Dart Registration / Onboarding CLIs @srieteja we will need your help on that portion

**Comment by srieteja** [comment]
Certainly! Let's schedule a call and discuss what needs to be done so we can have a clear picture of everything moving forward. @gkc and @athandle when do you prefer we schedule this call?

**Comment by athandle** [comment]
any day 12 noon IST works with me

**Comment by athandle** [comment]
@gkc atSign generated by 1 API key should be allowed to be activated by another super API key or not?
As of now, any super API key can activate atSigns generated by other super API keys

Secondly, do we need to put any rate limiter to these APIs like 1 key can generate these many atsigns in a certain amount of time?

**Comment by gkc** [comment]
> @gkc atSign generated by 1 API key should be allowed to be activated by another super API key or not? As of now, any super API key can activate atSigns generated by other super API keys

(1) I would say the answer is no, but (2) I thought we had agreed activation would only require atSign and activation key, not the API key that registered the atSign. Intent being that an IOT device would only need to be provisioned with its atSign and the activation key for that atSign?

> 
> Secondly, do we need to put any rate limiter to these APIs like 1 key can generate these many atsigns in a certain amount of time?

Two separate questions here (1) rate limiting based on whatever capacity we have available at the time (2) quotas within a period. I think the answer to both is yes but they are different things.

**Comment by athandle** [comment]
> > @gkc atSign generated by 1 API key should be allowed to be activated by another super API key or not? As of now, any super API key can activate atSigns generated by other super API keys
> 
> (1) I would say the answer is no, but (2) I thought we had agreed activation would only require atSign and activation key, not the API key that registered the atSign. Intent being that an IOT device would only need to be provisioned with its atSign and the activation key for that atSign?
> 
> > Secondly, do we need to put any rate limiter to these APIs like 1 key can generate these many atsigns in a certain amount of time?
> 
> Two separate questions here (1) rate limiting based on whatever capacity we have available at the time (2) quotas within a period. I think the answer to both is yes but they are different things.

Thanks @gkc for clarification,  I missed the first part. It's fixed now. The only concern is that we have a restriction of max atSigns an API key can activate. Either we have to remove this restriction or I can do reverse engineering. I can use from which API key this atSign was generated and then will add restriction. Please confirm.

Rate limit based on capacity is already in place. By capacity I mean no. of atSigns an API key is allowed which is set by admin.

Can you confirm what should be the restriction like no. of atSigns reservation per hour and no. of activation per hour. Can you please confirm the numbers.

**Comment by gkc** [comment]
> a restriction of max atSigns an API key can activate

The max number needs to be changeable, by us, for a given API key.


> I can use from which API key this atSign was generated and then will add restriction

sounds good except the max number for the restriction for a given API key needs to be changeable by us


> Can you confirm what should be the restriction like no. of atSigns reservation per hour and no. of activation per hour. Can you please confirm the numbers.

I can't confirm those numbers. We should discuss on the next architecture call. However I believe reservation per hour should be a very high number, since the reservation operation isn't doing very much, and reservations are likely to be 'bursty'. Activations of previously reserved atSigns will likely be spread out over a much longer period of time. All of these numbers will change over time, and over time we can scale up our infrastructure to cope with load

**Comment by gkc** [comment]
I believe the client-side work to consume the new APIs is largely complete, moving to PR43 for PR reviews and merging

**Comment by gkc** [comment]
Thanks @stulluri - I have approved the PR. @athandle please feel free to release the v3 API to prod at your convenience - thank you!

**Comment by athandle** [comment]
@gkc moved to prod, can we close this now?

**Comment by gkc** [comment]
Yep!
