### ISSUE TITLE
Update help text language and onboarding documents for API key

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#797]
Update documentation - Now API key developer can generate from registrar website instead of requesting admin

- [x] Update help text in registrar
- [ ] Update onboaridng widget documentation

**Comment by athandle** [comment]
Steps to generate API key :

1. Open URL https://my.atsign.com/login
2. Login with valid credentials 
3. Click on My atSign on the dashboard 
4. Click on atSign for which you want to generate an API key 
5. Click on the manage button
6. Click on Advance settings 
7. Click on "Generate New API key" and observe the screen 

Video for reference:  https://somup.com/c3iY6GuZe5

**Comment by nitesh2599** [comment]
@athandle I have added the same into the new onboarding readme [here](https://github.com/atsign-foundation/at_widgets/blob/feature/on-boarding-3.0/at_onboarding_flutter/README.md).

**Comment by athandle** [comment]
@tinashe404 can you please review the same and please create video in vimeo or youtube for help

**Comment by tinashe404** [comment]
@athandle Sure i will arrange for a video to be made

**Comment by JeremyTubongbanua** [comment]
https://www.youtube.com/watch?v=HVa8-X7RpNY

"Atsign API keys in 90 secs"

**Comment by athandle** [comment]
@tinashe404 @cconstab can we please freeze the content for this? It's been carry forwarded for long time

**Comment by tinashe404** [comment]
Yes! Frozen. The only thing we were waiting for was for you to do the work that allows activation tracking so we can put the video out

**Comment by athandle** [comment]
This API key is used to generate free atSigns in the onboarding widget. With this, you can track how many free atSigns are generated through your app and how many free and/or paid atSigns were activated using your app.

Each atSign has its own microservice which can be run anywhere. Atsign runs these for you but you can use Distributed Edge Secondary Server (dess) to run your own secondary server. To do this, your server will need to have a dedicated DNS address, port number and an SSL certificate to allow TLS encrypted communications.

**Comment by HimanQA** [comment]
@athandle check the below screenshots
![image](https://user-images.githubusercontent.com/105912666/191310799-447abb8b-2b84-4609-a9f8-39600af3f148.png)
![image](https://user-images.githubusercontent.com/105912666/191310980-7c346751-26f0-4afc-8fec-fe1572fc512e.png)
