### ISSUE TITLE
Rsync backups failing on Swarm-001

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#799]
**Describe the bug**
Rsync is failing and not giving any notice to admin. 

**To Reproduce**
1. First try and log into the backup machine
3. Then find it is not answering request at all (ssh)
4. Notice that rsync is failing but it is not alerting us of that failure!
5. And then reboot backup machine
6. Rysnc now working but we need to check/alert of failures of backups to AWS

**Expected behavior**
 We need to check/alert of failures of backups to AWS machine

**Screenshots**
```
gluster/@/etc/letsencrypt/live/02bcaa00-5af2-5cff-914b-9c626b4b0aea.swarm0002.atsign.zone/privkey.pem
          1,704 100%    2.06kB/s    0:00:00 (xfr#4524, ir-chk=1006/96449)
gluster/@/etc/letsencrypt/live/02c176f6-79f4-50f3-9dce-9fddee811a51.swarm0001.atsign.zone/
gluster/@/etc/letsencrypt/live/02c176f6-79f4-50f3-9dce-9fddee811a51.swarm0001.atsign.zone/02c176f6-79f4-50f3-9dce-9fddee811a51.swarm0001.atsign.zone.csr
            956 100%    1.14kB/s    0:00:00 (xfr#4525, ir-chk=1005/96464)
gluster/@/etc/letsencrypt/live/02c176f6-79f4-50f3-9dce-9fddee811a51.swarm0001.atsign.zone/02c176f6-79f4-50f3-9dce-9fddee811a51.swarm0001.atsign.zone.log
          8,174 100%    9.64kB/s    0:00:00 (xfr#4526, ir-chk=1004/96464)
```
backup via rsync now working

**Additional context**
Alert of failure should be sent to Gchat I would  think... wrapping the existing rsync with a check for success and noting failure to Gchat is likley the simple/safe route

**Comment by kumarnarendra701** [comment]
@cpswan - I have observed a high CPU during rsync due to less CPU and memory on the EC2 machine. We need to upgrade the EC2 machine.

![image](https://user-images.githubusercontent.com/29299536/179982637-4f5b6dfb-2a45-4f8e-a5d5-f9e66288afc9.png)

Added checks for rsync process for an alert. Please review PR.
https://github.com/atsign-company/secondaries-scripts/pull/54

**Comment by cconstab** [comment]
The high CPU was due to many concurrent rayncs running..
The new script should check previous run has finished. The CPU and memory on remote machine are just fine..

For the moment I have put the cronjob on swarm0001 to every two hours

**Comment by kumarnarendra701** [comment]
This is already done and PR is raised. @cconstab @cpswan - Please review.

**Comment by kumarnarendra701** [comment]
@cpswan - Script deployed on Staging and Swarm cluster.

**Comment by cpswan** [comment]
@kumarnarendra701 we need better error messages than `Error - Error while running Rsync.`

The error message should provide some indication of what went wrong and why that happened.

**Comment by kumarnarendra701** [comment]
@cpswan - We have disabled Rsync cronjob due to failure.

**Comment by athandle** [comment]
@cpswan can we close this ticket or do you think we have to do any workaround for this
