### ISSUE TITLE
Exception: public:publickey is not well-formed key

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#820]
**Describe the bug**
Some how the key `public:publickey` is accepted on the secondary/client but one in place is disturbs the sync process.

**To Reproduce**
1. First use atTalk between two atSigns
2. At some point this key is created - needs further investigation as to why/how
3. And then every sync results in a lot of noise/traffic trying to sync this key
4. 

**Expected behavior**
Never accept a malformed key on the atClient or Secondary. If one is created it should be deleted (the delete verb does not allow this key to be deleted manually)

**Screenshots**
```
SEVERE|2022-07-22 14:11:05.479238|SyncService|exception syncing entry to local {atKey: public:publickey, value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVLEk3IbJlFxtX4gAfw3RmEuEAkG7fY3bARun9SPDE2j0m8SZFLi/Rnu/6YC5o7zsubpgec/aIgaLC+NTLvHWU2RmZeluinRUb0wT+mdv6uX67IXRPpbHSZsZDlgDyySEtn2NgFzBwxtdumtOHaJ5z2XpZdz4yeznULWcQlu/a8542liUan8kElIsmKTIYax2VCfcA+jSEfWyAxUE//hQT7svbvfV2Zv+igldaCVhO65viRjdGIX9+Nr6MAz66JtKpdy+jWS/tknMBEXh79dTMyC1G+52i1/TQXgPe64x2jplzFN8BEpZYY9BCoDZceqnJySZFSBvHp01/06MBY1SwIDAQAB, metadata: {ttl: 0, ttb: 0, ccd: false, isBinary: false, isEncrypted: false, createdAt: 2022-07-22 19:33:57.971Z, updatedAt: 2022-07-22 19:33:57.971Z}, commitId: 1191, operation: *} - Exception: public:publickey is not well-formed key

SEVERE|2022-07-22 14:11:20.469205|SyncService|exception syncing entry to local {atKey: public:publickey, value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVLEk3IbJlFxtX4gAfw3RmEuEAkG7fY3bARun9SPDE2j0m8SZFLi/Rnu/6YC5o7zsubpgec/aIgaLC+NTLvHWU2RmZeluinRUb0wT+mdv6uX67IXRPpbHSZsZDlgDyySEtn2NgFzBwxtdumtOHaJ5z2XpZdz4yeznULWcQlu/a8542liUan8kElIsmKTIYax2VCfcA+jSEfWyAxUE//hQT7svbvfV2Zv+igldaCVhO65viRjdGIX9+Nr6MAz66JtKpdy+jWS/tknMBEXh79dTMyC1G+52i1/TQXgPe64x2jplzFN8BEpZYY9BCoDZceqnJySZFSBvHp01/06MBY1SwIDAQAB, metadata: {ttl: 0, ttb: 0, ccd: false, isBinary: false, isEncrypted: false, createdAt: 2022-07-22 19:33:57.971Z, updatedAt: 2022-07-22 19:33:57.971Z}, commitId: 1191, operation: *} - Exception: public:publickey is not well-formed key

SEVERE|2022-07-22 14:11:35.474199|SyncService|exception syncing entry to local {atKey: public:publickey, value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVLEk3IbJlFxtX4gAfw3RmEuEAkG7fY3bARun9SPDE2j0m8SZFLi/Rnu/6YC5o7zsubpgec/aIgaLC+NTLvHWU2RmZeluinRUb0wT+mdv6uX67IXRPpbHSZsZDlgDyySEtn2NgFzBwxtdumtOHaJ5z2XpZdz4yeznULWcQlu/a8542liUan8kElIsmKTIYax2VCfcA+jSEfWyAxUE//hQT7svbvfV2Zv+igldaCVhO65viRjdGIX9+Nr6MAz66JtKpdy+jWS/tknMBEXh79dTMyC1G+52i1/TQXgPe64x2jplzFN8BEpZYY9BCoDZceqnJySZFSBvHp01/06MBY1SwIDAQAB, metadata: {ttl: 0, ttb: 0, ccd: false, isBinary: false, isEncrypted: false, createdAt: 2022-07-22 19:33:57.971Z, updatedAt: 2022-07-22 19:33:57.971Z}, commitId: 1191, operation: *} - Exception: public:publickey is not well-formed key

```

```
cconstab@servalan:~/at_talk$ openssl s_client -tls1_2 -ign_eof -quiet f39f7dba-9b03-5e9e-b708-2326cbcac1a3.swarm0002.atsign.zone:3643
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = f39f7dba-9b03-5e9e-b708-2326cbcac1a3.swarm0002.atsign.zone
verify return:1
@scan
data:["publickey","publickey@iot_manager","signing_publickey@iot_manager"]
@
```

**Were you using an @‎application when the bug was found?**
  - atTalk / at_talk

**Additional context**
Why this is happening is also high priority and part of this ticket

**Comment by cconstab** [comment]
We need a way to clean up atSigns that have this key in place as delete does not work neither does lookup..

```
cconstab@servalan:~/at_talk$ openssl s_client -tls1_2 -ign_eof -quiet e32bbf28-4350-53eb-a7b2-0a08829d485f.swarm0002.atsign.zone:3644
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = e32bbf28-4350-53eb-a7b2-0a08829d485f.swarm0002.atsign.zone
verify return:1
@scan
data:["cached:publickey@iot_device02","cached:publickey@iot_manager","publickey","publickey@iot_device01","signing_publickey@iot_device01"]
@lookup:publickey
error:AT0003-Invalid syntax : Invalid syntax. e.g lookup:location@bob
@read:errno=0
cconstab@servalan:~/at_talk$

```

but you can update a key it would seem and delete the key but the key stays in place. 


```
cconstab@servalan:~/at_talk$ openssl s_client -tls1_2 -ign_eof -quiet f39f7dba-9b03-5e9e-b708-2326cbcac1a3.swarm0002.atsign.zone:3643
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = f39f7dba-9b03-5e9e-b708-2326cbcac1a3.swarm0002.atsign.zone
verify return:1
@scan
data:["publickey","publickey@iot_manager","signing_publickey@iot_manager"]
@from:@iot_manager
data:_cb409226-473a-4c1d-a354-6263754626da@iot_manager:76ee9dd4-0333-453e-989f-3cfddfcfeab3
@scan
data:["publickey","publickey@iot_manager","signing_publickey@iot_manager"]
@pkam:ijYmNkgA6sUe+BPALi8msDR+ZseHcsagiQpahzEr/PN7YYcem1Ia0K/zHQ9uhv6R9tpMZisBUJ20UUy4fp8FqRFnzNugBSzSMMxDhrfKcjb0KFuCbTwFPfam65W6syP+XZh9KmXIwFe8SEzu1fM4u1R9HaFr6jSYSXKjn4EoEtlHRV/rFkEgecSpju3OXfCi9aL6QBGBCL4NM2Cr9UNjxEZRATt2vS4LfuKuwRo/uD9qNzQ4XGLtu4sczsrtBV45MFoGUmlUd1SWWMQB2HcwjMJm/+NPbjMV2212nYz1nendas/uCKTgMplJ3x3MuixF25sEyJUxCmFlgC2ZI+yriw==
data:success
@iot_manager@scan
data:["@garycasey:shared_key@iot_manager","@iot_device01:shared_key@iot_manager","@iot_device02:shared_key@iot_manager","@iot_manager:signing_privatekey@iot_manager","atconnections.garycasey.iot_manager.at_contact.mospherepro@iot_manager","cached:@iot_manager:shared_key@garycasey","cached:@iot_manager:shared_key@iot_device01","cached:@iot_manager:shared_key@iot_device02","cached:@iot_manager:shared_key@kevin","cached:public:publickey@garycasey","cached:public:publickey@iot_device01","cached:public:publickey@iot_device02","public:publickey","public:publickey@iot_manager","public:signing_publickey@iot_manager","publickey.iot_device01@iot_manager","publickey.iot_device02@iot_manager","senthistory_v2.mospherepro@iot_manager","shared_key.garycasey@iot_manager","shared_key.iot_device01@iot_manager"]
@iot_manager@update:publickey hello new data
data:1192
@iot_manager@delete:public:publickey
data:1193
@iot_manager@scan
data:["@garycasey:shared_key@iot_manager","@iot_device01:shared_key@iot_manager","@iot_device02:shared_key@iot_manager","@iot_manager:signing_privatekey@iot_manager","atconnections.garycasey.iot_manager.at_contact.mospherepro@iot_manager","cached:@iot_manager:shared_key@garycasey","cached:@iot_manager:shared_key@iot_device01","cached:@iot_manager:shared_key@iot_device02","cached:@iot_manager:shared_key@kevin","cached:public:publickey@garycasey","cached:public:publickey@iot_device01","cached:public:publickey@iot_device02","public:publickey","public:publickey@iot_manager","public:signing_publickey@iot_manager","publickey.iot_device01@iot_manager","publickey.iot_device02@iot_manager","publickeyhellonew","senthistory_v2.mospherepro@iot_manager","shared_key.garycasey@iot_manager","shared_key.iot_device01@iot_manager"]
@iot_manager@

```

looking up the key also fails..

```
@iot_manager@llookup:public:publickey@iot_manager
data:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVLEk3IbJlFxtX4gAfw3RmEuEAkG7fY3bARun9SPDE2j0m8SZFLi/Rnu/6YC5o7zsubpgec/aIgaLC+NTLvHWU2RmZeluinRUb0wT+mdv6uX67IXRPpbHSZsZDlgDyySEtn2NgFzBwxtdumtOHaJ5z2XpZdz4yeznULWcQlu/a8542liUan8kElIsmKTIYax2VCfcA+jSEfWyAxUE//hQT7svbvfV2Zv+igldaCVhO65viRjdGIX9+Nr6MAz66JtKpdy+jWS/tknMBEXh79dTMyC1G+52i1/TQXgPe64x2jplzFN8BEpZYY9BCoDZceqnJySZFSBvHp01/06MBY1SwIDAQAB
@iot_manager@llookup:public:publickey
error:AT0003-Invalid syntax : Invalid syntax. e.g llookup:location@bob
@iot_manager@read:errno=0
cconstab@servalan:~/at_talk$

```

**Comment by cconstab** [comment]
More detail on where this key comes from.. All you need to do is run atTalk and the key appears, no need to send any messages.. See below

```
cconstab@servalan:~/at_talk$ openssl s_client -tls1_2 -ign_eof -quiet fc950553-8f57-514b-ae1d-70f5fe8c8eac.swarm0002.atsign.zone:4711
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = fc950553-8f57-514b-ae1d-70f5fe8c8eac.swarm0002.atsign.zone
verify return:1
@scan
data:["publickey@smilingkangaroo","signing_publickey@smilingkangaroo"]
@scan
data:["publickey","publickey@smilingkangaroo","signing_publickey@smilingkangaroo"]
@
```

The only command that was run before the first and the second scan was :-


```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@smilingkangaroo" -t "@acidrock2"
Syncing your data.............
@smilingkangaroo:
```

**Comment by gkc** [comment]
Looks like at_onboarding_cli is doing the update to create the `public:publickey` entry (rather than as it should be, `public:publickey@<atSign>`
@srieteja:
* please can you create an issue in at_libraries and take it up in this coming sprint? See [line 168 in at_onboarding_service_impl.dart](https://github.com/atsign-foundation/at_libraries/blob/trunk/at_onboarding_cli/lib/src/at_onboarding_service_impl.dart#L168-L170) which doesn't append the owning atSign.
* I'd also really like to understand why Colin has only now started to encounter this - whether it's only just started happening because of changes elsewhere?, or whether it was happening before but has only just become visible?

@murali-shris we need to put a validation guard into the top of the persistence layer which will reject any malformed keys from getting into the data store. Can you create an issue for this please and take it up in this coming sprint?

@murali-shris @srieteja we also need a way to delete this malformed key. I'm tempted to do something really quick and dirty which is to add some cleanup code to the secondary server startup to delete it. (Because once we have consistent validation guard to prevent malformed keys ever getting into the data store, we won't have this problem any more)

**Comment by murali-shris** [comment]
> Looks like at_onboarding_cli is doing the update to create the `public:publickey` entry (rather than as it should be, `public:publickey@<atSign>` @srieteja:
> 
> * please can you create an issue in at_libraries and take it up in this coming sprint? See [line 168 in at_onboarding_service_impl.dart](https://github.com/atsign-foundation/at_libraries/blob/trunk/at_onboarding_cli/lib/src/at_onboarding_service_impl.dart#L168-L170) which doesn't append the owning atSign.
> * I'd also really like to understand why Colin has only now started to encounter this - whether it's only just started happening because of changes elsewhere?, or whether it was happening before but has only just become visible?
> 
> @murali-shris we need to put a validation guard into the top of the persistence layer which will reject any malformed keys from getting into the data store. Can you create an issue for this please and take it up in this coming sprint?
> 
> @murali-shris @srieteja we also need a way to delete this malformed key. I'm tempted to do something really quick and dirty which is to add some cleanup code to the secondary server startup to delete it. (Because once we have consistent validation guard to prevent malformed keys ever getting into the data store, we won't have this problem any more)

@gkc 
feature request for validation layer https://github.com/atsign-foundation/at_server/issues/821
Will work on the clean up code as a part of this issue - #820

**Comment by murali-shris** [comment]
Merged PR for invalidating commit log cache on key deletion https://github.com/atsign-foundation/at_server/pull/830 in persistence and published at_persistence_secondary_server 3.0.31

**Comment by murali-shris** [comment]
Merged PR https://github.com/atsign-foundation/at_server/pull/831 which fixes malformed keys on server startup.
Have to release server code to canary and prod

**Comment by srieteja** [comment]
PR that contains fix to correct the malformed public key in at_onboarding_cli has been merged. About to release the package. Link to PR: https://github.com/atsign-foundation/at_libraries/pull/211

**Comment by murali-shris** [comment]
server code released to canary..prod release pending

**Comment by murali-shris** [comment]
@cconstab Server has been released to production. please verify and close the issue

**Comment by gkc** [comment]
To be clear : Prod release has not happened. We made a new canary release today, but our attempt to release to prod did not work

**Comment by murali-shris** [comment]
server v3.0.21 has been released. closing this issue
