### ISSUE TITLE
Provide training mode for jit-snapshot

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#845]
**Is your feature request related to a problem? Please describe.**

I can compile a jit-snapshot of a secondary with Dart 2.18 using a command line such as:

```
 dart compile jit-snapshot -o secondary.jit bin/main.dart -a @testatsign -p 12345 -s Te$tS3cret
```

NB the ordering of options:
* `-o secondary.jit` is a compiler option, and comes before the target file `bin/main.dart`
* `-a @testatsign -p 12345 -s Te$tS3cret` are program options for the secondary

For this to work some additional dependencies need to be in place:

* certs need to be present in a `certs` directory
* `/etc/cacerts/caerts.pem` has to be present

With all that in place the secondary will start up, bind to a socket, create its storage directory for Hive etc.

But it won't exit and complete the compiler training cycle. It has to be forced to close by `Ctrl-C`

**Describe the solution you'd like**

An additional flag/option (e.g. `-t` or `--training`) that has fewer (or no) dependencies that takes the compiler through the cold start process then exits to produce a jit-snapshot that's ready to become a new secondary with its own parameters.

**Describe alternatives you've considered**

If we find the `-a -p -s` flags absent then maybe we can assume a training run and exit.

**Comment by gkc** [comment]
Will take this on in PR44
