### ISSUE TITLE
socket network behavior analysis

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#849]
**Is your feature request related to a problem? Please describe.**
We have seen bugs in the system where the behavior of the system could not be explained unless we have a deeper understanding of the internals of TCP. Under this task, we will analyze and come up with recommendations for dealing with unreliable networks.

**Describe the solution you'd like**
Come up with recommendations that can be brainstormed and implemented

**Describe alternatives you've considered**
NA

**Additional context**
NA

Task checklist:
- [x] 1. Log socket exceptions properly
- [x] 2. Analyse case when stale connections receive data
- [x] 3. Disable Nagle's algorithm(enable tcpNoDelay)

**Comment by VJag** [comment]
Work done so far:

https://docs.google.com/document/d/1doXuXpOJ2G4pFIm5dRbr8Mc98L2QAdDlEcJu4FRQrss/edit?usp=sharing

**Comment by ksanty** [comment]
Discussed on today's architecture call.  @cconstab will review.  @VJag what other next steps are on deck?  Will this require further architecture call discussion?

**Comment by VJag** [comment]
Yes, we need some more time to discuss what I have presented in the call yesterday.

**Comment by srieteja** [comment]
note: linking PRs to issue rather than linking issue to PRs as the latter will close the issue after merging any one PR

Task 1: 
> PR: https://github.com/atsign-foundation/at_server/pull/884 (most of the logs were already present added one more)

Task 3: 
> PR1: at_server: https://github.com/atsign-foundation/at_server/pull/892

> PR2: at_lookup: https://github.com/atsign-foundation/at_libraries/pull/227

**Comment by srieteja** [comment]
Task 2:
> PR: https://github.com/atsign-foundation/at_server/pull/908

**Comment by gkc** [comment]
@srieteja any update?

**Comment by srieteja** [comment]
@gkc the sub-tasks created under this issue(mentioned in the description) have been completed and tested. I'm currently working on getting the PRs merged.
