### ISSUE TITLE
Staging environment jubilee

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#872]
**Is your feature request related to a problem? Please describe.**

The staging environment was almost completely down for a couple of days last week due to work on #867, but it didn't seem to cause any major issues. So do we really need all those old secondaries? Or can we reset back to a clean staging environment and start over?

**Describe the solution you'd like**

Delete all existing staging secondaries, start over.

**Describe alternatives you've considered**

Identify any special secondaries that need to be kept.

**Comment by ksanty** [comment]
Medium priority after arch call discussion

**Comment by athandle** [comment]
Dev and staging deleted. Final check running will clear by tomorrow, Deleting which were neither in dev nor in staging.
Updated 2 SP for remaining work

**Comment by kumarnarendra701** [comment]
@cpswan @athandle - Removed all secondaries and data for the staging server.

**Comment by cpswan** [comment]
thanks @kumarnarendra701 I've been watching the numbers come down.
