### ISSUE TITLE
Upgrade swarm managers to Ubuntu 22.04.1

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#896]
- [x] staging
- [x] canary
- [x] swarm0004
- [x] swarm0003
- [x] swarm0002
- [x] swarm0001

**Describe the solution you'd like**
Upgrade each manager in turn. Ensure that key services are working. Give swarm time to stabilise.

**Describe alternatives you've considered**
Wait for 24.04 LTS

**Comment by cpswan** [comment]
@kumarnarendra701 can you give swarm0001 priority due to #903 (though obviously do staging and/or canary first so we're not starting this with our largest prod cluster).

**Comment by cpswan** [comment]
Priority upgraded to High due to #903

**Comment by athandle** [comment]
1 swarm remaining reduced SPs

**Comment by kumarnarendra701** [comment]
@cpswan - All swarms manager upgraded to 22.04.1.
