### ISSUE TITLE
Direct secondary logs to GCP

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#898]
**Is your feature request related to a problem? Please describe.**
Logs are presently held on worker nodes, which can make them difficult to access, and often provides an incomplete picture

**Describe the solution you'd like**
Configure docker daemons to send logs to GCP.

Chris to figure out approach, Narendra to then roll it out across swarms.

**Comment by cpswan** [comment]
/etc/docker/daemon.json set to `{"log-driver":"gcplogs"}` on staging0001

for worker nodes I used this script:

```bash
#!/bin/bash
START=03
END=06
DOMAIN="staging0001"
PROJECT="development-305719"
REGION="us-central1"
SSHCMD='echo "{\"log-driver\":\"gcplogs\"}" | sudo tee /etc/docker/daemon.json'
for i in $(seq -w ${START} ${END})
do
  HOST="${DOMAIN}-${i}"
  if ((10#$i % 3 == 1)); then
    ZONE="a"
  elif ((10#$i % 3 == 2)); then
    ZONE="b"
  else
    ZONE="c"
  fi
  echo "$HOST"
  gcloud compute ssh --zone "$REGION-$ZONE" --project "$PROJECT" "core@$HOST" \
   --command="$SSHCMD" -- -n
done
```

for managers I just ran:

```bash
SSHCMD='echo "{\"log-driver\":\"gcplogs\"}" | sudo tee /etc/docker/daemon.json'
eval $SSHCMD
```

the Docker services need to be restarted for this to take effect. In staging I simply did `sudo systemctl restart docker` on each worker, but we shouldn't do that in prod as it will be disruptive (and will happen anyway when we do the next Flatcar upgrade).

**Comment by cpswan** [comment]
Moving to Waiting for Upstream Dependencies as this won't be completed until we do the next Flatcar upgrade.

**Comment by kumarnarendra701** [comment]
@cpswan - I have executed the script for swarm0004 cluster. Can I do it for the rest clusters and close this ticket and on Upgrade flat this will reflect?

**Comment by cpswan** [comment]
@kumarnarendra701 I want to wait for a reason to restart the nodes (like a Flatcar upgrade) rather than having unnecessary disruption to the prod environment. This isn't something we need to rush just to get the ticket closed.

**Comment by kumarnarendra701** [comment]
@cpswan - Work is done and we can close this ticket.

**Comment by cpswan** [comment]
@kumarnarendra701 before we close can you please verify that logs are viewable/searchable in the GCP console

**Comment by cpswan** [comment]
Moving to PR49 and reducing to 1 SP for final verification.
