### ISSUE TITLE
Swarm manager dropping every other connection to secondaries

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_server#903]
**Describe the bug**
Every other connection to secondaries fails on swarm0001-01 other nodes and customer facing stuff looks just fine

**To Reproduce**
1. Easier to show than tell
```
root@swarm0001-01:/home/cconstab# openssl s_client -brief 127.0.0.1:14152
140564733986112:error:02002071:system library:connect:No route to host:../crypto/bio/b_sock2.c:110:
140564733986112:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=113
root@swarm0001-01:/home/cconstab# openssl s_client -brief 127.0.0.1:14152
Can't use SSL_get_servername
CONNECTION ESTABLISHED
Protocol version: TLSv1.3
Ciphersuite: TLS_AES_256_GCM_SHA384
Requested Signature Algorithms: ECDSA+SHA256:RSA-PSS+SHA256:RSA+SHA256:ECDSA+SHA384:RSA-PSS+SHA384:RSA+SHA384:RSA-PSS+SHA512:RSA+SHA512:RSA+SHA1
Peer certificate: CN = 43bfa693-1e50-59e6-a0af-4816d398db8a.swarm0001.atsign.zone
Hash used: SHA256
Signature type: RSA-PSS
Verification: OK
Server Temp Key: X25519, 253 bits
@
error:AT0003-Invalid syntax : invalid command
@CONNECTION CLOSED BY SERVER
root@swarm0001-01:/home/cconstab#
```

**Expected behavior**
Always to be able to connect 

**Additional context**

Seems this is a Docker Swarm issue that others have hit when a node has been busy but not much on the GitHub pages to explain how to get out of the failure.
 Figure I would leave alone as we are planning on upgrading the management nodes.

**Comment by cpswan** [comment]
Although #896 hasn't been applied to swarm0001 yet, this seems to have been cleared by the worker reboots that happened during #895

I'd also note that at no time did this manifest in seccheck or any other tests/apps using swarm0001
