### ISSUE TITLE
Set auto SSL renewal for https://directory.atsign.wtf/

### ISSUE THREAD

**Issue by athandle** [atsign-foundation/at_server#924]
As of now we have to renew manually can we setup letsencrypt SSL auto-renewal for this dev site

**Comment by kumarnarendra701** [comment]
@cpswan - Created workflow to renew certs for directory.atsign.wtf. Please review and let me know if any changes are required.
https://github.com/atsign-company/at_find_api/pull/66

**Comment by cpswan** [comment]
Presently open PR is https://github.com/atsign-company/at_find_api/pull/67

Still waiting on @kumarnarendra701 to respond to requests for change. Bumping to PR47 and reducing to 2SP.

**Comment by kumarnarendra701** [comment]
@cpswan - Please review the below PR.
https://github.com/atsign-company/at_find_api/pull/67
https://github.com/atsign-company/secondaries-scripts/pull/59

**Comment by cpswan** [comment]
This is nearly ready to merge, bumping to PR48 and reducing to 1SP
