### ISSUE TITLE
Retrieve the AtNotification using the notification-id

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#931]
**Is your feature request related to a problem? Please describe.**
- Feature request to provide capability to retrieve the AtNotification object using the notification-id. 

- At the moment, only way to retrieve the notifications is query using the `notify:list` which returns a list of notifications; but user cannot retrieve a specific notification using the notification id.

**Describe the solution you'd like**
- Provide a new variant of notify which enables to retrieve the AtNotification object using the notification id

**Comment by ksanty** [comment]
Move to high after arch discsussion

**Comment by sitaram-kalluri** [comment]
As per the discussion in the architecture call, introduce a new verb that takes notification-id as input and returns the AtNotification object. 
Proposed verb:  `notify:fetch:<notification-id>` 

Please let me know if the proposed verb sounds good or needs a modification.

**Comment by gkc** [comment]
Pretty much completed during PR46. Last bits of review feedback to complete, then publishing / releasing etc.

@kalluriramkumar please can you link to the various relevant PRs

**Comment by sitaram-kalluri** [comment]
Done with the changes on at_server and merged to trunk branch. Completed coding in at_client. Pending work: Raise PR in at_client

**Comment by sitaram-kalluri** [comment]
The changes on the at_server is released to canary in v3.0.24

**Comment by gkc** [comment]
Waiting for
1. 3.0.24 to be released to prod
2. https://github.com/atsign-foundation/at_client_sdk/pull/738 to finish review process, be merged and new at_client package published

**Comment by sitaram-kalluri** [comment]
The changes are merged to the trunk branch. Pending publishing. Hence re-opening. No SP is required.

**Comment by sitaram-kalluri** [comment]
The changes are published in at_client 3.0.44
