### ISSUE TITLE
notify:messageType:text behaviour

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_server#969]
I assume that this is how you send a Notification of type Message.Text:

`notify:messageType:text:<@receiver>:<message 123>`

So I run this (as the atSign @fascinatingsnow):

`notify:messageType:text:@smoothalligator:test 123`

`=> data:d5c7ac4f-645b-4fa7-94c3-3a91885dcf09`

And this is what the notification looks like:

```
{
    "id": "d5c7ac4f-645b-4fa7-94c3-3a91885dcf09",
    "from": "@fascinatingsnow",
    "to": "@smoothalligator",
    "key": "@smoothalligator:test 123",
    "value": null,
    "operation": "null",
    "epochMillis": 1665586591188,
    "messageType": "MessageType.text",
    "isEncrypted": false
  }
```

Should `value:` be null? And should the `key:` look like that?

**Comment by sitaram-kalluri** [comment]
@JeremyTubongbanua : That is expected. As per the design, with message type 'text', the value will be null and the text will be part of the key.

**Comment by JeremyTubongbanua** [comment]
Thank you @kalluriramkumar
