### ISSUE TITLE
Set auto SSL renewal for *.dev.atsign.cloud

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#990]
### Is your feature request related to a problem? Please describe.

This domain is presently using a manually generated cert, which leads to admin overhead.

### Describe the solution you'd like

Switch to auto generation like #924 

### Describe alternatives you've considered

We could extend monitoring to the domains used by this cert

### Additional context

Should be pretty straightforward given the work already done for #924, so will give this 2SP

**Comment by kumarnarendra701** [comment]
@cpswan - Added GitHub workflow and raised PR for your review.
https://github.com/atsign-company/infrastructure_root_manager/pull/23
